Azure/BatchExplorer

Readme.md
app/app.component.ts
app/components/account/add/account-create-dialog.component.ts
app/components/account/details/account-details.component.ts
app/components/account/home/account-home.component.ts
app/services/account-service.ts

Fix #8 
Bug: 
* Adding your first account was not selecting it automatically.
* Deleting an account will unactivate it and activate the next if available.
Feature:
* Clicking on an account in the account list page will activate it.

Fix account create experience fix #8

---

app/components/job/action/add/job-create-basic-dialog.component.ts
app/components/job/details/job-details.component.ts
app/components/job/details/job-details.html
app/components/pool/action/add/pool-create-basic-dialog.component.ts
app/components/task/action/add/task-create-basic-dialog.component.ts
app/components/task/details/task-details.component.ts
app/components/task/details/task-details.html
app/models/forms/createJobModel.ts
app/models/forms/createTaskModel.ts

Clone job and tasks

---

.travis.yml
app/assets/styles/base/forms.scss
app/components/base/base.module.ts
app/components/base/form-error/form-error.component.ts
app/components/base/form-error/index.ts
app/components/pool/action/add/pool-create-basic-dialog.html
karma.conf.js
test/app/components/base/form-error/form-error.component.spec.ts
test/utils/helpers/index.ts
test/utils/helpers/template-interaction.ts
test/utils/helpers/template-queries.ts

Form error and some test helpers

---

app/index.html
config/webpack.config.dev.js
package.json

Changed default port, added repo field in package.json

---

app/assets/styles/base/forms.scss
app/components/base/create-form/create-form.component.ts
app/components/base/create-form/create-form.html
config/karma.shim.js
karma.conf.js
test/app/components/base/create-form/create-form.spec.ts

Create form error show reqeuest id and time

---

app/components/base/quick-list/quick-list-item.component.ts
app/components/base/quick-list/quick-list.component.ts
app/components/base/selectable-list/selectable-list-base.ts
app/components/base/selectable-list/selectable-list-item-base.ts
app/components/base/table/table-row.component.ts
app/components/base/table/table.component.ts
app/components/pool/action/add/pool-create-basic-dialog.html

* Cleanup the selectable list made possible by angular 2.3.0 component inheritance
* Fix ctrl/cmd click not working on mac
* Added ctrl/cmd click unselect selected element.

List cleanup with angular 2.3.0 inheritance

---

app/app.component.ts
app/app.layout.html
app/assets/styles/base/notifications.scss
app/assets/styles/main.scss
app/components/base/base.module.ts
app/components/base/form/action-form/action-form.component.ts
app/components/base/form/create-form/create-form.component.ts
app/components/base/notifications/index.ts
app/components/base/notifications/notification-container.component.ts
app/components/base/notifications/notification-container.html
app/components/base/notifications/notification-manager.ts
app/components/base/notifications/notification.component.ts
app/components/base/notifications/notification.html
app/components/base/notifications/notification.module.ts
app/components/base/notifications/notification.ts
app/components/base/quick-list/quick-list-item.component.ts
app/components/base/quick-list/quick-list.component.ts
app/components/base/table/table-row.component.ts
app/components/base/table/table.component.ts
app/components/job/action/add/job-create-basic-dialog.component.ts
app/components/pool/action/add/pool-create-basic-dialog.component.ts
app/components/pool/action/add/pool-create-basic-dialog.html
app/components/task/action/add/task-create-basic-dialog.component.ts
coding-guidelines.md
test/app/components/base/form/server-error/server-error.component.spec.ts
test/app/components/base/notifications/notification.spec.ts
test/app/components/component-test-helper.ts
test/app/components/job/action/add/job-create-basic-dialog.component.spec.ts
tslint.json

Added notifcation V1 fix #17 
* Publish a notifcation
* Autodismiss
* Dimiss Button

Notification V1

---

app/components/task/browse/task-list.component.ts

Delete multiple tasks

---

app/app.module.ts
app/assets/styles/main.scss
app/assets/styles/task/form.scss
app/components/task/action/add/index.ts
app/components/task/action/add/resourcefile-picker.component.ts
app/components/task/action/add/resourcefile-picker.html
app/components/task/action/add/task-create-basic-dialog.component.ts
app/components/task/action/add/task-create-basic-dialog.html
app/components/task/action/index.ts
app/models/forms/createTaskModel.ts
app/models/task.ts

Resource file create form

---

app/components/job/action/add/job-create-basic-dialog.component.ts
app/components/task/action/add/task-create-basic-dialog.component.ts

Fix notification for create job and create task

---

app/components/task/browse/preview/task-preview.component.ts
app/components/task/browse/preview/task-preview.html

Added tooltip for task preview

---

app/components/base/form/action-form/action-form.component.ts
app/components/base/form/action-form/action-form.html
app/components/base/form/create-form/create-form.component.ts
app/components/base/form/create-form/create-form.html
app/components/base/form/form-base.ts
app/components/pool/action/resize/pool-resize-dialog.component.ts
app/components/pool/action/resize/pool-resize-dialog.html
app/utils/index.ts
app/utils/object.ts
app/utils/validators/index.ts
app/utils/validators/number.ts
test/app/components/job/action/disable/disable-job-dialog.component.spec.ts
test/app/components/job/action/enable/enable-job-dialog.component.spec.ts
test/app/components/job/action/terminate/terminate-job-dialog.component.spec.ts

Pool resize use action-form and updated action-form&create-form to use same base class

---

app/components/base/form/form-error/form-error.component.ts
test/app/components/base/form/form-error/form-error.component.spec.ts

Bex error need input to be touched before showing

---

app/assets/styles/base/property-list.scss
app/assets/styles/theme/variables.scss
app/components/base/property-list/index.ts
app/components/base/property-list/property-group.component.ts
app/components/base/property-list/property-group.html
app/components/base/property-list/property-list.component.ts
app/components/base/property-list/property-list.module.ts
app/components/job/details/job-details.html
app/components/job/details/job-properties.html
app/components/node/details/node-details.html
app/components/pool/details/pool-details.html
app/components/pool/details/pool-properties.html
app/components/task/details/task-details.html

Property group collapse ability

---

app/app.component.ts
app/services/command-service.ts
app/services/settings-service.ts
config/webpack.config.base.js
config/webpack.config.dev.js
config/webpack.config.prod.js
package.json
test/app/components/base/property-list/property-group.component.spec.ts
test/app/components/base/property-list/text-property.component.spec.ts
test/utils/helpers/template-interaction.ts
test/utils/matchers/index.d.ts
test/utils/matchers/misc-matchers.ts
tsconfig.json
tslint.json
webpack.config.js

spec(property-list)

---

app/app.layout.html
app/assets/styles/base/forms.scss
app/assets/styles/main.scss
app/assets/styles/pool/create.scss
app/components/base/sidebar/sidebar-page.ts
app/components/job/action/add/job-create-basic-dialog.html
app/components/pool/action/add/pool-create-basic-dialog.html
app/components/pool/action/add/pool-os-picker.html
app/polyfills.browser.ts
app/utils/extensions/index.ts
client/main.ts
package.json
test/app/components/base/sidebar/sidebar-page.spec.ts

* Angular 2.3.0 -> 2.4.1
* Material 2.0.0.alpha.11 -> 2.0.0.beta.1

Update angular2 and material

---

config/webpack.config.base.js
config/webpack.config.dev.js
package.json

Upgrade to webpack 2.2 fix the webpack error in the console

---

app/assets/styles/base/banner.scss
app/assets/styles/pool/base.scss
app/components/base/banner/banner.component.ts
app/components/base/banner/banner.html
app/components/base/base.module.ts
app/components/pool/graphs/pool-graphs.component.ts
app/components/pool/graphs/pool-graphs.html
app/services/core/rx-list-proxy.ts
app/services/file-service.ts
app/services/job-service.ts
app/services/node-service.ts
app/services/pool-service.ts
app/services/service-base.ts
app/services/task-service.ts
app/utils/array.ts
app/utils/index.ts
app/utils/observable.ts
test/app/components/base/banner/banner.spec.ts
test/app/services/core/rx-batch-list-proxy.spec.ts
test/app/utils/array.spec.ts
test/app/utils/observable.spec.ts

Start task detect error 

---

app/assets/styles/account/browse.scss
app/assets/styles/base/list.scss
app/assets/styles/base/loading.scss
app/components/account/browse/account-list.component.ts
app/components/account/browse/account-list.html
app/components/account/home/account-home.component.ts
app/components/account/home/account-home.html
app/components/base/loading/loading.component.ts
app/components/base/loading/loading.html
test/app/components/account/browse/account-list.component.spec.ts

Fix #124 
* Loading icon when loading accounts instead of showing "no accoutn for subscription"
* Subscription are searchable

Improve account list UX

---

app/components/task/details/task-details.html

input tabs on the left and output tabs on the right. renamed tab headings to make more sense.

re-order task details tabs. so input params and outputs are grouped from left to right. 

---

app/assets/styles/pool/heatmap.scss
app/components/pool/graphs/nodes-heatmap.component.ts
test/app/components/pool/graphs/nodes-heatmap.component.spec.ts

Heatmap selected node style

---

app/services/core/rx-entity-proxy.ts
app/services/core/rx-list-proxy.ts
app/services/core/rx-proxy-base.ts
app/services/file-service.ts
app/utils/extensions/array.ts
app/utils/extensions/index.ts
app/utils/object.ts
test/app/utils/extensions/array.spec.ts
test/app/utils/object.spec.ts
tsconfig.json

New setting for the proxy to ignore some error code from being logged(404 by default)

---

app/components/pool/graphs/nodes-heatmap.component.ts
app/components/pool/graphs/pool-graphs.component.ts
test/app/components/pool/graphs/nodes-heatmap.component.spec.ts
test/utils/helpers/template-interaction.ts

Heatmap switch between pools refresh nodes

---

app/app.ts
app/assets/styles/main.scss
app/assets/styles/task/base.scss
app/assets/styles/task/lifetime.scss
app/assets/styles/theme/variables.scss
app/components/base/elapsed-time/elapsed-time.component.ts
app/components/task/details/task-details.html
app/components/task/details/task-details.module.ts
app/components/task/details/task-lifetime/index.ts
app/components/task/details/task-lifetime/task-lifetime-state.component.ts
app/components/task/details/task-lifetime/task-lifetime-state.html
app/components/task/details/task-lifetime/task-lifetime.component.ts
app/components/task/details/task-lifetime/task-lifetime.html
app/services/adal/access-token.ts
app/utils/date-utils.ts
app/utils/extensions/index.ts
app/utils/index.ts
config/karma.shim.js
test/app/components/task/details/task-lifetime/task-lifetime-state.component.spec.ts
test/app/components/task/details/task-lifetime/task-lifetime.component.spec.ts
test/app/services/adal/access-token.spec.ts
test/app/spec-bundle.ts
test/app/utils/date-utils.spec.ts

Task timeline

---

app/assets/styles/main.scss
app/assets/styles/task/timeline.scss
app/components/base/elapsed-time/elapsed-time.component.ts
app/components/task/details/task-details.html
app/components/task/details/task-details.module.ts
app/components/task/details/task-error-display.component.ts
app/components/task/details/task-error-display.html
app/components/task/details/task-lifetime/index.ts
app/components/task/details/task-timeline/index.ts
app/components/task/details/task-timeline/task-timeline-state.component.ts
app/components/task/details/task-timeline/task-timeline-state.html
app/components/task/details/task-timeline/task-timeline.component.ts
app/components/task/details/task-timeline/task-timeline.html
app/models/task.ts
app/utils/constants.ts
app/utils/date-utils.ts
package.json
test/app/components/task/details/task-error-display.component.spec.ts
test/app/components/task/details/task-lifetime/task-timeline-state.component.spec.ts
test/app/components/task/details/task-lifetime/task-timeline.component.spec.ts
test/app/models/task.spec.ts

Task timeout and refactor lifetime-> timeline

---

.vscode/launch.json
app/assets/styles/base/advanced-filter.scss
app/assets/styles/base/table.scss
app/components/base/advanced-filter/advanced-filter.component.ts
app/components/base/advanced-filter/advanced-filter.module.ts
app/components/base/advanced-filter/index.ts
app/components/base/advanced-filter/list-filter-control.ts
app/components/base/advanced-filter/list-filter-control/list-filter-control.html
app/components/base/advanced-filter/list-filter-control/list-filter-control.ts
app/components/base/list-and-show-layout/list-and-show-layout.component.ts
app/components/base/table/table-row.component.ts
app/components/task/browse/filter/task-advanced-filter.component.ts
app/components/task/browse/filter/task-advanced-filter.html
app/components/task/home/task-home.component.ts
app/components/task/home/task-home.html
app/utils/extensions/string.ts
app/utils/filter-builder/property.ts
package.json
test/app/components/base/advanced-filter/list-filter-control.spec.ts

Task filter by exit code

---

app/components/task/browse/display/task-list-display.component.ts
app/utils/object.ts

Change task dates to use DateUtils.prettyDate

---

app/components/base/list-and-show-layout/entity-details-list.component.ts
app/components/base/list-and-show-layout/list-loading.component.ts
app/components/base/list-and-show-layout/list-loading.html
app/components/file/browse/display/file-list-display.html
app/components/file/browse/file-list.html
app/components/file/browse/node-file-browse.html
app/components/file/browse/node-file-list.component.ts
app/components/file/browse/task-file-list.component.ts
app/components/file/home/file-home.html
app/components/task/details/task-details.html
app/models/node.ts
app/services/node-service.ts
app/utils/extensions/observable.ts
test/app/utils/observable.spec.ts

Cleanup and fix no node while loading.
fix #170

Improve task file UX

---

app/services/azure-http.service.ts
app/utils/constants.ts
test/app/services/azure-http.service.spec.ts

Retry logic for azure http

---

app/services/core/query-cache.ts
app/services/core/rx-list-proxy.ts
test/app/services/core/query-cache.spec.ts
test/app/services/core/rx-batch-list-proxy.spec.ts

RxListProxy use set to remove duplicate keys

---

app/app.layout.html
app/assets/styles/base/layout.scss
app/components/pool/details/pool-details.component.ts
app/components/pool/details/pool-details.html

Tooltips for back/forward buttons and node status on the pool summary

---

app/components/base/loading/loading.component.ts
app/components/job/browse/job-list.html
app/services/core/rx-list-proxy.ts

Fix loading icon staying when switching back nav

---

app/app.component.ts
app/app.layout.html
app/components/account/browse/account-dropdown.component.ts
app/components/account/browse/account-dropdown.html
app/services/account-service.ts

Tentative to fix the change detection not triggering after login and showing blank page

---

app/assets/styles/base/property-list.scss

Make properties more compact

---

app/components/node/details/node-details.html
app/components/node/details/node-properties.component.ts
app/components/node/details/node-properties.html

Node external ip

---

app/components/base/context-menu/context-menu.model.ts
app/components/pool/graphs/nodes-heatmap-legend.component.ts
app/components/pool/graphs/nodes-heatmap-legend.html
app/components/pool/graphs/nodes-heatmap.html
test/app/components/pool/graphs/nodes-heatmap-legend.component.spec.ts
test/utils/helpers/template-interaction.ts
test/utils/mocks/context-menu.service.mock.ts
test/utils/mocks/index.ts

Reboot and Reimage all nodes by state or category

---

app/components/application/action/delete/delete-application-action.ts
app/components/application/action/delete/delete-application-dialog.component.ts
app/components/application/action/delete/delete-package-action.ts
app/components/application/action/upload/upload-package-task.ts
app/components/application/browse/application-list.component.ts
app/components/application/details/application-package-table.component.ts
app/components/base/background-task/background-task-tracker.component.ts
app/components/base/background-task/background-task.model.ts
app/components/base/background-task/background-task.module.ts
app/components/base/background-task/background-task.service.ts
app/components/base/background-task/index.ts
app/components/job/action/delete/delete-job-action.ts
app/components/job/action/delete/delete-job-dialog.component.ts
app/components/job/browse/job-list.component.ts
app/components/pool/action/delete/delete-pool-dialog.component.ts
app/components/pool/action/delete/delete-pool-task.ts
app/components/pool/browse/pool-list.component.ts
app/components/task/action/delete/delete-task-action.ts
app/components/task/action/delete/delete-task-dialog.component.ts
app/components/task/browse/task-list.component.ts
app/services/core/long-running-action.ts
app/services/node-service.ts
test/app/components/base/background-task/background-task-manager.spec.ts
test/app/components/base/background-task/background-task-tracker.spec.ts
test/utils/mocks/index.ts
test/utils/mocks/notification.service.mock.ts

Handle errors in background task service

---

app/app.component.ts
app/components/pool/action/add/pool-os-picker.component.ts
app/models/index.ts
app/models/node-agent-sku-map.ts
app/models/node-agent-sku.ts

fix pool clone crash

---

app/app.component.ts
app/components/base/base.module.ts
app/components/base/editor/editor-languages.ts
app/components/base/editor/editor.component.ts
app/components/base/editor/editor.module.ts
app/components/base/editor/index.ts
app/components/pool/action/add/pool-create-basic-dialog.html
app/models/node-agent-sku-map.ts
app/services/pool-service.ts
client/api/batch-client-proxy/poolProxy.ts
package.json

Integrate ace editor as a angular2 component

---

app/components/account/browse/account-list.component.ts
app/components/job/action/disable/disable-job-dialog.component.ts
app/components/pool/graphs/nodes-heatmap.component.ts
app/components/task/details/task-error-display.component.ts
test/app/components/account/browse/account-list.component.spec.ts
test/app/components/base/banner/banner.spec.ts
test/app/components/file/browse/node-file-list.component.spec.ts
test/app/components/job/action/add/job-create-basic-dialog.component.spec.ts
test/app/components/job/action/disable/disable-job-dialog.component.spec.ts
test/app/components/job/action/enable/enable-job-dialog.component.spec.ts
test/app/components/job/action/terminate/terminate-job-dialog.component.spec.ts
test/app/components/job/details/error-display/job-error-display.component.spec.ts
test/app/components/node/connect/download-rdp.component.spec.ts
test/app/components/pool/details/pool-error-display.component.spec.ts
test/app/components/pool/graphs/nodes-heatmap-legend.component.spec.ts
test/app/components/pool/graphs/nodes-heatmap.component.spec.ts
test/app/components/pool/graphs/state-counter.spec.ts
test/app/components/task/details/task-dependencies.component.spec.ts
test/app/components/task/details/task-error-display.component.spec.ts
test/app/components/task/details/task-lifetime/task-timeline-state.component.spec.ts
test/app/components/task/details/task-lifetime/task-timeline.component.spec.ts
test/utils/mocks/components/index.ts
test/utils/mocks/components/info-box.component.mock.ts

remove module injection for performance improvement

remove modules refactor

---

app/app.module.ts
app/assets/styles/pool/heatmap.scss
app/components/pool/details/pool-details.html
app/components/pool/graphs/nodes-heatmap.component.ts
app/components/pool/graphs/nodes-heatmap.html
app/components/pool/graphs/pool-graphs.component.ts
app/components/pool/graphs/pool-graphs.html
app/models/index.ts
app/models/node-recent-task.ts
app/models/node.ts
app/models/pool.ts
test/app/components/pool/graphs/nodes-heatmap.component.spec.ts

Heatmap show running tasks status

---

app/assets/styles/base/banner.scss
app/components/base/banner/banner.component.ts
app/components/task/details/task-error-display.html

Fix banner style and reset buttons when switching 

---

app/assets/styles/base/layout.scss
app/assets/styles/file/log.scss
app/assets/styles/pool/base.scss
app/components/application/details/application-details.html
app/components/file/browse/task-file-list.component.ts
app/components/file/details/file-content.component.ts
app/components/job/details/job-details.html
app/components/node/details/node-details.html
app/components/pool/details/pool-details.html
app/components/task/details/task-details.html

fixed up the padding in tabs to make them consistent.

fix up tab padding, css. 

---

app/app.component.ts
app/assets/styles/account/browse.scss
app/components/account/browse/account-list.component.ts
app/components/account/browse/account-list.html
app/components/account/home/account-home.component.ts
app/components/account/home/account-home.html
app/components/base/list-and-show-layout/list-and-show-layout.component.ts
app/components/base/list-and-show-layout/list-and-show-layout.html
app/services/account.service.ts
test/app/components/account/browse/account-list.component.spec.ts

Load all the accounts on start and changed the account list experience

---

app/app.component.ts
app/app.module.ts
app/assets/styles/base/forms.scss
app/assets/styles/pool/create.scss
app/components/pool/action/add/pool-create-basic-dialog.component.ts
app/components/pool/action/add/pool-create-basic-dialog.html
app/components/pool/action/add/pool-os-picker.component.ts
app/components/pool/action/add/pool-os-picker.html
app/models/index.ts
app/models/vm-size.ts
app/services/azure-http.service.ts
app/services/index.ts
app/services/vm-size.service.ts
app/utils/constants.ts
app/utils/index.ts
app/utils/string-utils.ts
test/app/utils/string-utils.spec.ts

VMSizes loaded from the server

---

app/services/adal/user-authorization.ts
app/services/electron/remote.service.ts
client/authentication/authentication-window.ts
client/authentication/index.ts
client/core/global.ts
client/core/index.ts
client/core/unique-window.ts
client/main-window/index.ts
client/main-window/main-window.ts
client/main.ts
client/splash-screen/splash-screen.ts
config/webpack.config.dev.js
test/app/services/adal/user-authorization.spec.ts
test/utils/mocks/services/electron-remote.service.mock.ts

Make AAD auth window unique and cleanup of main window

---

CHANGELOG.md
Readme.md
package.json

Merge on Monday 3rd of April and sync stable branch

Getting ready for version 0.2.0

---

app/assets/styles/base/table.scss
app/components/application/details/application-package-table.html
app/components/base/abstract-list/abstract-list-base.ts
app/components/base/quick-list/quick-list.component.ts
app/components/base/table/index.ts
app/components/base/table/table-cell.component.ts
app/components/base/table/table-cell.html
app/components/base/table/table-column.component.ts
app/components/base/table/table-row.component.ts
app/components/base/table/table.component.ts
app/components/base/table/table.html
app/components/base/table/table.module.ts
app/components/pool/action/add/vm-size-picker.component.ts
app/components/pool/action/add/vm-size-picker.html
test/app/components/base/table/table-cell.component.spec.ts
test/app/components/base/table/table.component.spec.ts
test/app/components/pool/action/add/vm-size-picker.spec.ts

Added sorting to bl-table

---

app/services/core/rx-list-proxy.ts

Fix max results bug with query cache

---

app/services/core/index.ts
app/services/core/list-options.ts
app/services/core/proxy-options.ts
app/services/core/rx-list-proxy.ts
app/services/core/rx-proxy-base.ts
test/app/services/core/proxy-options.spec.ts

Fix pool details freeze after a minute

---

app/components/base/form/form-page/form-page.component.ts
app/components/base/form/form-picker/form-picker.component.ts
app/components/base/tags/tags.component.ts
app/components/pool/action/scale/autoscale-formula-picker.component.ts
app/components/pool/action/scale/pool-scale-picker.component.ts
config/webpack.config.base.js
config/webpack.config.dev.js
config/webpack.config.prod.js
config/webpack.config.test.js
docs/components.md

Internal: Moved from styleUrls to regular import

---

app/components/pool/action/resize/pool-resize-dialog.component.ts
app/components/pool/action/resize/pool-resize-dialog.html
app/components/pool/action/scale/pool-scale-picker.component.ts
app/components/pool/action/scale/pool-scale-picker.html
app/components/pool/details/pool-details.component.ts
app/components/pool/details/pool-details.html
app/models/decorators/pool-decorator.ts
app/models/dtos/index.ts
app/models/dtos/pool-enable-autoscale.dto.ts
app/services/pool-service.ts
client/api/batch-client-proxy/poolProxy.ts

Feature: Pool rescale supports autoscale

---

app/models/forms/create-pool-model.ts

Fix pool autoscale interval null when cloning pool

---

app/components/application/action/activate/activate-package-dialog.html
app/components/application/action/delete/delete-application-dialog.html
app/components/application/action/edit/application-edit-dialog.component.ts
app/components/application/action/edit/application-edit-dialog.html
app/components/base/form/complex-form/complex-form.component.ts
app/components/base/form/complex-form/complex-form.html
app/components/base/form/form-page/form-page.scss
app/components/base/form/simple-form/simple-form.html
app/components/job/action/delete/delete-job-dialog.html
app/components/job/action/disable/disable-job-dialog.html
app/components/job/action/enable/enable-job-dialog.html
app/components/job/action/terminate/terminate-job-dialog.html
app/components/pool/action/delete/delete-pool-dialog.html
app/components/pool/action/resize/pool-resize-dialog.html
app/components/task/action/delete/delete-task-dialog.html
app/components/task/action/terminate/terminate-task-dialog.html
app/styles/base/forms.scss
app/styles/pool/create.scss
test/app/components/application/action/edit/application-edit-dialog.component.spec.ts

fix #344
A couple of forms were missed in the form refactor to bl-complex-form. Added back in the actionColor and actionName properties that were missed off when simple form implemented a complex form.
Also a couple of CSS tweaks to add some spacing between buttons.

fix edit applcation forms layout

---

CHANGELOG.md
package.json

Prepare for v0.3.1

---

app/app.module.ts
app/components/base/tabs/tab-group.component.ts
app/components/base/tabs/tab-group.html
app/error-handler.ts

Fix: crash when going back to pool from node with breadcrumb

---

app/components/base/property-list/property-list.component.ts
app/components/base/property-list/property-list.scss
app/styles/main.scss

UI: Change icon for enabled/disabled properties

---

app/components/job/details/job-details.html

Moved task tab first in the job details

---

app/services/core/data-cache.ts
app/services/core/rx-entity-proxy.ts
test/app/services/core/rx-batch-entity-proxy.spec.ts

Feature: Display entities immediately if already present in the cache

---

app/components/base/form/key-value-picker/key-value-picker.component.ts
app/components/task/base/resourcefile-picker.component.ts
app/components/task/base/resourcefile-picker.html
test/app/components/task/base/resourcefile-picker.component.spec.ts

Fix pool create crash and add Resource file picker specs

---

Readme.md

Added a description of Batch labs in Readme

---

app/components/pool/action/add/pool-create-basic-dialog.component.ts
app/components/pool/action/add/pool-create-basic-dialog.html
app/components/pool/details/pool-configuration.html
app/models/dtos/pool-create.dto.ts
app/models/forms/create-pool-model.ts
app/models/pool.ts
app/models/task-scheduling-policy.ts
app/styles/base/forms.scss
app/styles/partials/grid.scss
app/styles/pool/create.scss

Added maxTasksPerNode, enableMpi and taskSchedulingPolicy to create pool 

---

app/components/base/form/complex-form/complex-form.html
app/components/pool/action/scale/pool-scale-picker.html

Fix: Disable on enter submit as it conflict with dropdown selection

---

app/components/base/property-list/property-list.scss
app/styles/pool/base.scss

Fix: Nested scrolling bar in configuration tabs

---

app/components/account/browse/account-fav-list.html
app/components/account/browse/account-list.html
app/components/account/details/account-details.html
app/components/application/browse/application-list.html
app/components/base/abstract-list/abstract-list-base.ts
app/components/base/abstract-list/abstract-list-item-base.ts
app/components/base/focus-section/focus-section.component.ts
app/components/base/quick-list/quick-list-item.component.ts
app/components/base/table/table-row.component.ts
app/components/file/browse/display/file-list-display.html
app/components/job/browse/job-list.html
app/components/node/browse/display/node-list-display.html
app/components/pool/browse/pool-list.html
app/components/task/browse/display/task-list-display.html
app/components/task/details/task-dependencies.html
test/app/components/base/quick-list/quick-list.component.spec.ts

Fix: List item now focus on click 

---

CHANGELOG.md
app/utils/date-utils.ts
package.json
test/app/utils/date-utils.spec.ts

Update changelog and version in package.json

---

app/components/base/focus-section/focus-section.component.ts
package.json
test/app/components/account/base/storage-account-picker/storage-account-picker.component.spec.ts
test/app/components/application/errors/application-error-display.component.spec.ts
test/app/components/base/quick-list/quick-list.component.spec.ts
test/app/memory-leak/mem-leak.spec.ts
tslint.json
yarn.lock

Seems like tslint broke the no fdescribe jasmine rule updated to use the banned word rule.

Fix: Remove fdescribe, fix specs and fix tslint

---

app/services/core/rx-entity-proxy.ts

Fix: Wait for the fetch to complete before returning an item

---

app/components/pool/graphs/nodes-heatmap.component.ts
app/components/pool/graphs/pool-graphs.component.ts

Fix: 	Only reset graphs if the pool id changes

---

app/models/pool-os-disk.ts
app/models/virtual-machine-configuration.ts
app/utils/pool-utils.ts

Fix custom image pool making list crash

---

app/components/shared/main-navigation.html
app/styles/partials/navigation.scss
app/styles/variables.scss

UI tweak: Make navigation bar thiner and define focus style

---

app/components/base/property-list/property-group.component.ts
app/components/base/property-list/property-group.html
app/components/pool/start-task/start-task-picker.html
app/components/pool/start-task/start-task-properties.html

Fix: start-task tab padding

---

app/components/pool/start-task/start-task-edit-form.component.ts

Start task form not reseting every time the pool is updated

---

app/components/file/details/code-file-viewer/code-file-viewer.component.ts
app/components/file/details/code-file-viewer/code-file-viewer.html
app/components/file/details/file-details.module.ts
app/components/file/details/file-too-large/file-too-large.component.ts
app/components/file/details/file-too-large/file-too-large.html
app/components/file/details/file-too-large/file-too-large.scss
app/components/file/details/file-too-large/index.ts
app/components/file/details/log-file-viewer/log-file-viewer.component.ts
app/components/file/details/log-file-viewer/log-file-viewer.html
app/services/electron/remote.service.ts

Fix: Don't show large files in batch labs but propose to open in external editor.

---

app/components/node/details/error/start-task-error-display.component.ts
app/components/node/details/error/start-task-error-display.html
app/components/node/details/index.ts
app/components/node/details/node-details.html
app/components/node/node.module.ts
app/components/pool/start-task/start-task-properties.html
app/models/decorators/failure-info-decorator.ts
app/models/decorators/start-task-info-decorator.ts
app/models/failure-info.ts
app/models/start-task-info.ts

add start task failure info banner to node

---

app/utils/pool-utils.ts
test/app/utils/pool-utils.spec.ts

Fix #481 
Hope this covers all cases now. 
Edit: Has broken the RDP UX with: 
_./app/components/node/connect/node-connect.component.ts:61:17
TS2322: Type 'boolean | RegExpMatchArray' is not assignable to type 'boolean'.
Type 'RegExpMatchArray' is not assignable to type 'boolean'._
I will fix it in the morning.

Test for windows offer types that are differnt format to existing

---

CHANGELOG.md
package.json

Prepare release 0.5.0

---

app/components/base/form/editable-table/editable-table.component.ts
app/components/task/base/resourcefile-picker.component.ts
app/models/user-account.ts
test/app/components/base/form/editable-table/editable-table.component.spec.ts

Fix: Task resource file edit broken and user identity not allowing admin

---

app/components/base/banner/banner.scss
app/components/base/form/editable-table/editable-table.component.ts
app/components/pool/details/error-display/pool-error-display.component.ts
app/models/user-account.ts
test/app/components/base/form/editable-table/editable-table.component.spec.ts

Fix bugs for release 0.5.1

---

app/components/base/buttons/button.component.ts
app/components/base/buttons/button.scss
app/components/base/form/edit-metadata-form/edit-metadata-form.component.ts
app/components/base/form/edit-metadata-form/edit-metadata-form.html
app/components/base/form/edit-metadata-form/index.ts
app/components/base/form/form.module.ts
app/components/base/property-list/property-group.component.ts
app/components/base/property-list/property-group.html
app/components/base/property-list/property-list.scss
app/components/job/details/job-configuration.component.ts
app/components/job/details/job-configuration.html
app/components/pool/details/pool-configuration.component.ts
app/components/pool/details/pool-configuration.html
app/components/pool/start-task/start-task-edit-form.component.ts
app/models/dtos/index.ts
app/models/dtos/job-patch.dto.ts
app/models/dtos/pool-patch.dto.ts
app/models/metadata.ts
app/services/job-service.ts
app/services/pool-service.ts
app/utils/model-utils.ts
test/app/components/application/details/application-properties.component.spec.ts
test/app/components/base/form/complex-form/complex-form.spec.ts
test/app/components/base/property-list/property-group.component.spec.ts

Feature: Allow editing metadata for job and pool

---

app/components/file/details/file-details.component.ts
app/components/file/details/file-details.html
app/components/file/details/log-file-viewer/log-file-viewer.component.ts

Action: Open file in external program

---

app/components/base/list-and-show-layout/delete-selected-items-dialog.component.ts
app/components/base/list-and-show-layout/delete-selected-items.html

Update the delete items dialog to use the new simple form

---

app/services/file/file-loader.ts
app/services/storage.service.ts

Fix blob storage download of binary files

---

app/components/base/buttons/button.component.ts
app/components/file/details/file-details.component.ts
app/components/file/details/file-too-large/file-too-large.component.ts
app/services/file/file-loader.ts

Fix opening file on osx & caching blob files:

---

app/services/core/data-cache.ts
app/services/core/rx-list-proxy.ts
test/app/services/core/rx-batch-list-proxy.spec.ts

Fix: delete multiple pool

---

Readme.md

Fix: Updated readme to explain python requirements

---

app/components/pool/action/delete/delete-pool-dialog.component.ts
app/components/pool/action/delete/delete-pool-dialog.html

Feature: Delete job with pool if same id

---

app/components/pool/graphs/nodes-heatmap.component.ts
app/components/pool/graphs/nodes-heatmap.html
app/components/pool/graphs/nodes-heatmap.scss
app/components/pool/graphs/pool-graphs.component.ts
app/components/pool/graphs/pool-graphs.scss
test/app/components/pool/graphs/nodes-heatmap.component.spec.ts

Fix: few heatmap tweaks

---

app/components/pool/details/pool-configuration.component.ts
app/components/pool/details/pool-configuration.html

am sure it can be done better, but this at least allows the UI to work.

quick fix to get pools working

---

app/app.component.ts
app/services/python-rpc/python-rpc.service.ts
docs/call-python.md
pylintrc
python/controllers/test_controller.py
python/jsonrpc/request.py
python/jsonrpc/response.py
python/server/__init__.py
python/server/app.py
python/server/response_stream.py
python/server/websocket_server.py

Feature: Ability to stream python

---

app/components/pool/action/add/pool-os-picker.component.ts
app/models/forms/create-pool-model.ts

PaaS pool create issue

---

app/components/pool/action/add/app-license-picker.component.ts
app/components/pool/action/add/app-license-picker.html
app/components/pool/action/add/license-eula-dialog.component.ts
app/components/pool/action/add/license-eula-dialog.html
test/app/components/pool/action/add/app-license-picker.component.spec.ts

add vray to the license picker

---

app/app.component.ts
app/services/python-rpc/python-rpc.service.ts
app/utils/logger/logger.ts
python/setup.py

Batchlabs will try to reconnect to the python server automatically if the connection is killed

Feature: reconnect to websocket automatically

---

app/components/node/connect/download-rdp.component.ts
app/components/node/connect/node-user-credentials-form.component.ts
app/components/node/connect/node-user-credentials-form.html
test/app/components/node/connect/download-rdp.component.spec.ts
test/app/components/node/connect/node-user-credentials-form.component.spec.ts

Fix: adding user to node as admin

---

app/components/pool/base/pool-nodes-preview.component.ts
app/components/pool/base/pool-nodes-preview.html
app/models/decorators/pool-decorator.ts
app/utils/pool-utils.ts
test/app/components/pool/base/pool-nodes-preview.component.spec.ts
test/app/utils/pool-utils.spec.ts

Fix: display the status of a pool node after deleting a node

---

app/components/task/details/task-configuration.html
app/models/index.ts
app/models/task-output-file.ts
app/models/task.ts

Feature: Show task output configuration

---

app/components/base/background-task/background-task-tracker.component.ts
app/components/base/background-task/background-task-tracker.html
app/components/base/background-task/background-task-tracker.scss
app/components/base/buttons/buttons.component.ts
app/components/base/buttons/directory-picker.component.ts
app/components/base/form/complex-form/complex-form.html
app/components/base/form/simple-form/simple-form.html
app/components/data/action/add/file-group-create-form.component.ts
app/components/data/action/add/file-group-create-form.html
app/components/data/data.module.ts
app/components/data/details/data-details.component.ts
app/components/data/details/data-details.html
app/components/data/details/download-file-group-dialog/download-file-group-dialog.component.ts
app/components/data/details/download-file-group-dialog/download-file-group-dialog.html
app/components/data/details/download-file-group-dialog/download-file-group-dialog.scss
app/components/data/details/download-file-group-dialog/index.ts
app/components/data/details/index.ts
app/styles/base/forms.scss
app/styles/base/scaffolding.scss
app/styles/main.scss

Feature: download file group

---

app/components/pool/action/add/pool-create-basic-dialog.component.ts
app/components/pool/action/add/pool-create-basic-dialog.html
app/components/pool/action/add/vm-size-picker.component.ts
app/components/pool/action/add/vm-size-picker.html
app/components/pool/details/pool-details.component.ts
app/components/pool/details/pool-details.html
app/components/pool/details/pool-details.scss
app/services/pricing.service.ts
app/utils/constants.ts
app/utils/index.ts
app/utils/number-utils.ts
app/utils/pool-utils.ts
test/app/utils/number-utils.spec.ts
test/app/utils/pool-utils.spec.ts

fix #595 
Also changed to display price per hour instead of per month

Feature: Display estimated pool pricing

---

app/components/pool/graphs/nodes-heatmap.component.ts

Fix reboot and reimage notification being inverted

---

app/services/account.service.ts

Fix account not having permission to listKeys

---

.vscode/launch.json
app/components/task/action/add/task-create-basic-dialog.component.ts
app/components/task/action/add/task-create-basic-dialog.html
app/components/task/details/task-configuration.html
app/models/decorators/task-decorator.ts
app/models/dtos/task-create.dto.ts
app/models/forms/create-task-model.ts
app/models/task.ts

Feature: Task user identity

---

.vscode/launch.json
src/client/core/batchlabs-application.ts
src/client/core/global.ts
src/client/core/index.ts
src/client/core/unique-window.ts
src/client/logger/logger-proxy.ts
src/client/logger/pretty-stream.ts
src/client/main-window/main-window.ts
src/client/main.ts
src/client/python-process/python-executable.ts

Should fix #633 
This also include some logging improvement for development: 
* Will print the log nicely in the console instead of being buyan json format(Only like that in the file)
* Made the python discovery error better by not showing errors unless no valid version is found

Fix: Ghost process left after quitting batch labs prod. Also improve logging for dev

---

app/app.ts
app/components/base/charts/chart.directive.ts
app/core/record/arm-record.ts
app/core/record/decorators.ts
app/core/record/helpers.ts
app/core/record/record.ts
src/client/core/batchlabs-application.ts
src/client/main.ts
tsconfig.json
tslint.json

Switch to es6 target

---

app/app.ts

Added reload shortcut at all time

---

app/components/task/browse/display/task-list-display.html

fix task id column not truncating

---

app/components/task/details/output/task-outputs.component.ts
app/models/server-error.ts
app/services/file-service.ts
app/services/storage-client.service.ts

Improve errors when loading task outputs

---

app/components/base/dialogs/dialog.service.ts
app/components/base/dialogs/dialogs.module.ts
app/components/base/dialogs/index.ts
app/components/base/dialogs/prompt/index.ts
app/components/base/dialogs/prompt/prompt-dialog.component.ts
app/components/base/dialogs/prompt/prompt-dialog.html
app/components/pool/action/resize/pool-resize-dialog.component.ts
app/components/pool/action/scale/autoscale-formula-picker.component.ts
app/components/pool/action/scale/autoscale-formula-picker.html
app/components/pool/action/scale/autoscale-formula-picker.scss
app/components/pool/action/scale/pool-scale-picker.component.ts
app/components/pool/details/pool-details.component.ts
app/styles/main.scss
app/styles/partials/heading.scss

Fix update autoscale formula and style

---

app/components/file/browse/file-explorer/file-table-view/file-table-view.scss
app/components/file/browse/file-explorer/file-tree-view/file-tree-view.scss
app/components/file/details/file-details-view/file-details-view.scss

Fix file tree overflow

---

app/components/base/form/expanding-textarea/expanding-textarea.component.ts
app/components/base/form/expanding-textarea/expanding-textarea.html
app/components/base/form/expanding-textarea/expanding-textarea.scss
app/components/base/form/expanding-textarea/index.ts
app/components/base/form/form.module.ts
app/components/base/form/single-line-textarea/index.ts
app/components/base/form/single-line-textarea/single-line-textarea.directive.ts
app/components/base/form/single-line-textarea/single-line-textarea.scss
app/components/pool/start-task/start-task-picker.html
app/components/task/action/add/task-create-basic-dialog.component.ts
app/components/task/action/add/task-create-basic-dialog.html

Feature: better command line for tasks and start task

---

src/client/core/index.ts
src/client/core/smart-card-certificate.ts
src/client/main.ts

fix #271 
You can now use the pin or smart card button when login

Feature: smart card support for windows when signing in

---

.editorconfig
.travis.yml
app/services/python-rpc/python-rpc.service.ts
app/utils/constants.ts
python/main.py
python/setup.py
src/client/client-constants.ts
src/client/core/batchlabs-application.ts
src/client/main-window/main-window.ts
src/client/main.ts
src/client/python-process/python-rpc-server-process.ts

Internal: find an available port to connect the python rpc server

---

ThirdPartyNotices.txt
app/components/shared/main-navigation.component.ts
electron-builder.yml
scripts/lca/generate-third-party.ts
src/client/client-constants.ts

Feature: Open ThirdPartyNotices.txt from batchlabs UI

---

app/components/job/graphs/job-graphs-home/job-graphs-home.scss
app/components/job/graphs/tasks-running-time-graph/tasks-running-time-graph.scss

Fix job graph overflowing vertically

---

app/services/file/file-navigator/file-navigator.ts
app/services/file/file-navigator/file-tree.model.ts

Fix: Browsing file group using absolute path

---

app/components/base/table/table.scss
app/components/file/details/file-details-view/file-details-view.component.ts
app/components/job/job-hook-task/job-hook-task-browser/job-hook-task-browser.scss
app/components/job/job-hook-task/job-hook-task-details/job-hook-task-details.html
app/components/job/job-hook-task/job-hook-task-details/job-hook-task-details.scss
app/services/file/file-loader.ts
app/services/file/file-navigator/file-navigator.ts
app/services/storage.service.ts
app/utils/cloud-path-utils.ts

Fix job prep and release task overflowing style issues

---

app/components/pool/graphs/nodes-heatmap.component.ts

Fix heatmap running task behaving on resize

---

app/components/base/editor/editor.scss
app/components/base/loading/loading.html
app/components/base/split-pane/split-pane.component.ts
app/components/base/split-pane/split-pane.html
app/components/data/details/data-details.html
app/components/file/browse/file-explorer/file-explorer.component.ts
app/components/file/browse/file-explorer/file-explorer.scss
app/components/file/browse/file-explorer/file-table-view/file-table-view.html
app/components/file/browse/file-explorer/file-table-view/file-table-view.scss
app/components/file/browse/file-explorer/file-tree-view/file-tree-view.scss
app/components/file/details/code-file-viewer/code-file-viewer.scss
app/components/file/details/file-details-view/file-details-view.scss
app/components/file/details/image-file-viewer/image-file-viewer.scss
app/components/file/details/log-file-viewer/log-file-viewer.html
app/components/file/details/log-file-viewer/log-file-viewer.scss
app/components/job/details/job-details.html
app/components/job/job-hook-task/job-hook-task-browser/job-hook-task-browser.scss
app/components/node/details/node-details.html
app/components/task/details/task-details.html
app/styles/base/layout.scss
app/styles/vendor/material-theme.scss

UI Feature: Use full height for details and scroll in file content

---

app/components/base/base.module.ts
app/components/base/virtual-scroll/index.ts
app/components/base/virtual-scroll/virtual-scroll.component.ts
app/components/base/virtual-scroll/virtual-scroll.html
app/components/base/virtual-scroll/virtual-scroll.module.ts
app/components/base/virtual-scroll/virtual-scroll.scss
app/components/file/browse/file-explorer/file-explorer.component.ts
app/components/file/browse/file-explorer/file-explorer.html
app/components/file/details/file-content.component.ts
app/components/file/details/file-content.html
app/components/file/details/file-details-view/file-details-view.component.ts
app/components/file/details/file-details-view/file-details-view.html
app/components/file/details/log-file-viewer/log-file-viewer.component.ts
app/components/file/details/log-file-viewer/log-file-viewer.html
app/components/file/details/log-file-viewer/log-file-viewer.scss
app/components/task/details/output/task-outputs.component.ts
app/components/task/details/output/task-outputs.html
app/services/file-service.ts
app/styles/base/layout.scss
app/styles/base/scaffolding.scss
package.json
scripts/travis/build-and-test.sh
yarn.lock

Feature: virtual scroll component and use with log file viewer

---

app/components/application/details/application-details.component.ts
app/components/application/details/application-package-table.component.ts
app/components/base/sidebar/sidebar-manager.ts
app/components/base/sidebar/sidebar-ref.ts
app/components/data/browse/file-group-list.component.ts
app/components/data/details/data-details.component.ts
app/components/job/base/job-stats-preview/job-stats-preview.component.ts
app/components/job/base/job-stats-preview/job-stats-preview.html
app/components/job/details/job-progress-status/job-progress-status.html
test/app/components/base/sidebar/sidebar.spec.ts

Rename completition to completion

---

app/components/account/details/account-details.html
app/components/application/details/application-details.html
app/styles/vendor/material-theme.scss

show subscription name on account details

---

app/components/pool/graphs/nodes-heatmap.component.ts

Feature: Heatmap running task fill

---

app/components/base/abstract-list/abstract-list-base.ts
app/components/base/list-and-show-layout/list-and-show-layout.component.ts
app/components/base/selectable-list/list-or-table-base.ts
app/components/base/selectable-list/selectable-list.ts
app/components/job/browse/job-list.component.ts
app/components/job/browse/job-list.html
test/app/components/application/details/application-package-table.component.spec.ts

fix #745 
Problem in the list not cleaning up subscription and leaving closure behind

Fix: memory leak in list

---

app/components/base/tabs/tab-group.html

UI feat: Disable tabs animations

---

app/services/file/file-navigator/file-navigator.ts

Load all files with continuation token at the same level

---

app/utils/extensions/index.ts
app/utils/extensions/security.ts

Security: Disable eval

---

app/components/pool/action/add/pool-os-picker.html
app/components/pool/action/scale/pool-scale-picker.component.ts
app/components/pool/action/scale/pool-scale-picker.html
app/models/forms/create-pool-model.ts
src/client/api/batch-client-proxy/shared/proxy-utils.ts

Feature: Resize timeout in form

---

app/components/settings/default-settings.json
app/models/settings.ts
app/services/settings.service.ts
app/services/subscription.service.ts
app/utils/string-utils.ts

Feature: Added settings to ignore subscriptions

---

app/components/file/browse/file-explorer/file-tree-view/file-tree-view.scss
app/components/task/details/output/task-outputs.component.ts

change error message for persisted outputs

---

app/components/application/action/create/application-create-dialog.component.ts
app/services/storage.service.ts
app/utils/index.ts
app/utils/url-utils.ts
test/app/components/application/action/create/application-create-dialog.component.spec.ts
test/app/utils/url-utils.spec.ts

Remove application package upload code to use storage directly

---

app/components/data/shared/cloud-file-picker/cloud-file-picker.component.ts
app/components/data/shared/cloud-file-picker/cloud-file-picker.html
app/components/data/shared/file-group-picker/file-group-picker.component.ts
app/components/data/shared/file-group-picker/file-group-picker.html
app/components/data/shared/file-group-picker/file-group-picker.scss
test/app/components/market/submit/parameter-input.component.spec.ts

allow user to create file group from job template form

---

app/components/data/details/download-file-group-dialog/download-file-group-dialog.component.ts

Fix: download file group recursive

---

app/components/pool/graphs/pool-graphs.component.ts

Fix: pool start task failed quick fix not doing anything

---

app/components/pool/details/pool-configuration.html

Fix: Typo on pool configuration(Display name)

---

app/components/pool/action/add/pool-create-basic-dialog.component.ts
app/components/pool/action/scale/pool-scale-picker.component.ts

Fix: cannot create pool if not changing resize timeout

---

app/components/base/form/form-picker/form-picker.component.ts

Fix: form picker reseting form on cancel

---

app/components/market/application-action/choose-action.component.ts
app/components/market/application-action/choose-action.html
app/components/market/application-action/choose-action.scss
app/components/pool/action/add/license-eula-dialog.html
app/models/application.ts
app/services/ncj-template.service.ts

Opens the MD file in Chrome via GitHub. 
Only 3ds Max and ImageMagick have full readme files at the moment. Will work on the rest tomorrow.

Click link to show readme file from action chooser

---

app/components/application/details/application-package-table.component.ts
app/components/job/details/job-details.component.ts
app/components/pool/details/pool-details.component.ts
app/components/task/details/task-details.component.ts

CSS overlay not removed after delete

---

app/components/node/details/error/index.ts
app/components/node/details/error/node-error-display.component.ts
app/components/node/details/error/node-error-display.html
app/components/node/details/index.ts
app/components/node/details/node-details.html
app/components/node/node.module.ts
app/models/compute-node-error.ts
app/models/index.ts
app/models/node.ts

Feature: Display compute node errors if any

---

app/components/base/split-pane/split-pane.component.ts
app/components/base/split-pane/split-pane.scss
app/components/pool/action/resize/pool-resize-dialog.html
app/components/pool/action/scale/autoscale-formula-picker.component.ts
app/components/pool/action/scale/autoscale-formula-picker.html
app/components/pool/action/scale/autoscale-formula-picker.scss
app/components/pool/action/scale/pool-scale-picker.component.ts
app/components/pool/action/scale/pool-scale-picker.html
app/services/batch-api/poolProxy.ts
app/services/pool-service.ts
app/styles/partials/heading.scss

Feature: Evaluate autoscale formula

---

app/components/market/home/recent-template-list/recent-template-list.component.ts
app/components/market/home/recent-template-list/recent-template-list.html
app/components/market/home/recent-template-list/recent-template-list.scss
app/components/market/local-template-browser/local-template-browser.scss
app/components/market/submit-recent-template/submit-recent-template.scss
app/components/market/submit/market-application.model.ts
app/components/market/submit/submit-market-application.component.ts
app/components/market/submit/submit-ncj-template.component.ts
app/components/market/submit/submit-ncj-template.html
app/models/ncj-job-template.ts
app/services/ncj-template.service.ts
app/styles/base/breadcrumbs.scss

Add ability to export template parameters: 
Note: Dave would also like to show the associated CLI command for running the template which i will add in the submit template UI. That will be another PR.
Add padding to local templates heading:

export ncj recent template paramters

---

app/components/job/browse/job-list.component.ts
app/components/pool/action/scale/autoscale-formula-picker.scss
app/components/task/browse/display/task-list-display.component.ts

Fix: task list is blank after adding a new one

---

app/components/shared/main-navigation.component.ts

Feature: about page(with version), show logs and redirect to github issues 

---

app/components/node/details/node-details.html
app/components/pool/graphs/nodes-heatmap-legend.component.ts
app/components/pool/graphs/nodes-heatmap.component.ts
app/components/pool/graphs/nodes-heatmap.html
app/components/pool/graphs/pool-graphs.component.ts
app/components/pool/graphs/pool-graphs.html
test/app/components/pool/graphs/nodes-heatmap-legend.component.spec.ts

Disable re-image for IaaS pools

---

app/components/job/details/job-configuration.html
app/components/pool/details/pool-configuration.html
app/models/decorators/pool-decorator.ts

Fix:  Show user identity in start task and wrap long command lines

---

app/services/batch-api/fileProxy.ts
app/services/file-service.ts

Fix: reading/downloading binary files

---

app/components/base/buttons/buttons.component.ts

Add task on disabled job

---

CHANGELOG.md
ThirdPartyNotices.txt
package.json

Chore: Prepare for release 0.9.0

---

app/components/file/browse/node-file-browse.component.ts
app/components/file/browse/node-file-browse.html

Feature: Display message when node is unavailable to view files

---

src/client/core/batchlabs-application.ts

Update user agent to include os and if dev

---

app/models/image-reference.ts
app/models/pool-os-disk.ts
app/utils/pool-utils.ts

Fix custom image display

---

app/components/pool/graphs/pool-graphs.component.ts
app/services/core/data/list-view.ts

Fix: ListView fetchall issue when switching params too fast

---

CHANGELOG.md
ThirdPartyNotices.txt
docs/new-release.md
package.json
scripts/lca/generate-third-party.ts

Release 0.10.0

---

app/components/file/browse/node-file-browse.component.ts

Show node files when start task failed

---

app/models/cloud-service-configuration.ts
app/models/decorators/cloud-service-configuration-decorator.ts
app/utils/pool-utils.ts
test/app/utils/pool-utils.spec.ts

Fix: Show the correct OS when using cloud service

---

app/components/job/job-hook-task/job-hook-task-details/job-hook-task-details.component.ts
app/components/job/job-hook-task/job-hook-task-details/job-hook-task-details.html
app/components/job/job-hook-task/job-hook-task-details/job-hook-task-details.scss

Fix: crash when looking at job preparation/release tasks

---

CHANGELOG.md
package.json

Prepare for release 0.10.1

---

CHANGELOG.md
app/components/pool/action/add/vm-size-picker.html
app/services/monaco-loader.service.ts
package.json
test/app/components/pool/action/add/vm-size-picker.spec.ts

Hotfix: vm size picker broken

---

src/client/main.ts
yarn.lock

Fix: Add hide, minimize and hide others shortcuts on osx

---

app/components/account/details/account-quotas-card/account-quotas-card.component.ts
app/components/account/details/account-quotas-card/account-quotas-card.html
app/components/account/details/account-quotas-card/account-quotas-card.scss
app/services/vm-size.service.ts

Added pool usage, dedicated core usage and low-pri core usage.

---

.github/ISSUE_TEMPLATE.md
Readme.md
app/components/account/details/account-quotas-card/account-quotas-card.html
app/components/account/details/account-quotas-card/account-quotas-card.scss

* Updated readme to include more information
* Updated issue template
* Updated progress bar to touch the sides and be 1px thiner

Update readme and progress bar on quotas

---

app/components/account/account.module.ts
app/components/account/details/account-details.component.ts
app/components/account/details/account-details.html
app/components/account/details/index.ts
app/components/account/details/keys-dialog/batch-account-keys-dialog.component.ts
app/components/account/details/keys-dialog/batch-account-keys-dialog.html
app/components/account/details/keys-dialog/batch-account-keys-dialog.scss
app/components/account/details/keys-dialog/index.ts
scripts/publish/publish.ts

Show batch account shared keys

---

app/components/account/browse/account-list.component.ts
app/services/account.service.ts
src/common/constants.ts

Cache batch account list to improve loading time

---

src/client/core/aad/adal/aad.service.ts
src/client/core/batchlabs-application.ts
src/client/main-window/main-window.ts
src/client/main.ts
tsconfig.json

Feature: Stop asking the user to login everytime they start batchlabs

---

CHANGELOG.md
ThirdPartyNotices.txt
package.json
scripts/publish/github-api.ts
scripts/publish/publish.ts
yarn.lock

Prepare for release 0.12.0

---

CHANGELOG.md
app/services/adal/adal.service.spec.ts
app/services/adal/adal.service.ts
package.json

Fix subscriptions not loading

---

CHANGELOG.md
package.json

Hotfix Electron vulnerability 

---

app/services/navigator.service.ts
karma.conf.js

Fix: batchlabs link navigation with session display bug

---

CHANGELOG.md
package.json
src/client/core/aad/adal/user-decoder.ts
yarn.lock

fix #1044 (authentication)
fix #1042 (auto updater)

Hot fix: Authentication crash and auto updater

---

app/app.ts
src/client/main.ts
src/client/menu.ts

Feature: Application menu for all OS + ctrl+shift+N for new window

---

.gitattributes
.gitignore
app/app.ts
src/client/core/aad/adal/aad.service.spec.ts
src/client/core/aad/adal/aad.service.ts
src/client/core/aad/authentication/authentication.service.spec.ts
src/client/core/aad/authentication/authentication.service.ts
src/client/core/batchlabs-application.ts
src/client/core/batchlabs-initializer.ts
src/client/core/main-window-manager.ts
src/client/core/unique-window.ts
src/client/main-window/main-window.ts
src/client/splash-screen/splash-screen.ts

Only one of the window is shown at all time.
fix #1035 (splash behind main app)
fix #1043 (auth window behind main app)

Bug fix: Splash screen and auth windows don't overlap with main window

---

app/components/job/action/add/pool-picker.component.ts
app/services/core/data/list-view.ts
app/styles/base/advanced-filter.scss

Fix: Pool picker empty after changing account

---

app/components/file/browse/file-explorer/file-table-view/file-table-view.html

Fix: Don't show Last modified if node is a directory

---

CHANGELOG.md
ThirdPartyNotices.txt
app/components/base/property-list/link-property/link-property.html
app/components/base/property-list/property-content/property-content.scss
package.json
scripts/publish/publish.ts

Prepare for release 0.13.0

---

.travis.yml
src/client/main.ts
src/client/startup.ts
yarn.lock

Fix: logger creating multiple folder

---

app/components/base/duration-picker/duration-picker.component.ts
app/components/base/form/complex-form/complex-form.scss
app/components/node/connect/node-connect.component.ts
app/components/node/connect/node-connect.html
app/components/node/connect/node-user-credentials-form.component.ts
app/services/node-user.service.ts

Fix: Node connect always says expire in 24h

---

app/components/pool/graphs/heatmap/nodes-heatmap.component.ts

fix #1095 
The recent change to the list layout being OnPush uncoverered an issue in the heatmap to handling changes correctly

Fix: Heatmap not showing any nodes

---

app/components/market/home/market.html

Fix: Market -> Gallery typo

---

app/models/forms/create-form-group-model.ts

Fix issue with uploading to an existing FG

---

app/components/account/details/programatic-usage/aad-credentials-picker/resource-permission-button/resource-permission-button.component.spec.ts
app/components/file/browse/file-explorer/file-explorer-workspace.ts
app/components/task/details/output/task-outputs.component.ts
test/app/components/task/details/output/task-output.component.spec.ts

There was a few error logged in the test that were not crashing them.

Fix: Some error being logged in the test

---

app/components/file/browse/file-browse.module.ts
app/components/file/browse/file-explorer/file-explorer.module.ts
app/components/file/browse/file-explorer/file-table-view/file-table-view.html
app/components/file/browse/file-explorer/file-tree-view/file-tree-view-row/file-tree-view-row.component.ts
app/components/file/browse/file-explorer/file-tree-view/file-tree-view-row/file-tree-view-row.html
app/components/file/browse/file-explorer/file-tree-view/file-tree-view-row/file-tree-view-row.scss
app/components/file/browse/file-explorer/file-tree-view/file-tree-view-row/index.ts
app/components/file/browse/file-explorer/file-tree-view/file-tree-view.component.ts
app/components/file/browse/file-explorer/file-tree-view/file-tree-view.html
app/components/file/browse/file-explorer/file-tree-view/file-tree-view.scss
app/components/file/browse/file-explorer/file-tree-view/index.ts
app/components/file/browse/file-explorer/index.ts

fix #1062 
Include: 
* Arrow up/down to move focus
* Arrow right/left to expand/collapse folder
* Space to open file

Feature: File explorer keyboard navigation

---

src/@batch-flask/ui/card/card.scss

Fix: Clicking on account details before done loading redirect to app packages

---

app/components/account/details/account-details.scss

Fix: no storage account banner on app list not wrapping

---

app/components/account/details/account-details.component.ts
app/services/application-service.ts
app/services/quota.service.ts

Fix: account details not disposing data

---

app/components/job-schedule/browse/job-schedule-list.component.ts
app/components/node/browse/node-list.component.ts
app/components/pool/browse/pool-list.component.ts
app/components/task/browse/task-list.component.ts
app/services/core/data/generic-view.ts
app/services/core/data/list-view.ts

Fix: Data not being disposed correctly when switching accounts

---

app/services/file-service.ts

Fix refactor bug that killed viewing files in the explorer

---

app/components/job/action/add/job-create-basic-dialog.component.ts
app/components/job/action/add/job-create-basic-dialog.html
app/components/task/action/add/task-create-basic-dialog.component.ts

Feature: Added support for picking custom user account on task and job hook tasks

---

app/components/pool/details/pool-configuration.html

Usability: Hide pool os properties if using custom image

---

app/components/pool/action/add/pool-create-basic-dialog.component.ts
app/components/pool/action/add/pool-create-basic-dialog.html

Fix: user accounts and start task not showing if auto storage not setup

---

app/components/pool/action/add/vm-size-picker/vm-size-picker.component.ts
app/components/pool/action/add/vm-size-picker/vm-size-picker.html
src/@batch-flask/ui/index.ts

Fix: Vm size picker crash if sizes not loaded

---

ThirdPartyNotices.txt
package.json
scripts/lca/default-licenses/apache-2.0.txt
scripts/lca/default-licenses/electron.txt
scripts/lca/generate-third-party.ts
yarn.lock

Update with electron license

---

app/components/account/details/account-details.html
app/components/account/details/programatic-usage/programatic-usage.html

Fix tool tip for account credentials and add resource ID

---

.stylelintrc.json
CHANGELOG.md
app/components/node/details/node-details.html
docs/new-release.md
package.json
scripts/publish/publish.ts

Prepare for release 0.14.0

---

CHANGELOG.md
package.json
src/@batch-flask/ui/browse-layout/browse-layout.component.ts

Fix: selecting item close the filter

---

app/components/account/home/account-home.html
app/components/data/home/data-home.html
src/@batch-flask/ui/batchui.module.ts
src/@batch-flask/ui/browse-layout/browse-layout.scss
src/@batch-flask/ui/index.ts
src/@batch-flask/ui/select/index.ts
src/@batch-flask/ui/select/option/index.ts
src/@batch-flask/ui/select/option/option.component.ts
src/@batch-flask/ui/select/option/option.html
src/@batch-flask/ui/select/select.component.spec.ts
src/@batch-flask/ui/select/select.component.ts
src/@batch-flask/ui/select/select.html
src/@batch-flask/ui/select/select.module.ts
src/@batch-flask/ui/select/select.scss

Feature: New select component

---

app/services/ncj-template.service.ts
package.json

Use load-json-file package to strip BOM

---

src/@batch-flask/core/server-error/server-error.ts

Handle string based error messages

---

app/components/node/connect/node-connect.component.ts
app/components/node/details/node-configuration.component.ts
app/components/node/details/node-configuration.html

Rename adress to address

---

app/app.routes.ts
app/components/data/browse/data-container-list.component.ts
app/components/data/browse/data-container-list.html
app/components/data/details/data-default.component.ts
app/components/data/details/data-details.component.ts
app/components/data/details/data-details.html
app/components/data/home/data-home.component.ts
app/components/data/home/data-home.html
app/components/data/home/data-home.scss
app/services/core/data/storage-list-getter.ts
app/services/storage/auto-storage.service.ts
app/services/storage/storage-blob.service.ts
app/services/storage/storage-container.service.ts
src/@batch-flask/ui/browse-layout/browse-layout.component.ts
src/@batch-flask/ui/browse-layout/browse-layout.scss
src/@batch-flask/ui/loading/loading.component.ts
src/@batch-flask/ui/loading/loading.html
src/@batch-flask/ui/select/select.component.ts
src/@batch-flask/ui/select/select.html

Fix: Storage container issues

---

app/components/account/base/auto-storage-account-picker/auto-storage-account-picker.component.spec.ts
app/components/account/details/account-details.html
app/components/pool/action/add/app-license-picker/app-license-picker.html
src/@batch-flask/ui/table/table-cell/table-cell.component.spec.ts
src/@batch-flask/ui/table/table-cell/table-cell.component.ts
src/@batch-flask/ui/table/table-cell/table-cell.html
src/@batch-flask/ui/table/table-column/table-column.component.ts
src/@batch-flask/ui/table/table-head/table-head.component.ts
src/@batch-flask/ui/table/table-row/table-row.component.ts
src/@batch-flask/ui/table/table-row/table-row.html
src/@batch-flask/ui/table/table.component.ts
src/@batch-flask/ui/table/table.html
src/@batch-flask/ui/table/table.scss
src/test/utils/mocks/components/table.component.mock.ts

Added an input called `defaultWidth` to a column.
Called `defaultWidth` instead of `width` to work with future work on resizable columns
fix #1239

Internal: Support providing width of column

---

app/components/task/browse/preview/task-preview.component.ts
app/components/task/browse/preview/task-preview.html
app/components/task/browse/preview/task-preview.scss
src/@batch-flask/ui/quick-list/quick-list-item-status/quick-list-item-status.component.ts

Feature: Show completed task running time

---

app/components/market/application-action/choose-action.component.ts
app/components/market/application-action/choose-action.html
app/components/market/application-action/choose-action.scss

Open gallery application template in github

---

app/components/market/submit/submit-ncj-template.component.spec.ts
app/components/market/submit/submit-ncj-template.component.ts
python/controllers/ncj_controller.py
python/requirements.txt
python/server/app.py
python/server/websocket_server.py

fix #1219(Support autopool for local templates)
fix #1082(Empty default values)

Update azure-batch-extensions and support autopool for local templates

---

app/components/common/download-folder-dialog/download-folder-dialog.html
app/components/data/shared/blob-container-picker/blob-container-picker.html
app/components/data/shared/cloud-file-picker/cloud-file-picker.html
app/components/data/shared/file-group-picker/file-group-picker.html
app/components/data/shared/file-group-sas/file-group-sas.html
app/components/market/submit/parameter-input/parameter-input.html
app/components/pool/action/add/pool-create-basic-dialog.html
app/components/pool/action/scale/pool-scale-picker.component.ts
app/components/pool/action/scale/pool-scale-picker.scss
app/styles/base/forms.scss
app/styles/pool/create.scss
src/@batch-flask/ui/form/expanding-textarea/expanding-textarea.html
src/@batch-flask/ui/form/form-field/form-field.component.ts
src/@batch-flask/ui/form/form-field/form-field.html
src/@batch-flask/ui/form/form.module.ts
src/@batch-flask/ui/form/hint/hint.component.ts
src/@batch-flask/ui/form/hint/hint.scss
src/@batch-flask/ui/form/hint/index.ts

UI feat: Form field support hints and error nicely

---

app/components/data/details/data-container-files.component.ts
app/components/data/details/data-container-files.html
app/components/file/browse/blob-files-browser/blob-files-browser.component.ts
app/components/file/browse/file-explorer/file-explorer.component.ts
app/components/file/browse/file-explorer/file-explorer.html
app/components/file/browse/file-explorer/file-tree-view/file-tree-view.component.ts
app/services/file/file-navigator/file-navigator.ts
app/services/storage/storage-blob.service.ts
python/server/websocket_server.py
src/@batch-flask/ui/dialogs/confirmation-dialog.component.ts
src/@batch-flask/ui/dialogs/dialog.service.ts
src/@batch-flask/ui/form/complex-form/complex-form.component.ts
src/@batch-flask/ui/form/simple-form/simple-form.component.ts
src/@batch-flask/ui/index.ts

fix #1290 
This also redesign how delete files works by having a field on a file navigator to specify how to delete files

Fix: Broken folder delete and redesign logic

---

app/components/job/job-hook-task/job-hook-task-details/job-hook-task-details.component.ts

Fix: Job prep/release task not loading node

---

src/@batch-flask/ui/select/select.component.ts
src/@batch-flask/ui/select/select.html
src/@batch-flask/ui/select/select.scss

Feature: Select disable support

---

app/models/blob-container.ts
app/services/core/data/storage-entity-getter.ts
app/services/core/data/storage-list-getter.ts
app/services/storage/storage-container.service.ts

Fix: storage container pin

---

app/components/account/browse/account-list/account-list.html
app/components/account/details/account-default.component.ts
app/styles/base/layout.scss

Fix: Account list now showing loading icon on first load

---

app/components/data/browse/data-container-list.component.ts
app/components/job/browse/job-list.component.ts
app/components/task/browse/task-list.component.ts
src/@batch-flask/ui/select/select.component.ts
src/@batch-flask/ui/select/select.html
src/@batch-flask/ui/select/select.scss

List components not having OnPush were making the forms extremely laggy(To much to check at every key input)

Internal: Change some component change detection to OnPush and select keyboard nav tweaks

---

app/components/job/job-hook-task/job-hook-task-browser/job-hook-task-browser.scss
app/components/job/job-hook-task/job-hook-task-details/job-hook-task-details.html
app/components/job/job-hook-task/job-hook-task-details/job-hook-task-details.scss

Fix: Job prep/release tasks not displaying correctly

---

app/components/node/connect/node-connect.component.ts
src/@batch-flask/ui/form/complex-form/complex-form.scss

Fix: Expiry time not showing when generting creds for node connect

---

app/components/job/details/job-progress-status/job-progress-status.component.spec.ts
app/components/job/details/job-progress-status/job-progress-status.component.ts

Fix: Job gauge use current nodes instead of target to prevent overflow

---

CHANGELOG.md
ThirdPartyNotices.txt
package.json

Prepare for release 0.15.0

---

index.html
index.js

Website: Update batchlabs website to point to azure storage builds

---

app/components/job-schedule/action/add/job-schedule-create-basic-dialog.component.ts
app/components/job-schedule/action/add/job-schedule-create-basic-dialog.html
app/components/job/action/add/job-create-basic-dialog.component.ts
app/components/job/action/add/job-create-basic-dialog.html
app/components/pool/action/add/pool-create-basic-dialog.component.ts
app/components/pool/action/add/pool-create-basic-dialog.html
app/models/forms/create-job-model.ts
app/models/forms/create-job-schedule-model.ts
app/models/forms/create-pool-model.ts
src/@batch-flask/ui/datetime-picker/datetime-picker.scss
src/@batch-flask/ui/editor/editor.component.ts
src/@batch-flask/ui/form/editable-table/editable-table.component.ts

Fixed #1318, Added metadata picker in
1) pool create form
2) job create/edit form
3) job schedule create/edit form
- Fixed datetime picker calender icon size issue
- Fixed json editor caches previous data when first time load after close unsaved form
- Fixed editable table not populating default for empty table when switching view issue

Feature: metadata picker

---

app/components/pool/base/app-packages/app-package-picker.component.ts
appveyor.yml
karma.conf.js
src/@batch-flask/core/index.ts
src/@batch-flask/core/key-navigator/index.ts
src/@batch-flask/core/key-navigator/list-key-navigator.spec.ts
src/@batch-flask/core/key-navigator/list-key-navigator.ts
src/@batch-flask/ui/form/editable-table/editable-table.component.ts
src/@batch-flask/ui/select/option/option.component.ts
src/@batch-flask/ui/select/option/option.html
src/@batch-flask/ui/select/select-dropdown/select-dropdown.component.ts
src/@batch-flask/ui/select/select-dropdown/select-dropdown.html
src/@batch-flask/ui/select/select.component.ts
src/@batch-flask/ui/select/select.html
src/test/utils/helpers/template-interaction.ts

Feature: Improve select keyboard navigation

---

app/components/task/base/resourcefile-picker.component.spec.ts
app/components/task/base/resourcefile-picker.component.ts
src/@batch-flask/core/keys.ts
src/@batch-flask/ui/form/editable-table/editable-table.component.spec.ts
src/@batch-flask/ui/form/editable-table/editable-table.component.ts
src/@batch-flask/ui/form/editable-table/editable-table.html
src/@batch-flask/ui/form/editable-table/editable-table.scss
test/app/components/base/form/editable-table/editable-table.component.spec.ts

Fix: Pressing enter on editable table removes the row

---

app/components/data/shared/file-group-picker/file-group-picker.component.ts
app/components/data/shared/file-group-sas/file-group-sas.component.ts
app/services/storage/storage-account-keys.service.ts
src/client/core/batchlabs-application.ts

Fix: File group try loading before auto storage account is resolved

---

app/components/account/details/account-details.component.ts
app/components/account/details/account-details.html
app/services/application.service.ts
app/styles/base/focus-section.scss
src/@batch-flask/ui/index.ts
src/@batch-flask/ui/list-and-show-layout/entity-details-list.scss
src/@batch-flask/ui/table/table-column-manager.ts
src/@batch-flask/ui/table/table-column/table-column.component.ts
src/@batch-flask/ui/table/table-head/table-head-cell/table-head-cell.component.ts
src/@batch-flask/ui/table/table-head/table-head.component.ts
src/@batch-flask/ui/table/table-head/table-head.html
src/@batch-flask/ui/table/table-row-render/table-row-render.html
src/@batch-flask/ui/table/table-row-render/table-row.component.ts
src/@batch-flask/ui/table/table.component.spec.ts
src/@batch-flask/ui/table/table.component.ts
src/@batch-flask/ui/table/table.scss
src/client/proxy/proxy-settings.ts
src/test/utils/helpers/template-interaction.ts

Feature: Resiable table

---

app/components/pool/start-task/start-task-picker.component.ts

Feature: Wait for success is the default

---

src/client/core/batchlabs-application.ts

Fix: Rate card api authorization error

---

src/@batch-flask/ui/select/select.component.spec.ts
src/@batch-flask/ui/select/select.component.ts

Fix: Select not showing selected value if set before receiving new options

---

app/components/account/base/auto-storage-account-picker/auto-storage-account-picker.component.ts
app/components/data/home/data-home.component.ts
app/components/data/shared/storage-account-picker/storage-account-picker.component.ts
src/client/core/batchlabs-application.ts

Fix: Going to data tab before account is loaded raise error

---

app/components/pool/graphs/performance-graph/cpu-usage/cpu-usage-graph.component.ts
app/components/pool/graphs/performance-graph/cpu-usage/cpu-usage-graph.html
app/components/pool/graphs/performance-graph/disk-io/disk-io-graph.component.ts
app/components/pool/graphs/performance-graph/disk-io/disk-io-graph.html
app/components/pool/graphs/performance-graph/disk-usage/disk-usage-graph.component.ts
app/components/pool/graphs/performance-graph/disk-usage/disk-usage-graph.html
app/components/pool/graphs/performance-graph/memory-usage/memory-usage-graph.component.ts
app/components/pool/graphs/performance-graph/memory-usage/memory-usage-graph.html
app/components/pool/graphs/performance-graph/network-usage/network-usage-graph.component.ts
app/components/pool/graphs/performance-graph/network-usage/network-usage-graph.html
app/components/pool/graphs/performance-graph/performance-data.ts
app/components/pool/graphs/performance-graph/performance-graph.component.ts
app/models/app-insights/index.ts
app/models/app-insights/metrics-result.ts
app/services/app-insights/app-insights-query.service.ts
app/services/app-insights/metric-definition.ts
app/services/app-insights/query-result-processor.spec.ts
app/services/app-insights/query-result-processor.ts
src/@batch-flask/ui/charts/chart.directive.ts

Feature: Pool nodes metrics show individual nodes lines

---

app/components/data/browse/data-container-list.html
app/components/node/browse/display/node-list-display.component.ts
app/components/node/browse/display/node-list-display.scss
app/components/node/browse/node-list.html
app/components/task/browse/display/task-list-display.component.ts
app/components/task/browse/display/task-list-display.scss
app/components/task/browse/task-list.html

Fix: Task list not scrolling

---

CHANGELOG.md
app/components/account/home/account-home.html
appveyor.yml
package.json

Fix: 3rd subscription always disabled in account list

---

package.json
yarn.lock

Upgrade get-proxy-settings to include ProxyEnable fix

---

app/services/storage/storage-client-proxy-factory.ts
app/services/storage/storage-client.service.ts

Fix: Storage api enable exponential retries

---

src/@batch-flask/ui/browse-layout/browse-layout.component.ts
src/@batch-flask/ui/browse-layout/browse-layout.html
src/@batch-flask/ui/browse-layout/browse-layout.module.ts
src/@batch-flask/ui/browse-layout/browse-layout.scss
src/@batch-flask/ui/browse-layout/toggle-filter-button/index.ts
src/@batch-flask/ui/browse-layout/toggle-filter-button/toggle-filter-button.component.spec.ts
src/@batch-flask/ui/browse-layout/toggle-filter-button/toggle-filter-button.component.ts
src/@batch-flask/ui/browse-layout/toggle-filter-button/toggle-filter-button.html
src/@batch-flask/ui/browse-layout/toggle-filter-button/toggle-filter-button.scss
src/@batch-flask/ui/buttons/clickable/clickable.component.ts

Feature: Show marker to let user know filter were selected

---

app/components/account/browse/account-list/account-list.component.ts
app/components/pool/details/pool-details.html

Clicking on the account refresh also refresh subscriptions

---

app/components/account/browse/account-dropdown.component.ts
app/components/account/browse/account-dropdown.html
app/components/layout/footer/rpc-server-status/rpc-server-status.component.spec.ts
app/components/layout/footer/rpc-server-status/rpc-server-status.component.ts
app/components/layout/footer/rpc-server-status/rpc-server-status.html
app/components/layout/footer/rpc-server-status/rpc-server-status.scss
app/components/layout/pinned-entity-dropdown/pinned-dropdown.component.ts
app/components/layout/pinned-entity-dropdown/pinned-dropdown.html
src/@batch-flask/ui/dropdown/dropdown.component.ts
src/@batch-flask/ui/dropdown/dropdown.html
src/@batch-flask/ui/dropdown/dropdown.module.ts
src/@batch-flask/ui/index.ts
src/@batch-flask/ui/notifications/persisted-dropdown/persisted-notifications-dropdown.component.ts
src/@batch-flask/ui/notifications/persisted-dropdown/persisted-notifications-dropdown.html
src/test/utils/mocks/services/electron-remote.service.mock.ts

Also include change to OnPush change detection to improve performance

Accessiblity: Header and footer dropdowns navigable via keyboard

---

app/app.module.ts
app/components/account/home/account-home.html
app/components/common/subscription-picker/subscription-picker.html
app/models/index.ts
app/models/subscription.ts
app/models/tenant-details.ts
app/services/index.ts
app/services/ms-graph/core/aad-graph-http.service.ts
app/services/subscription.service.ts
app/services/tenant-details.service.ts

Feature: Get tenant details and display next to subscription pickers

---

app/services/adal/adal.service.spec.ts
app/services/adal/adal.service.ts
src/@batch-flask/core/server-error/server-error.ts
src/client/core/aad/adal/aad.service.ts
test/app/components/application/action/create/application-create-dialog.component.spec.ts
test/app/components/application/action/edit/application-edit-dialog.component.spec.ts

Feature: Handle not loading tenants

---

app/app.component.ts
src/client/core/batchlabs-application.ts
src/client/core/main-window-manager.ts
src/client/startup.ts

Fix: Opening 2nd instance of BatchLabs doesn't work and create ghost processes

---

CHANGELOG.md
ThirdPartyNotices.txt
package.json

Prepare for release 0.16.0

---

app/components/task/browse/display/task-list-display.html

Fix: Task list exit code is cropped

---

app/components/data/shared/cloud-file-picker/cloud-file-picker.scss
app/components/data/shared/file-group-sas/file-group-sas.scss
app/components/market/application-action/choose-action.scss

Fix NCJ template action CSS

---

app/components/account/details/account-details.html
app/components/account/details/programatic-usage/programatic-usage.html

Fix: Add https prefix to the account url 

---

app/services/file/file-navigator/file-navigator.ts

Fix: deleting folder, deletes all folder starting with that name

---

CHANGELOG.md
app/components/application/details/application-package-table.html
package.json

Fix: Application package table show state

---

app/components/layout/header/header.component.spec.ts
app/components/layout/header/header.component.ts
app/components/layout/header/header.scss
src/@batch-flask/ui/electron/current-browser-window.service.ts
src/@batch-flask/ui/electron/current-browser-window/current-browser-window.service.spec.ts
src/@batch-flask/ui/electron/current-browser-window/current-browser-window.service.ts
src/@batch-flask/ui/electron/current-browser-window/index.ts
src/@batch-flask/ui/electron/electron.module.ts
src/@batch-flask/ui/electron/index.ts
src/@batch-flask/ui/electron/os.service.ts
src/@batch-flask/utils/os/os.ts
src/client/main-window/main-window.ts
src/test/utils/mocks/windows/windows.mock.ts

Feature: Osx title bar hidden(inline with header) 

---

app/components/file/details/image-file-viewer/image-file-viewer.component.spec.ts
app/components/file/details/image-file-viewer/image-file-viewer.component.ts
app/components/file/details/image-file-viewer/image-file-viewer.html
app/components/market/application-action/choose-action.html
app/components/market/home/market.html
app/components/settings/default-settings.json
app/services/file/file-loader.ts
src/client/splash-screen/splash-screen.html

Accessiblity: Img tags missing alt tags + tests

---

CHANGELOG.md
app/components/pool/graphs/heatmap/nodes-heatmap.component.spec.ts
app/components/pool/graphs/heatmap/nodes-heatmap.component.ts
package.json
src/@batch-flask/utils/logging/node-logger.ts
src/@batch-flask/utils/logging/renderer-logger.ts

fix #1484
Was an issue with the warning message logged when having more than 2500 nodes.

Fix: Heatmap not showing if having more than 2500 nodes

---

app/components/task/browse/display/task-list-display.html
src/@batch-flask/ui/abstract-list/abstract-list-base.ts
src/@batch-flask/ui/table/table-row-render/table-row.component.ts

Fix: Context menu not showing on table

---

CHANGELOG.md
ThirdPartyNotices.txt
package-lock.json
package.json
scripts/lca/generate-third-party.ts

Prepare for release 0.17.0

---

app/components/task/browse/display/task-list-display.html
app/components/task/browse/preview/index.ts
app/components/task/browse/preview/task-preview.component.ts
app/components/task/browse/preview/task-preview.html
app/components/task/browse/preview/task-runtime.component.ts
app/components/task/browse/preview/task-runtime.html
app/components/task/browse/preview/task-runtime.scss
app/components/task/browse/task-browse.module.ts
app/styles/job/base.scss

Fix: #1501
Shows success and failure color matching to state column.

Add run time to the task grid

---

CHANGELOG.md
app/components/task/details/output/task-outputs.component.spec.ts
app/components/task/details/output/task-outputs.component.ts
app/components/task/details/task-configuration.html
package-lock.json
package.json

Fix: Task outputs when no auto storage account provided

---

CHANGELOG.md
app/models/node-connection-settings.ts
app/services/node-connect/node-connect.service.ts

Fix:One-click-connect for Windows Cloud Service

---

CHANGELOG.md
package.json
src/client/core/batch-explorer-application.ts

Fix issue with govt cloud switching

---

app/models/account.ts

Fix account navigation not working

---

app/components/account/details/account-details.component.ts
app/components/account/details/account-details.html
app/components/account/details/account-details.scss
app/components/account/home/account-home.component.ts
app/components/account/home/account-home.scss
app/components/market/home/recent-template-list/recent-template-list.html
app/styles/account/browse.scss
src/@batch-flask/ui/table/table.component.ts
src/@batch-flask/ui/table/table.html

account favorite icon css (Fix: #1545)
account subscription ddl and search css
recent templates spelling mistake
padding to bottom of "getting started" card

Fix up some css styling for accounts and details

---

CHANGELOG.md
app/components/account/details/programatic-usage/programatic-usage.html
app/models/storage-account.ts
app/services/python-rpc/python-rpc.service.ts
package.json
python/controllers/create_file_group_controller.py
python/requirements.txt
python/server/aad_auth.py

Fix for storage authentication bug

---

src/@batch-flask/ui/activity-monitor/activity-monitor-footer-item/activity-monitor-footer-item.component.spec.ts
src/@batch-flask/ui/activity-monitor/activity-monitor-footer-item/activity-monitor-footer-item.component.ts
src/@batch-flask/ui/activity-monitor/activity-monitor-footer-item/activity-monitor-footer-item.html
src/@batch-flask/ui/activity-monitor/activity/activity-processor.model.ts
src/@batch-flask/ui/activity-monitor/activity/activity.model.ts
src/@batch-flask/ui/file/file-navigator/file-navigator.ts

Add upload progress to footer as a percentage

---

app/utils/storage-utils.spec.ts
app/utils/storage-utils.ts

Disallow colon character in storage container names

---

CHANGELOG.md
app/services/pricing.service.ts
app/services/pricing/pricing.model.ts
package-lock.json

Fix: rate card api braking change

---

docs/new-release.md
package-lock.json
src/@batch-flask/ui/sidebar/sidebar-bookmarks/sidebar-bookmarks.scss

Fix sidebar bookmark css and update docs for release

---

app/services/azure-batch/file/file.service.ts
src/@batch-flask/ui/file/file-navigator/file-navigator.ts
src/@batch-flask/ui/file/file-navigator/file-tree.model.ts
src/@batch-flask/ui/file/file-navigator/helper.ts

Fix: Viewing filename with backslash on linux

---

app/components/node/action/node-commands.ts
app/components/node/browse/node-list.component.ts
app/components/node/details/node-details.component.ts

This was resulting in a 404 not found as pool id was undefined

Fix: Trying to list nodes before pool id is set.

---

app/components/application/browse/application-list.component.spec.ts
src/@batch-flask/compiler/dev-translations-loader.ts
src/@batch-flask/core/i18n/i18n.service.spec.ts
src/@batch-flask/core/i18n/i18n.service.ts
src/@batch-flask/ui/activity-monitor/activity-monitor-footer-item/activity-monitor-footer-item.component.spec.ts
src/@batch-flask/ui/entity-commands/entity-command.i18n.yml
src/@batch-flask/ui/entity-commands/entity-command.spec.ts
src/@batch-flask/ui/entity-commands/entity-command.ts
test/app/components/application/details/application-details.component.spec.ts

Fix: Multi action message having double s(e.g. jobss)

---

app/services/azure-batch/pool-node-count/pool-node-count.service.ts

Fix: Node count memory leak

---

app/components/pool/action/add/app-license-picker/app-license-picker.component.spec.ts
app/components/pool/action/add/app-license-picker/app-license-picker.component.ts
app/models/application-license.ts

Feature: Get license pricing from rate card api

---

src/client/menu.ts

Show currently selected environment

---

app/components/settings/default-settings.json
app/models/settings.ts
app/services/github-data/github-data.service.spec.ts
app/services/github-data/github-data.service.ts
src/@batch-flask/ui/activity/activity-service.spec.ts

fix #955 
fix #1390 (Fix issue with timing in loading templates)
This let user specify a fork of the main repository. This can be useful to develop your own templates

Feature: Let user pick alternative repository for template

---

assets/style.css
index.html
index.js
insider.html

Update github pages with insider downloads

---

app/services/batch-account/local-batch-account.service.spec.ts
app/services/batch-account/local-batch-account.service.ts

Fix: Prevent user from adding the same local account twice

---

app/services/azure-batch/core/batch-http.service.ts
app/services/azure-batch/core/batch-shared-key-authenticator.spec.ts
app/services/azure-batch/core/batch-shared-key-authenticator.ts

Fix: Shared key not working for POST,DELETE requests

---

.vsts/pipelines.yml

This will register all dependencies and will check for any security and legal issues.

Internal: Add dependencies registration task

---

app/components/account/action/add/add-local-batch-account.component.ts
app/components/account/action/add/add-local-batch-account.html
app/services/azure-batch/core/batch-http.service.ts
app/services/telemetry/renderer-telemetry-uploader.ts
src/@batch-flask/core/telemetry/telemetry.service.ts
src/@batch-flask/utils/url-utils/url-utils.ts
src/client/client.module.ts
src/client/core/telemetry/application-insights-uploader.ts
src/client/core/telemetry/client-telemetry.module.ts
src/client/core/telemetry/index.ts
src/client/core/telemetry/machine-id.service.spec.ts
src/client/core/telemetry/machine-id.service.ts
src/client/core/telemetry/telemetry-manager.ts
src/common/constants/constants.ts

fix #1613 
Also include adding a sessionId and a random userId to the telemetry

Fix: Validate local account url and show error when trying to list pools if invalid

---

app/services/batch-account/batch-account.service.spec.ts
app/services/batch-account/batch-account.service.ts

Fix favorites broken when 1 has invalid id

---

app/components/account/browse/account-list/account-list.component.spec.ts
app/components/application/browse/application-list.component.spec.ts
src/@batch-flask/core/testing/index.ts
src/@batch-flask/core/testing/telemetry-testing.module.ts
src/@batch-flask/ui/entity-commands/entity-command.spec.ts
src/@batch-flask/ui/entity-commands/entity-command.ts
src/common/constants/constants.ts
test/app/components/application/details/application-details.component.spec.ts

Telemetry: track which action is being used

---

CHANGELOG.md
app/components/account/monitoring/monitor-chart/monitor-chart.component.ts

Fix: Monitoring chart null error when theme is not loaded yet.

---

app/components/account/action/create/batch-account-create.component.spec.ts
app/components/account/action/create/batch-account-create.component.ts
app/components/account/action/create/batch-account-create.html
app/components/account/base/auto-storage-account-picker/auto-storage-account-picker.component.ts
app/components/common/common.module.ts
app/components/common/location-picker/index.ts
app/components/common/location-picker/location-picker.component.spec.ts
app/components/common/location-picker/location-picker.component.ts
app/components/common/location-picker/location-picker.html
app/components/common/location-picker/location-picker.i18n.yml
app/components/common/location-picker/location-picker.module.ts
app/components/common/subscription-picker/subscription-picker.component.spec.ts
app/components/common/subscription-picker/subscription-picker.component.ts
app/components/common/subscription-picker/subscription-picker.html
src/@batch-flask/ui/form/form-error/form-error.component.ts
src/@batch-flask/ui/index.ts
src/@batch-flask/ui/select/option/option.component.ts
src/@batch-flask/ui/select/option/option.html
src/@batch-flask/ui/select/select.component.spec.ts
src/@batch-flask/ui/select/select.component.ts
src/@batch-flask/ui/select/select.html
src/test/utils/helpers/form-control-validators.ts

fix #1642
Also fixed issues with select component

Feature: New location picker + Cleanup account creation

---

CHANGELOG.md
app/models/dtos/index.ts
app/models/dtos/job-create.dto.ts
app/models/dtos/job-patch.dto.ts
app/models/dtos/pool-create/index.ts
app/models/dtos/pool-create/pool-create.dto.spec.ts
app/models/dtos/pool-create/pool-create.dto.ts
app/models/dtos/virtual-machine-configuration.dto.ts
package-lock.json

Fix: Cloning pool issue with readonly property kept

---

CHANGELOG.md
app/components/market/application-action/choose-action.component.ts
app/components/market/application-action/choose-action.html

Fix: Ncj view readme open it online

---

CHANGELOG.md
src/@batch-flask/ui/buttons/button.component.spec.ts
src/@batch-flask/ui/buttons/button.component.ts

Fix: Button not handling action not returning an observable or null

---

CHANGELOG.md
src/@batch-flask/ui/table/table-row-render/table-row-render.html
src/@batch-flask/ui/table/table.component.spec.ts

Fix: Multi select table checkbox

---

CHANGELOG.md
app/components/pool/details/error-display/pool-error-display.component.spec.ts
app/components/pool/details/error-display/pool-error-display.component.ts
package.json
src/@batch-flask/ui/banner/banner.component.ts
src/@batch-flask/ui/banner/banner.html
src/@batch-flask/ui/banner/banner.scss
src/test/utils/mocks/components/banner.component.mock.ts

Fix: Increase pool quota quick fix not working

---

CHANGELOG.md
src/@batch-flask/ui/property-list/text-property/text-property.component.spec.ts
src/@batch-flask/ui/property-list/text-property/text-property.component.ts

Fix: Copy non text property

---

CHANGELOG.md
package-lock.json
src/@batch-flask/ui/browse-layout/toggle-filter-button/toggle-filter-button.component.spec.ts
src/@batch-flask/ui/browse-layout/toggle-filter-button/toggle-filter-button.component.ts

Fix: Toggle filter button null exception

---

CHANGELOG.md
app/components/node/action/upload-node-logs/upload-node-logs-dialog.component.ts
app/components/pool/action/add/pool-os-picker.component.ts
app/utils/storage-utils.spec.ts
app/utils/storage-utils.ts

Fix parsing container url in national cloud

---

CHANGELOG.md
app/services/quota.service.ts

Fix: Quota usage not showing 

---

src/@batch-flask/utils/url-utils/url-utils.spec.ts
src/@batch-flask/utils/url-utils/url-utils.ts

Fix Url validation to accept IPs

---

src/@batch-flask/ui/buttons/button.component.spec.ts
src/@batch-flask/ui/buttons/button.component.ts
src/@batch-flask/ui/buttons/clickable/clickable.component.ts
src/@batch-flask/ui/property-list/property-group/property-group.component.spec.ts
src/@batch-flask/ui/property-list/property-group/property-group.component.ts
src/@batch-flask/ui/property-list/property-group/property-group.html
src/@batch-flask/ui/property-list/property-group/property-group.scss

- Navigable with keyboard
- `aria-expanded`
fix https://dev.azure.com/azurebatch/BatchExplorer/_workitems/edit/9
fix https://dev.azure.com/azurebatch/BatchExplorer/_workitems/edit/8
fix https://dev.azure.com/azurebatch/BatchExplorer/_workitems/edit/7

Accessibility: Property group accessibility

---

src/@batch-flask/ui/select/select-dropdown/select-dropdown.component.ts
src/@batch-flask/ui/select/select-dropdown/select-dropdown.html
src/@batch-flask/ui/select/select.component.spec.ts
src/@batch-flask/ui/select/select.component.ts
src/@batch-flask/ui/select/select.html
src/test/utils/helpers/template-interaction.ts

fix https://dev.azure.com/azurebatch/BatchExplorer/_workitems/edit/6

Accessibility: Select component tab should close the dropdown if open

---

app/components/account/details/programatic-usage/aad-credentials-picker/create-new-aad-app/create-new-aad-app.html
app/components/account/details/programatic-usage/aad-credentials-picker/generate-aad-app-secret/generate-aad-app-secret.html
src/@batch-flask/ui/table/table-head/table-head-cell/table-head-cell.component.ts
src/@batch-flask/ui/table/table.scss

fix https://dev.azure.com/azurebatch/BatchExplorer/_workitems/edit/5
fix https://dev.azure.com/azurebatch/BatchExplorer/_workitems/edit/15

Accessibility: Make table header accessible when sortable

---

app/components/layout/main-navigation/main-navigation.component.ts
app/components/layout/main-navigation/main-navigation.i18n.yml
app/components/market/home/market.html
src/@batch-flask/ui/auto-focus/auto-focus.directive.spec.ts
src/@batch-flask/ui/auto-focus/auto-focus.directive.ts
src/@batch-flask/ui/auto-focus/auto-focus.module.ts
src/@batch-flask/ui/auto-focus/index.ts
src/@batch-flask/ui/batchui.module.ts
src/@batch-flask/ui/browse-layout/browse-layout.html
src/@batch-flask/ui/browse-layout/browse-layout.module.ts

fix https://dev.azure.com/azurebatch/BatchExplorer/_workitems/edit/53

Accessibility: Main navigation accessible

---

app/components/market/application-action/choose-action.html
app/components/market/application-action/choose-action.scss

fix https://dev.azure.com/azurebatch/BatchExplorer/_workitems/edit/66

Accessibility: Choose action header separate text from image

---

app/components/job/graphs/all-job-graphs-home/jobs-bar-chart/jobs-bar-chart.component.ts
app/components/job/graphs/all-job-graphs-home/jobs-bar-chart/jobs-bar-chart.html
app/components/job/graphs/all-job-graphs-home/jobs-cpu-wait-time-graph/jobs-cpu-wait-time-graph.html
app/components/job/graphs/all-job-graphs-home/jobs-running-time-graph/jobs-running-time-graph.html

fix https://dev.azure.com/azurebatch/BatchExplorer/_workitems/edit/60

Accessibility: All job graphs aria label

---

src/@batch-flask/ui/file/file-explorer/file-tree-view/file-tree-view-row/file-tree-view-row.component.ts
src/@batch-flask/ui/file/file-explorer/file-tree-view/file-tree-view-row/file-tree-view-row.html
src/@batch-flask/ui/file/file-explorer/file-tree-view/file-tree-view.component.spec.ts
src/@batch-flask/ui/file/file-explorer/file-tree-view/file-tree-view.component.ts
src/@batch-flask/ui/file/file-explorer/file-tree-view/file-tree-view.html
src/@batch-flask/ui/file/file-explorer/file-tree-view/file-tree-view.scss
src/@batch-flask/ui/file/file-viewer/file-viewer-container/file-viewer-container.component.ts
src/@batch-flask/ui/file/file-viewer/file-viewer-container/file-viewer-container.html

Add screen reader functionality for tree view

Accessibility: Tree view accessible

---

app/components/job/action/add/job-create-basic-dialog.html
app/components/job/action/add/job-manager-task-picker.html
app/components/job/action/add/job-preparation-task-picker.html
app/components/job/action/add/job-release-task-picker.html
app/components/job/action/add/pool-picker/pool-picker.component.spec.ts
app/components/job/action/add/pool-picker/pool-picker.component.ts
app/components/job/action/add/pool-picker/pool-picker.html
app/components/job/action/add/pool-picker/pool-picker.i18n.yml
app/components/job/action/add/pool-picker/pool-picker.scss
app/components/market/submit/submit-ncj-template.component.spec.ts
app/components/pool/action/add/container-configuration.html
app/components/pool/action/add/container-images-picker.html
app/components/pool/action/add/container-registry-picker.html
app/components/pool/network-configuration/inbound-nat-pool-picker.html
app/components/pool/network-configuration/network-security-group-rules.component.ts
app/components/pool/network-configuration/network-security-group-rules.html
app/components/pool/start-task/start-task-picker.html
app/components/task/base/resourcefile-picker.component.ts
app/components/task/base/resourcefile-picker.html
data/themes/classic.json
src/@batch-flask/ui/form/editable-table/editable-table.component.ts
src/@batch-flask/ui/form/editable-table/editable-table.html
src/@batch-flask/ui/form/editable-table/editable-table.scss
src/@batch-flask/ui/form/form-page/form-page.html
src/@batch-flask/ui/form/key-value-picker/key-value-picker.component.ts
src/@batch-flask/ui/form/key-value-picker/key-value-picker.html

fix https://dev.azure.com/azurebatch/BatchExplorer/_workitems/edit/76

Accessibility: various fixes

---

.vsts/linux/linux-dependencies.yml
.vsts/pipelines.yml
docs/virtual-scroll.md
src/@batch-flask/ui/abstract-list/abstract-list-base.ts
src/@batch-flask/ui/activity/activity-monitor/activity-monitor-tree-view/activity-monitor-tree-view.component.ts
src/@batch-flask/ui/activity/activity-monitor/activity-monitor-tree-view/activity-monitor-tree-view.html
src/@batch-flask/ui/quick-list/quick-list.html
src/@batch-flask/ui/table/table.component.spec.ts
src/@batch-flask/ui/table/table.html
src/@batch-flask/ui/testing/virtual-scroll/virtual-scroll.testing.module.ts
src/@batch-flask/ui/virtual-scroll/index.ts
src/@batch-flask/ui/virtual-scroll/virtual-scroll-row.directive.ts
src/@batch-flask/ui/virtual-scroll/virtual-scroll.component.spec.ts
src/@batch-flask/ui/virtual-scroll/virtual-scroll.component.ts
src/@batch-flask/ui/virtual-scroll/virtual-scroll.html
src/@batch-flask/ui/virtual-scroll/virtual-scroll.module.ts

fix #1710 
also fix #1695 (Upgrade VSTS pool)

Internal: Virtual scroll better use

---

data/themes/classic.json
data/themes/theme.schema.json
src/@batch-flask/ui/scrollable/scrollable.component.ts
src/app/app.module.ts
src/app/components/account/account.module.ts
src/app/components/account/details/account-cost-card/account-cost-card.component.spec.ts
src/app/components/account/details/account-cost-card/account-cost-card.component.ts
src/app/components/account/details/account-cost-card/account-cost-card.html
src/app/components/account/details/account-cost-card/account-cost-card.i18n.yml
src/app/components/account/details/account-cost-card/account-cost-card.scss
src/app/components/account/details/account-cost-card/index.ts
src/app/components/account/details/account-details.html
src/app/services/azure-consumption/index.ts
src/app/services/azure-consumption/usage-details/index.ts
src/app/services/azure-consumption/usage-details/usage-details.service.spec.ts
src/app/services/azure-consumption/usage-details/usage-details.service.ts
src/app/services/azure-http.service.ts
src/app/services/pricing.service.ts
src/app/services/themes/chart-colors.spec.ts
src/app/services/themes/chart-colors.ts
src/app/services/themes/theme-core.ts
src/app/services/themes/theme-definition.model.ts
src/app/services/themes/theme.model.ts
src/app/styles/base/layout.scss
src/common/constants/constants.ts

Feature: Show cost of batch account for current billing period

---

data/themes/classic.json
src/@batch-flask/ui/select/select.component.ts
src/@batch-flask/ui/select/select.html
src/app/components/account/details/account-cost-card/account-cost-card.html
src/app/components/pool/graphs/pool-graphs.i18n.yml
src/app/components/settings/settings.scss
src/app/components/task/base/task-state/task-state.html

Fix select combobox not read correctly in JAWS https://azurebatch.visualstudio.com/BatchExplorer/_workitems/edit/10
fix FileExplorer contrast https://azurebatch.visualstudio.com/BatchExplorer/_workitems/edit/131

Accessibility: Various fixes 8

---

CHANGELOG.md
app/components/pool/action/scale/pool-scale-picker.component.ts
app/components/pool/action/scale/pool-scale-picker.html
package-lock.json

Fix: Rescale pool issue with toggling between autoscale and fixed size

---

src/@batch-flask/ui/buttons/clickable/clickable.component.ts
src/app/components/layout/main-navigation/profile-button/profile-button.component.ts
src/common/constants/constants.ts

Fix: Submit issue or feature request link

---

src/@batch-flask/core/http-base.ts
src/@batch-flask/core/record/navigable-record.ts
src/@batch-flask/ui/file/file-loader/file-loader.ts
src/@batch-flask/ui/file/file-viewer/log-file-viewer/log-file-viewer.component.ts
src/app/components/layout/pinned-entity-dropdown/pinned-dropdown.component.spec.ts
src/app/components/layout/pinned-entity-dropdown/pinned-dropdown.component.ts
src/app/components/layout/pinned-entity-dropdown/pinned-dropdown.html
src/app/components/layout/pinned-entity-dropdown/pinned-dropdown.scss
src/app/services/azure-batch/file/file.service.spec.ts
src/app/services/azure-batch/file/file.service.ts
src/app/services/pinned-entity/pinned-entity.service.ts

Fix: Task output tailing

---

src/app/components/task/browse/task-list.component.ts

Fix: Call to list task with undefined job id

---

src/@batch-flask/core/index.ts
src/@batch-flask/core/rxjs-operators.ts
src/@batch-flask/ui/buttons/button.component.ts
src/@batch-flask/ui/buttons/button.html
src/@batch-flask/ui/buttons/button.scss
src/app/components/task/browse/preview/task-preview.html
src/app/components/task/browse/task-list.scss
src/app/components/task/details/task-details.html
src/app/components/task/details/task-details.module.ts
src/app/components/task/details/task-node-info/index.ts
src/app/components/task/details/task-node-info/task-node-info.component.spec.ts
src/app/components/task/details/task-node-info/task-node-info.component.ts
src/app/components/task/details/task-node-info/task-node-info.html
src/app/components/task/details/task-node-info/task-node-info.i18n.yml
src/app/components/task/details/task-node-info/task-node-info.scss
src/app/services/azure-batch/node/node.service.spec.ts
src/app/services/azure-batch/node/node.service.ts
src/app/services/azure-batch/pool/pool.service.spec.ts
src/app/services/azure-batch/pool/pool.service.ts

Feature: New direct link on the task summary to the pool and node

---

src/@batch-flask/ui/property-list/property-content/property-content.component.ts
src/@batch-flask/ui/property-list/property-field/property-field.component.ts
src/@batch-flask/ui/property-list/property-field/property-field.html

This remove the double focus for links and tables

Accessibility: Better property

---

src/@batch-flask/ui/datetime-picker/datetime-picker.component.spec.ts
src/@batch-flask/ui/datetime-picker/datetime-picker.component.ts
src/@batch-flask/ui/datetime-picker/datetime-picker.html
src/@batch-flask/ui/datetime-picker/datetime-picker.i18n.yml
src/@batch-flask/ui/datetime-picker/datetime-picker.scss

fix https://dev.azure.com/azurebatch/BatchExplorer/_queries/edit/82/?triage=true

Accessibility: Datetime picker label + redesign

---

data/themes/classic.json
src/@batch-flask/ui/browse-layout/browse-layout.component.ts
src/@batch-flask/ui/browse-layout/browse-layout.i18n.yml
src/@batch-flask/ui/buttons/clickable/clickable.component.ts
src/@batch-flask/ui/buttons/refresh-btn/refresh-btn.component.ts
src/@batch-flask/ui/common.i18n.yml
src/@batch-flask/ui/file/file-explorer/file-explorer-tabs/file-explorer-tabs.html
src/@batch-flask/ui/file/file-explorer/file-explorer.i18n.yml
src/@batch-flask/ui/file/file-explorer/file-tree-view/file-tree-view.html
src/@batch-flask/ui/form/editable-table/editable-table.html
src/@batch-flask/ui/property-list/entity-configuration/entity-configuration.html
src/@batch-flask/ui/property-list/entity-configuration/entity-configuration.i18n.yml
src/@batch-flask/ui/property-list/property-group/property-group.component.spec.ts
src/@batch-flask/ui/property-list/property-group/property-group.html
src/@batch-flask/ui/property-list/property-list.component.ts
src/@batch-flask/ui/property-list/property-list.module.ts
src/@batch-flask/ui/property-list/property-list.scss
src/@batch-flask/ui/quick-list/quick-list-row-render/quick-list-row-render.component.ts
src/@batch-flask/ui/quick-list/quick-list-row-render/quick-list-row-render.html
src/@batch-flask/ui/quick-list/quick-list.html
src/@batch-flask/ui/table/table-column-manager.ts
src/@batch-flask/ui/table/table-column/table-column.component.ts
src/@batch-flask/ui/table/table-head/table-head-cell/table-head-cell.component.ts
src/@batch-flask/ui/table/table.html
src/app/components/account/browse/account-list/account-list.html
src/app/components/account/monitoring/account-monitoring-home/account-monitoring-home.scss
src/app/components/job/action/add/job-preparation-task-picker.html
src/app/components/job/action/add/job-release-task-picker.html
src/app/styles/partials/loading-indicators.scss

https://dev.azure.com/azurebatch/BatchExplorer/_workitems/edit/18
https://dev.azure.com/azurebatch/BatchExplorer/_workitems/edit/44
https://dev.azure.com/azurebatch/BatchExplorer/_workitems/edit/46
https://dev.azure.com/azurebatch/BatchExplorer/_workitems/edit/88
https://dev.azure.com/azurebatch/BatchExplorer/_workitems/edit/130
https://dev.azure.com/azurebatch/BatchExplorer/_workitems/edit/164

Accessibility: Various fixes 11

---

scripts/azpipelines/build-type.ps1
scripts/swagger/validate-models.ts
src/@batch-flask/ui/file/file-explorer/file-explorer.component.ts
src/@batch-flask/ui/file/file-navigator/file-navigator.spec.ts
src/@batch-flask/ui/file/file-navigator/file-navigator.ts
src/@batch-flask/ui/sidebar/sidebar-page.spec.ts
src/@batch-flask/ui/sidebar/sidebar-spec-helper.spec.ts
src/@batch-flask/ui/sidebar/sidebar.spec.ts
src/@batch-flask/ui/table/table-column/table-column.component.ts
src/app/components/data/details/data-container-files.component.ts
src/app/components/data/details/data-container-files.html
src/app/components/file/browse/blob-files-browser/blob-files-browser.component.ts
src/app/services/storage/storage-blob.service.ts
src/client/menu/main-application-menu.ts

Fix: File explorer upload + refactor

---

package-lock.json
package.json
src/app/app.ts
src/app/components/common/location/location.component.spec.ts
src/app/components/common/location/location.component.ts
src/app/components/common/location/location.html
src/app/components/common/location/location.scss

Fix: Remove flags

---

src/@batch-flask/ui/sidebar/sidebar-page.ts
src/@batch-flask/ui/table/table.component.ts
src/app/components/data/action/add/file-group-create-form.component.ts
src/app/components/data/action/add/file-group-options-picker.html
src/app/components/gallery/gallery-routing.module.ts
src/app/components/gallery/gallery.module.ts
src/app/components/gallery/home/recent-template-list/recent-template-list.component.ts
src/app/components/gallery/home/recent-template-list/recent-template-list.html
src/app/components/gallery/submit-recent-template/submit-recent-template.component.ts
src/app/components/gallery/submit-recent-template/submit-recent-template.html
src/app/components/gallery/submit-recent-template/submit-recent-template.scss
src/app/components/gallery/submit/submit-ncj-template.component.ts
src/app/components/node/node.module.ts

Fix: Recent template, Edit start task

---

src/@batch-flask/ui/entity-commands/entity-command.spec.ts
src/@batch-flask/ui/entity-commands/entity-command.ts
src/app/components/node/action/node-commands.ts
src/app/components/node/browse/display/node-list-display.html
src/app/components/pool/details/pool-details.module.ts
src/app/components/pool/graphs/pool-graphs.module.ts
src/app/components/pool/graphs/pool-state-graph/pool-state-graph.component.ts
src/app/components/pool/graphs/pool-state-graph/pool-state-graph.html
src/app/components/pool/graphs/pool-state-graph/pool-state-graph.scss
src/app/services/azure-batch/node/node.service.ts
src/app/services/azure-batch/pool-node-count/pool-node-count.service.ts

Feature: Multi node delete support

---

config/webpack.config.base.js
config/webpack.config.prod.js
package.json
src/@batch-flask/electron/auto-update/auto-update-main.service.ts
src/@batch-flask/electron/auto-update/auto-update-renderer.service.ts
src/@batch-flask/electron/auto-update/base.ts
src/@batch-flask/electron/auto-update/index.ts
src/@batch-flask/electron/electron-main.module.ts
src/@batch-flask/electron/index.ts
src/@batch-flask/ui/editor/editor.component.ts
src/@batch-flask/ui/file/file-viewer/file-type-association/default-associations.ts
src/@batch-flask/ui/file/file-viewer/text-file-viewer/text-file-viewer.component.spec.ts
src/@batch-flask/ui/file/file-viewer/text-file-viewer/text-file-viewer.component.ts
src/@batch-flask/ui/form/form-json-editor/form-json-editor.component.ts
src/app/components/gallery/ncj-template-viewer/ncj-template-viewer.component.ts
src/client/client.module.ts

Performance Make all use of monaco editor load async

---

src/@batch-flask/ui/common.i18n.yml
src/@batch-flask/ui/select/select.component.ts
src/@batch-flask/ui/select/select.html
src/app/components/pool/action/add/pool-create-basic-dialog.component.ts
src/app/components/pool/network-configuration/virtual-network-picker/virtual-network-picker.component.spec.ts
src/app/components/pool/network-configuration/virtual-network-picker/virtual-network-picker.component.ts
src/app/components/pool/network-configuration/virtual-network-picker/virtual-network-picker.html
src/app/components/pool/network-configuration/virtual-network-picker/virtual-network-picker.i18n.yml

Feature/Fix: Allow to remove VNET selection when creating a pool

---

CHANGELOG.md
ThirdPartyNotices.txt
package-lock.json
package.json
scripts/lca/generate-third-party.ts
scripts/publish/publish.ts

Prepare for release 0.19.0

---

src/@batch-flask/ui/browse-layout/browse-layout.component.spec.ts
src/@batch-flask/ui/browse-layout/browse-layout.component.ts
src/@batch-flask/ui/browse-layout/browse-layout.module.ts

Fix: Close advanced filter slideout when selecting an item

---

src/app/components/job-schedule/action/job-schedule-action.module.ts
src/app/components/job/details/job-details.module.ts

Fix: Create job schedule from job not opening sidebar

---

src/@batch-flask/electron/auto-update/auto-update-main.service.ts
src/@batch-flask/electron/auto-update/base.ts
src/app/components/job/details/job-details.component.ts
src/app/components/layout/main-navigation/profile-button/profile-button.component.spec.ts
src/app/components/layout/main-navigation/profile-button/profile-button.component.ts
src/app/components/node/home/node-home.component.ts
src/app/services/adal/adal.service.spec.ts
src/app/services/adal/adal.service.ts
src/test/utils/mocks/notification.service.mock.ts

Fix: Catch check for updates error

---

CHANGELOG.md
package-lock.json
package.json
src/app/components/job/action/add/pool-picker/pool-picker.component.ts

Fix: Null pointer exception in pool picker when using Local Batch account

---

electron-builder.yml

Fix debian package configuration typo for dependencies

---

src/@batch-flask/ui/abstract-list/abstract-list-base.ts
src/@batch-flask/ui/file/file-loader/file-loader.spec.ts
src/@batch-flask/ui/file/file-loader/file-loader.ts

Fix: Handle null properties in FileLoader

---

CHANGELOG.md
src/@batch-flask/electron/auto-update/auto-update-renderer.service.ts
src/@batch-flask/electron/utils/electron-utils.spec.ts
src/@batch-flask/electron/utils/electron-utils.ts
src/@batch-flask/electron/utils/index.ts
src/app/services/adal/adal.service.spec.ts
src/app/services/adal/adal.service.ts
src/app/services/batch-explorer.service.ts
src/client/core/properties/batch-explorer-properties.ts

Fix: Wrap observable from main process so it unsubscribe when refreshing/closing window

---

CHANGELOG.md
package.json
src/@batch-flask/electron/auto-update/auto-update-renderer.service.ts
src/@batch-flask/electron/utils/electron-utils.spec.ts
src/@batch-flask/electron/utils/electron-utils.ts
src/app/components/pool/base/certificate-references/certificate-references-picker.i18n.yml
src/app/services/adal/adal.service.ts
src/app/services/batch-explorer.service.ts
src/app/services/ncj/portfolio/github-portfolio.spec.ts
src/app/services/ncj/portfolio/github-portfolio.ts

Fix: Using a branch with a / for github portfolio

---

src/@batch-flask/core/aad/access-token/access-token.model.ts
src/@batch-flask/core/key-navigator/list-key-navigator.spec.ts
src/@batch-flask/core/key-navigator/list-key-navigator.ts
src/@batch-flask/ui/abstract-list/abstract-list-base.ts
src/@batch-flask/ui/table/table-row-render/table-row-render.component.ts
src/@batch-flask/ui/table/table-row-render/table-row-render.html
src/@batch-flask/ui/table/table.component.spec.ts
src/@batch-flask/ui/table/table.component.ts
src/@batch-flask/ui/table/table.html
src/@batch-flask/ui/table/table.scss
src/app/services/python-rpc/python-rpc.service.ts
src/app/services/user-configuration/renderer-configuration-store.ts

Accessibility: Support focusing columns with keyboard in tables

---

src/@batch-flask/ui/entity-commands/entity-command-label-icon.ts
src/app/components/pool/action/pool-commands.i18n.yml
src/app/components/pool/action/pool-commands.ts
src/app/components/pool/action/scale/autoscale-formula-picker/autoscale-formula-picker.component.spec.ts
src/app/services/azure-batch/pool/pool.service.spec.ts
src/app/services/azure-batch/pool/pool.service.ts

fix #1884
Resize button is replaced with a stop resize button when the pool is resizing

Feature: Support aborting the resize of a pool

---

.vscode/extensions.json
.vscode/settings.json
.vscode/tasks.json
electron-builder.yml
src/@batch-flask/core/azure-environment/azure-environment.ts
src/@batch-flask/electron/utils/electron-utils.ts
src/app/components/settings/settings.html
src/app/services/adal/adal.service.spec.ts
src/app/services/adal/adal.service.ts
src/app/services/app-insights/app-insights-api.service.ts
src/app/services/arm-location/arm-location.service.spec.ts
src/app/services/azure-batch/core/batch-http.service.ts
src/app/services/azure-http.service.ts
src/app/services/batch-explorer.service.ts
src/app/services/ms-graph/core/aad-graph-http.service.ts
src/app/services/ms-graph/core/ms-graph-http.service.ts
src/app/services/python-rpc/python-rpc.service.ts
src/app/services/subscription/subscription.service.spec.ts
src/app/services/tenant-details.service.ts
src/client/core/aad/access-token/access-token.service.ts
src/client/core/aad/adal/aad.service.spec.ts
src/client/core/aad/adal/aad.service.ts
src/client/core/aad/authentication/authentication.service.ts
src/client/core/batch-explorer-application.ts
src/client/core/main-window-manager.ts
src/client/proxy/proxy-settings.ts
src/client/startup.ts
tsconfig.json
tslint.json

Fix: Switching Azure environments

---

package-lock.json
package.json

Component governance reported security vulnerabilities with some depenendcies.
This only applies to `master` branch and insider builds since the general dependeny update. Stable build are not affected

Fix: Vulnerabilities with lodash, handlebars

---

electron-builder.yml
src/client/startup.ts

Fix auto update in insider

---

src/@batch-flask/ui/file/file-loader/file-loader.spec.ts
src/@batch-flask/ui/file/file-loader/file-loader.ts
src/@batch-flask/ui/file/file-viewer/file-type-association/default-associations.ts
src/@batch-flask/utils/string-utils/string-utils.ts

fix #1928 
Was an issue with the filename containing escaped `/` -> `%2F` which `src=` didn't like

Fix: View images from node

---

src/app/components/application/action/batch-application-package-commands.ts
src/app/components/application/details/application-package-table.component.ts
src/app/components/application/details/application-package-table.html
src/app/components/application/details/application-packages.component.spec.ts
src/app/components/application/details/application-packages.component.ts

Fix: App packages list buttons enable/disable

---

src/@batch-flask/utils/misc/misc.spec.ts
src/@batch-flask/utils/misc/misc.ts

Bytes values in the app is rounded in weird ways -> 16 => 20

Fix: Printing of bytes wrong in the app

---

src/@batch-flask/ui/abstract-list/abstract-list-base.ts
src/@batch-flask/ui/dialogs/confirmation-dialog.html
src/@batch-flask/ui/dialogs/confirmation-dialog.scss
src/@batch-flask/ui/entity-commands/entity-command.ts

As there is a bug with Voice Over `aria-selected`. This can help the user in making sure he selected the right entities

Accessibility: Added summary of which items were multi selected

---

.vsts/darwin/darwin-dependencies.yml
package-lock.json
src/app/components/account/details/account-cost-card/account-cost-card.component.spec.ts
src/app/components/account/details/account-cost-card/account-cost-card.component.ts
src/app/services/arm-http.service.ts
src/app/services/azure-cost-management/azure-cost-management.service.spec.ts
src/app/services/azure-cost-management/azure-cost-management.service.ts
src/app/services/azure-cost-management/index.ts
src/app/services/azure-http.service.ts
src/common/constants/constants.ts

Fix: Account cost graph by switch to CostManagement Api

---

python/requirements.txt
src/app/components/data/action/add/file-group-create-form.component.ts
src/app/components/pool/base/app-packages/app-package-picker.component.spec.ts
src/app/components/pool/base/app-packages/app-package-picker.component.ts
src/app/components/pool/base/app-packages/app-package-picker.html
src/app/components/pool/base/app-packages/app-package-picker.scss
src/client/python-process/python-rpc-server-process.ts

Fix: Blank values for edit app package references

---

src/app/components/account/details/account-cost-card/account-cost-card.component.ts
src/app/services/azure-cost-management/azure-cost-management.service.spec.ts
src/app/services/azure-cost-management/azure-cost-management.service.ts
src/app/utils/arm-resource-utils/arm-resource-utils.ts

This require to get the price of all elements in the resource group where the batch account is located then filter and aggregate locally.

Internal: Get ready for billing to switch to be at the pool level

---

src/@batch-flask/ui/vtabs/vtab-group.html

fix https://dev.azure.com/azurebatch/BatchExplorer/_workitems/edit/121

Accessibility: Make vtab component use aria

---

src/@batch-flask/ui/buttons/button.component.ts
src/@batch-flask/ui/editor/editor.component.ts
src/@batch-flask/ui/file/file-loader/file-loader.ts
src/@batch-flask/ui/file/file-viewer/file-viewer-container/file-viewer-header/file-viewer-header.component.ts
src/@batch-flask/ui/file/file-viewer/file-viewer-container/file-viewer-header/file-viewer-header.html
src/@batch-flask/ui/file/file-viewer/file-viewer/file-viewer.ts
src/@batch-flask/ui/file/file-viewer/text-file-viewer/text-file-viewer.component.spec.ts
src/@batch-flask/ui/file/file-viewer/text-file-viewer/text-file-viewer.component.ts
src/@batch-flask/ui/file/file-viewer/text-file-viewer/text-file-viewer.html
src/app/components/gallery/local-template-explorer/local-template-explorer.component.ts
src/app/components/gallery/ncj-template-viewer/ncj-template-viewer.component.ts
src/app/components/gallery/ncj-template-viewer/ncj-template-viewer.html
src/app/services/ncj/local-template.service.ts

Feature: Allow live editing of templates in library + save

---

src/app/components/job/browse/job-list.component.ts

Feature: Sort job by creationg time

---

src/@batch-flask/ui/dropdown/dropdown.scss

fix #1914
Seems like the style was applied in different order in prod build than dev

Fix: Pinned dropdown Style

---

src/@batch-flask/utils/date-utils/date-utils.spec.ts
src/app/components/settings/settings.component.ts
src/app/components/settings/settings.html
src/app/components/settings/settings.i18n.yml
src/app/services/github-data/github-data.service.ts
src/app/services/ncj/portfolio/github-portfolio.spec.ts
src/app/services/ncj/portfolio/github-portfolio.ts
src/app/services/ncj/portfolio/portfolio.service.spec.ts
src/app/services/ncj/portfolio/portfolio.service.ts
src/common/be-user-configuration.model.ts

Also split the settings between github data and the microsoft repo

Feature: Point the new azure-extension-templates repo

---

src/app/components/job/browse/job-list.component.ts

Feature: Sort jobs by end time

---

src/@batch-flask/ui/abstract-list/abstract-list-base.ts
src/@batch-flask/ui/abstract-list/partial-sort-warning/partial-sort-warning.component.spec.ts
src/@batch-flask/ui/abstract-list/partial-sort-warning/partial-sort-warning.component.ts
src/@batch-flask/ui/abstract-list/partial-sort-warning/partial-sort-warning.html
src/@batch-flask/ui/quick-list/quick-list.component.spec.ts
src/@batch-flask/ui/table/table.component.ts
src/app/components/job/browse/job-list.component.ts
src/app/components/pool/browse/pool-list.component.ts

Feature: Save last sort order for lists

---

src/@batch-flask/ui/abstract-list/abstract-list-base.ts

Fix: Ctrl click on the list

---

CHANGELOG.md
Readme.md
ThirdPartyNotices.txt
package-lock.json
package.json

Prepare for release 2.0.0

---

src/@batch-flask/ui/metrics-monitor/metrics-monitor.scss
src/@batch-flask/ui/vtabs/vtab-group.component.spec.ts
src/@batch-flask/ui/vtabs/vtab-group.html
src/app/components/job-schedule/details/job-schedule-details.component.ts
src/app/components/job-schedule/details/job-schedule-details.html

Fix: VTabComponent null pointer exception when current tab is null

---

src/app/components/gallery/local-template-explorer/local-template-pick-button/local-template-pick-button.component.spec.ts
src/app/components/gallery/local-template-explorer/local-template-pick-button/local-template-pick-button.component.ts
src/app/components/pool/graphs/heatmap/nodes-heatmap.component.ts

Fix: Open a local template can return undefined

---

CHANGELOG.md
package-lock.json
package.json
src/@batch-flask/core/data/entity-getter/entity-getter.spec.ts
src/@batch-flask/core/data/entity-view/entity-view.spec.ts
src/@batch-flask/core/data/generic-view.ts
src/@batch-flask/core/data/list-getter/list-getter.spec.ts
src/@batch-flask/core/data/list-view/list-view.spec.ts
src/@batch-flask/core/data/list-view/list-view.ts
src/@batch-flask/core/data/test/fake-model.ts
src/@batch-flask/ui/abstract-list/abstract-list-base.ts
src/@batch-flask/ui/file/file-loader/file-loader.ts
src/@batch-flask/ui/file/file-viewer/file-viewer-container/file-viewer-header/file-viewer-header.component.ts
src/@batch-flask/ui/file/file-viewer/file-viewer-container/file-viewer-header/file-viewer-header.html
src/app/models/azure-batch/node/node.ts

Fix: Null route segement on navigating on quick list too fast

---

CHANGELOG.md
package-lock.json
package.json
src/@batch-flask/ui/property-list/table-property/table-property.component.ts
src/app/components/common/resource-files-properties/resource-files-properties.component.spec.ts
src/app/components/common/resource-files-properties/resource-files-properties.html
src/app/models/multi-instance-settings.ts

Fix:: Resource file properties when files are null

---

CHANGELOG.md
src/app/services/azure-batch/pool-node-count/pool-node-count.service.spec.ts
src/app/services/azure-batch/pool-node-count/pool-node-count.service.ts
src/app/services/batch-account/arm-batch-account.service.ts
src/app/services/batch-account/batch-account.service.ts

Fix: Node counts recover from error

---

CHANGELOG.md
src/app/services/authorization-http/authorization-http.service.ts

Fix: Permission update when changing batch account 

---

src/app/components/gallery/submit/submit-ncj-template.component.spec.ts

Fix test warning in submit-ncj-template.spec due to undefined observable in poolPicker combineLatest

Fix test warning

---

src/@batch-flask/ui/time-range-picker/time-range-picker.component.ts
src/@batch-flask/ui/time-range-picker/time-range-picker.html
src/@batch-flask/ui/time-range-picker/time-range.model.ts
src/app/components/account/details/account-cost-card/account-cost-card.component.spec.ts
src/app/components/account/details/account-cost-card/account-cost-card.component.ts
src/app/components/account/details/account-cost-card/account-cost-card.html
src/app/components/account/details/account-cost-card/account-cost-card.i18n.yml
src/app/components/account/details/account-cost-card/account-cost-card.scss
src/app/components/pool/details/pool-cost-card/index.ts
src/app/components/pool/details/pool-cost-card/pool-cost-card.component.spec.ts
src/app/components/pool/details/pool-cost-card/pool-cost-card.component.ts
src/app/components/pool/details/pool-cost-card/pool-cost-card.html
src/app/components/pool/details/pool-cost-card/pool-cost-card.scss
src/app/components/pool/details/pool-details.html
src/app/components/pool/details/pool-details.module.ts
src/app/components/pool/details/pool-details.scss
src/app/components/pool/graphs/pool-state-graph/pool-state-graph.scss
src/app/services/azure-cost-management/azure-cost-management.service.spec.ts
src/app/services/azure-cost-management/azure-cost-management.service.ts
src/app/services/azure-cost-management/azure-cost-mangement-api.model.ts
src/common/constants/constants.ts

fix #1993 
Also updated account dashboard to split prices per pool instead of meters

Feature: Show pool price history

---

CHANGELOG.md
src/app/components/settings/settings.component.spec.ts
src/app/components/settings/settings.component.ts
src/app/services/ncj/ncj-template.service.ts

Fix: Microsoft portfolio setting not persisted

---

src/app/components/account/account.module.ts
src/app/components/account/action/account-commands.ts
src/app/components/account/action/add/edit-local-batch-account.component.ts
src/app/components/account/action/add/index.ts
src/app/components/account/details/account-summary-card/account-summary-card.component.spec.ts
src/app/services/batch-account/local-batch-account.service.ts

Feature: Edit local batch account

---

src/@batch-flask/core/commands/keybindings/keybindings.service.ts

Fix: Keyboard binding reset when leaving the window

---

src/app/components/job/browse/job-list.component.ts

Fix: Job created via NCJ added to the end of the list

---

src/app/models/cloud-service-configuration.ts
src/app/utils/pool-utils.spec.ts
src/app/utils/pool-utils.ts

Now that this is fully deployed add in constants to mirror other CS versions
Are there tests I need to run or do you trust me?

Update constants to include CS6

---

CHANGELOG.md
ThirdPartyNotices.txt
package-lock.json
package.json

Prepare for release 2.1.0

---

.vscode/settings.json
CHANGELOG.md
package-lock.json
package.json
src/app/components/job/action/add/pool-picker/pool-picker.component.spec.ts
src/app/components/job/action/add/pool-picker/pool-picker.component.ts

Fix: Pool picker not listing pools

---

CHANGELOG.md
package.json
src/app/components/node/connect/node-connect.component.spec.ts
src/app/components/node/connect/node-connect.component.ts

Fix: Connect to node as admin

---

CHANGELOG.md
src/app/models/azure-batch/task/task.spec.ts
src/app/models/azure-batch/task/task.ts

Fix stort task by runtime

---

src/app/components/gallery/application-action/choose-action.component.ts
src/app/components/gallery/home/gallery.component.ts
src/app/components/gallery/home/gallery.html
src/common/constants/constants.ts

Links now also honor the settings overrides for repo, branch and path

Fix gallery readme and template links to target batch-extension-templates

---

src/client/proxy/manual-proxy-configuration-window/manual-proxy-configuration-window.html
src/client/proxy/proxy-credentials-window/proxy-credentials.html

Fix: Make password field a password type for the proxy creds window

---

src/app/components/account/details/programatic-usage/programing-sample/samples/aad/python.py.template
src/app/components/account/details/programatic-usage/programing-sample/samples/shared-key/python.py.template

Update python samples to be compatible with latest SDK

---

src/app/services/quota.service.ts

Service definition of job quota is all jobs not completed (basically anything which can go back into an active state counts against quota).

Update job quota to reflect service side definition of quota

---

src/app/services/batch-account/arm-batch-account.service.ts

fix #2044 
This ensure that if it fail to load batch accounts for 1 subscription it will still update with all the other subscription accounts.

Ignore errors when listing batch accounts 

---

src/app/services/pricing.service.ts
src/app/services/pricing/pricing.model.ts

Monitor promo pricing

---

src/app/components/pool/action/add/os-picker/custom-image-picker/custom-image-picker.component.spec.ts
src/app/components/pool/action/add/os-picker/custom-image-picker/custom-image-picker.component.ts
src/app/models/image-reference.ts
src/app/services/compute.service.ts
src/common/constants/constants.ts

Add SharedImageGallery to custom images blade

---

src/app/components/task/browse/task-list.component.ts

Stop setting options to base on refresh to allow filter retention

---

CHANGELOG.md
ThirdPartyNotices.txt
package-lock.json
package.json

Prepare for release 2.3.0

---

src/app/components/job/details/job-configuration.html

Fix Missing Job Execution Information

---

src/@batch-flask/ui/duration-picker/duration-picker.component.spec.ts
src/@batch-flask/ui/duration-picker/duration-picker.component.ts
src/app/components/job/action/add/job-manager-task-picker.html
src/app/components/job/action/add/job-preparation-task-picker.html
src/app/components/job/action/add/job-release-task-picker.html
src/app/components/task/action/add/add-task-form.html

Change retention time default and eliminate auto-infinity

---

CHANGELOG.md
ThirdPartyNotices.txt
package-lock.json
package.json
src/@batch-flask/ui/file/file-explorer/file-table-view/file-path-navigator/file-path-navigator.component.spec.ts

Release/prepare 2.4.0

---

src/@batch-flask/ui/duration-picker/duration-picker.component.ts
src/app/components/job/action/add/job-preparation-task-picker.component.ts
src/app/components/job/action/add/job-preparation-task-picker.html
src/app/components/job/action/add/job-release-task-picker.component.ts
src/app/components/job/action/add/job-release-task-picker.html
src/app/components/job/action/add/job-task-base.component.ts
src/app/components/node/connect/node-connect.component.spec.ts
src/app/components/node/connect/node-connect.component.ts

Fix duration picker bugs

---

src/@batch-flask/ui/banner/banner.html

Fixed issue with caret toggling for the pool error details.

Fix caret toggling for error display

---

src/@batch-flask/core/constants.ts
src/@batch-flask/core/record/decorators.ts
src/@batch-flask/ui/duration-picker/duration-picker.component.ts
src/@batch-flask/ui/duration-picker/duration-picker.html
src/app/components/pool/action/add/os-picker/os-image-picker/os-image-picker.component.spec.ts
src/app/components/pool/start-task/start-task-picker.component.spec.ts
src/app/models/constraints.ts
src/app/models/task-constraints.ts

Set error message for when the duration value chosen for retentionTime and/or maxWallClockTime exceeds the DateTime maximum in the backend.

Error Message Duration Exceed Maximum

---

src/app/components/account/action/create/batch-account-create.component.spec.ts
src/app/components/account/action/create/batch-account-create.component.ts
src/app/models/forms/create-account-model.ts
src/app/services/batch-account/arm-batch-account.service.ts

Fix account create bug

---

src/@batch-flask/core/data/list-getter/list-getter.ts

Update list fetch to follow empty responses

---

CHANGELOG.md
ThirdPartyNotices.txt
package-lock.json
package.json
python/requirements.txt

Prepare for release 2.5.0

---

package-lock.json
package.json

* Need to fix package tree-kill dependency - will be in a different PR

Fixed 3 security vulnerabilities

---

python/requirements.txt

Updated pyinstaller to fix GitHub security vulnerability.

Updated pyinstaller to 3.6

---

CHANGELOG.md
ThirdPartyNotices.txt
package-lock.json
package.json
scripts/publish/publish.ts

Prepare for release 2.7.0

---

.vsts/win/sign.yml

This reverts commit ecf7d69f04e7940459773dcf4e879444c6b001fd.

Revert "Update signing yml (#2167)"

---

assets/style.css
index.html
insider.html

Fixed color contrast issues for both `index.html` and `insider.html`.
`index.html`
**Before**:
**After**:
`insider.html`
**Before**:
**After**:

BE Download Page - Color Contrast Accessibility Bug fixes

---

index.html
insider.html

Added alternative text for links and images for screen readers.
* Small fix: color contrast issues

BE Download Page - Fix image-alt and link-name issues

---

.vsts/darwin/ci.yml
.vsts/darwin/darwin-dependencies.yml
.vsts/darwin/distribution.yml
.vsts/dependencies.yml
.vsts/distribution.yml
.vsts/linux/ci.yml
.vsts/linux/distribution.yml
.vsts/linux/linux-dependencies.yml
.vsts/pipelines.yml
.vsts/pyenv.yml
.vsts/update-en-loc.yml
.vsts/win/distribution.yml
.vsts/win/win-dependencies.yml
package-lock.json
package.json

- Remove Python 2
- Upgrade to Node 12
- Ubuntu 16 -> 18
- MacOS 10.14 => 10.15
- Added a Python 3 venv for Linux/MacOS
- Replace electron-rebuild with electron-builder

Build pipeline updates

---

config/webpack.config.base.js
package-lock.json
package.json

This addresses a security vulnerability in 'serialize-javascript'

Updated copy-webpack-plugin dependency

---

src/app/components/job/action/add/add-job-form.html

Fixed spelling error

---

src/app/components/task/details/sub-tasks/properties/sub-task-properties.component.ts
src/app/components/task/details/sub-tasks/properties/sub-task-properties.html

Fixed field indicated by red arrow:
Original issue:

Fixed issue with displaying detail information on sub task blade

---

.vsts/update-en-loc.yml

This fixes the localization CI pipeline

Updated localization CI user

---

src/app/components/node/browse/node-list.component.ts

This allows multi-select deletion (and matches other left-hand lists like the pools list)

Added delete button to left-hand node list

---

CHANGELOG.md
ThirdPartyNotices.txt
package-lock.json
package.json

Prepare for release 2.8.0

---

src/app/components/pool/network-configuration/virtual-network-picker/virtual-network-picker.component.ts
src/app/services/network/network-configuration.service.ts
tslint.json

Hotfix for classic vnet not found issue

---

src/app/components/layout/footer/rpc-server-status/rpc-server-status.component.spec.ts
src/app/components/layout/footer/rpc-server-status/rpc-server-status.component.ts

fix [#2267](https://github.com/Azure/BatchExplorer/issues/2267)

Fixed typo in the connection status label

---

src/@batch-flask/ui/file/file-explorer/file-explorer-tabs/file-explorer-tabs.html
src/@batch-flask/ui/file/file-explorer/file-table-view/file-table-view.html
src/@batch-flask/ui/form/complex-form/footer/form-footer.html
src/@batch-flask/ui/property-list/table-property/table-property.component.spec.ts
src/@batch-flask/ui/property-list/table-property/table-property.component.ts
src/@batch-flask/ui/property-list/table-property/table-property.html
src/@batch-flask/ui/property-list/table-property/table-property.scss
src/@batch-flask/ui/server-error/server-error.html
src/app/components/account/details/account-monitoring-section/account-monitoring-section.html
src/app/components/account/monitoring/account-monitoring.i18n.yml
src/app/components/gallery/application-action/choose-action.html

Addresses high-severity accessibility issues.

---

CHANGELOG.md
ThirdPartyNotices.txt
package-lock.json
package.json

Prepare for release 2.9.0

---

src/app/components/gallery/home/gallery.component.ts
src/app/components/gallery/home/gallery.html
src/app/components/gallery/home/gallery.scss
src/app/components/pool/action/add/app-license-picker/app-license-picker.component.ts
src/app/components/pool/action/add/app-license-picker/app-license-picker.html
src/app/components/pool/action/add/app-license-picker/app-license-picker.scss
src/app/components/pool/action/add/pool-create-basic-dialog.component.ts
src/app/components/pool/action/add/pool-create-basic-dialog.html
src/app/components/pool/action/add/pool-create-basic-dialog.scss

The following are screenshots for deprecation warnings in class, dark, and high contrast themes:

Deprecation warnings for cloud service pools, graphics and rendering images, and pay-for-use licensing

---

CHANGELOG.md
ThirdPartyNotices.txt
package-lock.json
package.json
scripts/publish/publish.ts

Prepare for release 2.10.0

---

package-lock.json
package.json

* `azure-storage` 
* some other lower-severity nested dependencies

Fixes high-severity component issues

---

package-lock.json
src/app/components/pool/action/add/vm-size-picker/vm-size-picker.component.ts

Updated VM size categories with FPGA. Also includes minor npm audit fixes.

Add fpga to vm size categories

---

package-lock.json
package.json
src/@batch-flask/ui/buttons/button.component.spec.ts
src/@batch-flask/ui/buttons/button.html

Tooltip now collapses when esc key is pressed during hover.

Fix tooltip doesn't close with esc key

---

src/app/components/pool/action/add/pool-create-basic-dialog.component.ts
src/app/components/pool/action/add/pool-create-basic-dialog.html

Only show when a Cloud Services image is selected
Screenshots:

Dynamically show/hide cloud services deprecation warning

---

package-lock.json
package.json
src/client/core/aad/aad-constants.ts
src/client/core/aad/auth-provider.ts
src/client/core/aad/auth/aad.service.ts

Fix: Unable to log in with personal (MSA) accounts

---

.stylelintrc.json

Renames unit-blacklist -> unit-disallowed-list

Fix stylelint deprecation warning

---

package.json
scripts/publish/publish.ts

* Creates merge branch for bumping version in package.json and merging stable back into master (subsequent manual step).
* Manually bumped version for insider builds.
Closes #2338

Publish script bumps version post-release

---

src/@batch-flask/ui/browse-layout/browse-layout.html
src/@batch-flask/ui/buttons/button.scss
src/@batch-flask/ui/buttons/refresh-btn/refresh-btn.component.ts
src/@batch-flask/ui/buttons/refresh-btn/refresh-btn.html
src/@batch-flask/ui/property-list/entity-configuration/entity-configuration.html
src/app/components/account/action/edit-storage-account/edit-storage-account-form.html
src/app/components/account/details/account-summary-card/account-summary-card.html
src/app/components/account/details/programatic-usage/programing-sample/programing-sample.html
src/app/styles/vendor/material-theme.scss
src/client/proxy/manual-proxy-configuration-window/manual-proxy-configuration-window.html

October accessibility bug fixes including fixes for focus order, focus visual indicator, role updates for screen reader, tooltip overlap on hover, and placeholder suggestions for editable fields.

October a11y bug fixes

---

CHANGELOG.md
ThirdPartyNotices.txt

Prepare for release 2.12.0

---

.vsts/update-en-loc.yml

Using Ubuntu 20.04 for localization build

Updating localization build image to Ubuntu 20.04

---

CHANGELOG.md
package.json

Updating the patch version for reverting changes to using VM SKU API.

[Hotfix] Update Patch Version

---

src/app/components/pool/graphs/heatmap/nodes-heatmap.component.spec.ts
src/app/components/pool/graphs/heatmap/nodes-heatmap.component.ts
src/app/polyfills.browser.ts

- Update heatmap node height calculations for `requiredSlots`
- Update heatmap node tooltip display to include `taskSlotsCount / taskSlotsPerNode`
- Naming update from `task` to `taskSlots`

[Fix] Update heatmap node height calculations

---

data/themes/classic.json
src/@batch-flask/ui/buttons/button.scss
src/@batch-flask/ui/notifications/toast/toast.scss
src/app/components/account/browse/account-list/account-list.scss
src/app/components/layout/header/header.html
src/app/components/layout/header/header.scss
src/client/proxy/manual-proxy-configuration-window/manual-proxy-configuration-window.css
src/client/proxy/manual-proxy-configuration-window/manual-proxy-configuration-window.html

February accessibility bug fixes include several improvements on luminosity contrast ratios for buttons and icons. Also the back/forward button is now accessible through keyboard navigation (before these buttons were skipped on keyboard navigation and only accessible through mouse clicks).

February a11y Bug Fixes

---

CHANGELOG.md
ThirdPartyNotices.txt

Prepare for release 2.13.0

---

package-lock.json
package.json

Possibly addresses issues with Conditional Access policies that require a minimum Chromium version of 91. (#2446)

Upgrades to Electron 13

---

EULA.html
index.html
insider.html

Fixes [AB#646](https://azurebatch.visualstudio.com/3426cbfe-4c9a-4da4-88df-70f025a77017/_workitems/edit/646)

Added landmarks to website

---

package-lock.json
package.json
src/client/core/aad/auth-provider.spec.ts
src/client/core/aad/auth-provider.ts

Batch Explorer would not start when an exception is thrown during silent auth that isn't an authentication error.

Fixes issue with failed silent auth

---

util/build-util/__mocks__/inquirer.ts
util/build-util/__mocks__/shelljs.ts
util/build-util/__tests__/cli.spec.ts
util/build-util/jest.config.js
util/build-util/package-lock.json
util/build-util/package.json
util/build-util/tsconfig.json

Limited by Jest's lack of support for ES modules.

Basic CLI test

---

src/client/main-window/main-window.ts

In-release regression caused by upgrade to Electron 13 (3bd43c756).

Restores native menubar on Windows

---

.editorconfig
.vscode/launch.json
package-lock.json
package.json
scripts/proxy/initProxyServer.sh
scripts/proxy/initVirtualMachine.ps1
scripts/proxy/main.bicep
scripts/proxy/peering.bicep
scripts/proxy/proxy-deployment.bicep
scripts/proxy/proxy-server.bicep
scripts/proxy/readme.md
scripts/proxy/virtual-machine.bicep
scripts/proxy/vpn-peerings.bicep
src/client/core/aad/auth-provider.ts
src/client/proxy/proxy-settings.ts

Handles [issue with MSAL auth code flow](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2600) when a proxy is present. Uses the configured Batch Explorer proxy settings to pass to the AAD client. Currently, proxy credentials are not supported by a limitation of MSAL.
PR includes an Azure deployment for creating a proxied environment for Batch Explorer.
Fixes #2350.

Improved proxy support with MSAL authentication

---

packages/playground/src/ui-playground/demo/form/checkbox/new-checkbox-demo.tsx
packages/playground/src/ui-playground/demo/form/radiobutton/radiobutton-demo.tsx
packages/playground/src/ui-playground/layout/demo-main-content.tsx
packages/playground/src/ui-playground/layout/demo-nav-menu.tsx
packages/playground/src/ui-playground/new-functions.tsx
packages/react/src/ui-react/components/form/__tests__/checkbox.spec.tsx
packages/react/src/ui-react/components/form/__tests__/radio-button.spec.tsx
packages/react/src/ui-react/components/form/checkbox.tsx
packages/react/src/ui-react/components/form/radio-button.tsx

[Checkbox control work item](https://msazure.visualstudio.com/AzureBatch/_workitems/edit/14215432/)
- Added wrapped checkbox form control, unit tests for it, & integrated it into the playground
[Radio button group control work item](https://msazure.visualstudio.com/AzureBatch/_workitems/edit/14215411/)
- Added wrapped radio button form control, unit tests for it, & integrated it into the playground

Added checkbox and radio button group form controls

---

src/app/components/account/details/programatic-usage/programing-sample/programing-sample.html
src/app/components/job/action/add/add-job-form.html
src/app/components/job/graphs/all-job-graphs-home/all-job-graphs-home.html

May accessibility bug fixes include improvements on screen reader announcing correct retry counts, accessing graphs through tabbing, and including correct labels for controls.

May a11y Bug Fixes

---

src/@batch-flask/ui/select/select.html
src/@batch-flask/ui/sidebar/sidebar-bookmarks/sidebar-bookmarks.html
src/app/components/account/details/account-monitoring-section/account-monitoring-section.html
src/app/components/account/details/account-summary-card/account-summary-card.html
src/app/components/job/action/add/add-job-form.html
src/app/components/job/action/add/add-job-form.scss

Merge June accessibility bug fixes into master branch

Add June Accessibility Bug Fixes

---

CHANGELOG.md
ThirdPartyNotices.txt

Prepare for release 2.15.0

---

CHANGELOG.md
package.json

Bumps Batch Explorer to v2.16.0

Merges stable into master

---

src/@batch-flask/ui/buttons/button.scss
src/@batch-flask/ui/buttons/clickable/clickable.scss
src/@batch-flask/ui/notifications/toast/toast.scss
src/@batch-flask/ui/sidebar/sidebar-content/sidebar-content.scss
src/app/components/account/details/account-monitoring-section/account-monitoring-section.html
src/app/components/pool/action/add/os-picker/os-offer-tile/os-offer-tile.html
src/app/components/pool/action/add/os-picker/os-offer-tile/os-offer-tile.i18n.yml
src/app/components/pool/action/add/os-picker/pool-os-picker.module.ts
src/app/styles/vendor/material-theme.scss

Mostly, but not all, related to High-Contrast Mode.

Accessibility Fixes

---

src/app/components/pool/action/add/pool-create-basic-dialog.html

Add deprecation warning for Windows container images

---

src/client/menu/help-menu.ts
src/client/menu/main-menu.i18n.yml
src/common/constants/constants.ts

This will show for all languages.
Example:

Add Italy Accessibility Declarations Link to Batch Explorer

---

index.html
insider.html

Add Italy accessibility declaration link to web in footer

---

python/requirements.txt

Fixes [AB#1013](https://azurebatch.visualstudio.com/3426cbfe-4c9a-4da4-88df-70f025a77017/_workitems/edit/1013)

Upgrades Batch PIP modules

---

desktop/package-lock.json
desktop/package.json
util/bux/package-lock.json

This resolves one packaging issue where mkdirp wasn't included

Add mkdirp as an explicit dependency of desktop

---

src/@batch-flask/core/html-util/focus-helper.spec.ts
src/@batch-flask/core/html-util/focus-helper.ts
src/@batch-flask/core/html-util/index.ts
src/@batch-flask/core/index.ts
src/@batch-flask/ui/buttons/clickable/clickable.component.spec.ts
src/@batch-flask/ui/callout/callout.directive.spec.ts
src/@batch-flask/ui/callout/callout.directive.ts
src/@batch-flask/ui/callout/callout.html
src/@batch-flask/ui/datetime-picker/datetime-picker.html
src/@batch-flask/ui/form/form-field/form-field.html
src/@batch-flask/ui/form/form-field/form-field.scss
src/app/components/account/monitoring/monitor-chart/monitor-chart.component.ts
src/app/components/account/monitoring/monitor-chart/monitor-chart.html
src/app/components/job-schedule/action/add/job-schedule-create-basic-dialog.html
src/app/components/pool/action/add/os-picker/os-offer-tile/os-offer-tile.html
src/app/components/pool/action/add/pool-create-basic-dialog.html

Fixes:
[AB#446](https://azurebatch.visualstudio.com/3426cbfe-4c9a-4da4-88df-70f025a77017/_workitems/edit/446)
[AB#451](https://azurebatch.visualstudio.com/3426cbfe-4c9a-4da4-88df-70f025a77017/_workitems/edit/451)
[AB#452](https://azurebatch.visualstudio.com/3426cbfe-4c9a-4da4-88df-70f025a77017/_workitems/edit/452)
[AB#453](https://azurebatch.visualstudio.com/3426cbfe-4c9a-4da4-88df-70f025a77017/_workitems/edit/453)
[AB#996](https://azurebatch.visualstudio.com/3426cbfe-4c9a-4da4-88df-70f025a77017/_workitems/edit/996)

Several a11y bug fixes

---

desktop/src/@batch-flask/core/batch-explorer-http-client.ts
packages/common/src/ui-common/__tests__/setup-tests.ts
packages/common/src/ui-common/http/__tests__/fetch-http-client.spec.ts
packages/common/src/ui-common/http/__tests__/http-util.spec.ts
packages/common/src/ui-common/http/__tests__/map-http-headers.spec.ts
packages/common/src/ui-common/http/__tests__/mock-http-client.spec.ts
packages/common/src/ui-common/http/fetch-http-client.ts
packages/common/src/ui-common/http/http-client.ts
packages/common/src/ui-common/http/index.ts
packages/common/src/ui-common/http/map-http-headers.ts
packages/common/src/ui-common/http/mock-http-client.ts
packages/common/src/ui-common/index.ts
packages/service/src/ui-service/certificate/__tests__/certificate-service.spec.ts
packages/service/src/ui-service/certificate/certificate-list-view.ts
packages/service/src/ui-service/storage/__tests__/storage-account-service.spec.ts
packages/service/src/ui-service/subscription/__tests__/subscription-service.spec.ts

- Added support for request bodies
- Added unit tests for FetchHttpClient
- Added support for blobs and ArrayBuffers on responses
- Reworked MockHttpClient function signatures
- Renamed MockHttpHeaders to MapHttpHeaders

Shared library HttpClient improvements

---

desktop/package-lock.json
package.json
packages/common/package-lock.json
packages/playground/package-lock.json
packages/react/package-lock.json
packages/service/package-lock.json
util/bux/package-lock.json
util/common-config/package-lock.json
web/package-lock.json

Removing this was causing multiple versions of React to be used

Readd --legacy-peer-deps to bootstrap call

---

data/themes/classic.json
src/@batch-flask/ui/list-and-show-layout/entity-details-list.html
src/@batch-flask/ui/property-list/link-property/link-property.component.ts
src/@batch-flask/ui/property-list/property-content/property-content.component.ts
src/app/components/pool/action/add/os-picker/os-offer-tile/os-offer-tile.html
src/app/components/pool/graphs/pool-state-graph/pool-state-graph.component.ts

Accessibility bug fixes

---

packages/readme.md

Add bux installation instructions and minor fix

Minor readme update

---

CHANGELOG.md
ThirdPartyNotices.txt
scripts/lca/default-licenses/mit.txt
scripts/lca/generate-third-party.ts

Prepare for release 2.16.0

---

src/app/services/themes/theme.service.ts

Removing folder where customers can add custom themes.

Remove custom themes

---

Localize/loc/cs/desktop/i18n/resources.resjson.lcl
Localize/loc/de/desktop/i18n/resources.resjson.lcl
Localize/loc/es/desktop/i18n/resources.resjson.lcl
Localize/loc/fr/desktop/i18n/resources.resjson.lcl
Localize/loc/hu/desktop/i18n/resources.resjson.lcl
Localize/loc/it/desktop/i18n/resources.resjson.lcl
Localize/loc/ja/desktop/i18n/resources.resjson.lcl
Localize/loc/ko/desktop/i18n/resources.resjson.lcl
Localize/loc/nl/desktop/i18n/resources.resjson.lcl
Localize/loc/pl/desktop/i18n/resources.resjson.lcl
Localize/loc/pt-BR/desktop/i18n/resources.resjson.lcl
Localize/loc/pt-PT/desktop/i18n/resources.resjson.lcl
Localize/loc/ru/desktop/i18n/resources.resjson.lcl
Localize/loc/sv/desktop/i18n/resources.resjson.lcl
Localize/loc/tr/desktop/i18n/resources.resjson.lcl
Localize/loc/zh-Hans/desktop/i18n/resources.resjson.lcl
Localize/loc/zh-Hant/desktop/i18n/resources.resjson.lcl

- Add translations that we have so far to the **desktop** app that can be re-used
- Creating this PR on behalf of Daniel from the localization team
For more context, please see: [https://dev.azure.com/ceapex/CEINTL/_workitems/edit/789905?src=WorkItemMention&src-action=artifact_link](https://dev.azure.com/ceapex/CEINTL/_workitems/edit/789905?src=WorkItemMention&src-action=artifact_link)

Add reusable loc translations from loc team

---

src/app/components/pool/action/add/pool-create-basic-dialog.html
src/app/components/pool/details/pool-details.component.ts
src/app/components/pool/details/pool-details.html
src/app/utils/pool-utils.ts

Add deprecation warning on pool details for cloud service pools.

Cloud Service Deprecation Warning on Pool Details

---

package-lock.json
package.json
patches/@azure+core-http+2.2.7.patch
src/app/components/application/action/create/application-create-dialog.component.spec.ts
src/app/components/application/action/create/application-create-dialog.component.ts
src/app/services/storage/storage-blob.service.ts
src/client/core/storage/storage-blob-adapter.spec.ts

fix @azure/storage-blob usage

---

CHANGELOG.md
ThirdPartyNotices.txt

Prepare for release 2.17.0

---

desktop/src/@batch-flask/ui/buttons/button.component.spec.ts
desktop/src/@batch-flask/ui/buttons/button.component.ts
desktop/src/@batch-flask/ui/buttons/button.html
desktop/src/@batch-flask/ui/buttons/button.scss
desktop/src/@batch-flask/ui/buttons/clickable/clickable.component.ts
desktop/src/@batch-flask/ui/form/editable-table/editable-table.component.ts
desktop/src/@batch-flask/ui/form/editable-table/editable-table.html
desktop/src/@batch-flask/ui/metrics-monitor/metrics-monitor.scss
desktop/src/@batch-flask/ui/quotas/quota-display/quota-display.scss
desktop/src/@batch-flask/ui/tags/tag-list/tag-list.scss
desktop/src/@batch-flask/ui/toolbar/toolbar.scss
desktop/src/app/components/gallery/application-list/gallery-application-list.html
desktop/src/app/components/gallery/application-list/gallery-application-list.scss
desktop/src/app/components/layout/pinned-entity-dropdown/pinned-dropdown.html
desktop/src/app/components/pool/action/add/app-license-picker/app-license-picker.scss
desktop/src/app/components/pool/action/add/vm-size-picker/vm-size-picker.component.ts
desktop/src/app/components/pool/action/add/vm-size-picker/vm-size-picker.html
desktop/src/app/models/vm-size.ts
desktop/src/app/styles/variables.scss

In preparation for cutover to `main` as default branch.

Merges latest changes from master into main

---

Localize/loc/cs/desktop/i18n/resources.resjson.lcl
Localize/loc/de/desktop/i18n/resources.resjson.lcl
Localize/loc/es/desktop/i18n/resources.resjson.lcl
Localize/loc/fr/desktop/i18n/resources.resjson.lcl
Localize/loc/hu/desktop/i18n/resources.resjson.lcl
Localize/loc/id/desktop/i18n/resources.resjson.lcl
Localize/loc/it/desktop/i18n/resources.resjson.lcl
Localize/loc/ja/desktop/i18n/resources.resjson.lcl
Localize/loc/ko/desktop/i18n/resources.resjson.lcl
Localize/loc/nl/desktop/i18n/resources.resjson.lcl
Localize/loc/pl/desktop/i18n/resources.resjson.lcl
Localize/loc/pt-BR/desktop/i18n/resources.resjson.lcl
Localize/loc/pt-PT/desktop/i18n/resources.resjson.lcl
Localize/loc/ru/desktop/i18n/resources.resjson.lcl
Localize/loc/sv/desktop/i18n/resources.resjson.lcl
Localize/loc/tr/desktop/i18n/resources.resjson.lcl
Localize/loc/zh-Hans/desktop/i18n/resources.resjson.lcl
Localize/loc/zh-Hant/desktop/i18n/resources.resjson.lcl

LEGO: Pull request from users/loc/juno/hb_b5190a78-9093-45f2-826d-2cc1e04cb56a_20230519161655655 to main with localized lcls

LEGO: Pull request from users/loc/juno/hb_b5190a78-9093-45f2-826d-2cc1e04cb56a_20230519161655655 to main

---

desktop/src/@batch-flask/core/data/list-view/list-view.spec.ts
desktop/src/@batch-flask/core/data/list-view/list-view.ts
desktop/src/app/services/azure-batch/pool/pool.service.ts

Component incorrectly determined cached parameters to ensure items are replaced and not appended.

Fixes #2732: Only pools for selected account are shown

---

Localize/loc/es/desktop/i18n/resources.resjson.lcl
Localize/loc/tr/desktop/i18n/resources.resjson.lcl

LEGO: Pull request from users/loc/juno/hb_b5190a78-9093-45f2-826d-2cc1e04cb56a_20230530141000859 to main with localized lcls

LEGO: Pull request from users/loc/juno/hb_b5190a78-9093-45f2-826d-2cc1e04cb56a_20230530141000859 to main

---

Localize/loc/cs/desktop/i18n/resources.resjson.lcl
Localize/loc/de/desktop/i18n/resources.resjson.lcl
Localize/loc/es/desktop/i18n/resources.resjson.lcl
Localize/loc/fr/desktop/i18n/resources.resjson.lcl
Localize/loc/hu/desktop/i18n/resources.resjson.lcl
Localize/loc/id/desktop/i18n/resources.resjson.lcl
Localize/loc/it/desktop/i18n/resources.resjson.lcl
Localize/loc/ja/desktop/i18n/resources.resjson.lcl
Localize/loc/ko/desktop/i18n/resources.resjson.lcl
Localize/loc/nl/desktop/i18n/resources.resjson.lcl
Localize/loc/pl/desktop/i18n/resources.resjson.lcl
Localize/loc/pt-BR/desktop/i18n/resources.resjson.lcl
Localize/loc/pt-PT/desktop/i18n/resources.resjson.lcl
Localize/loc/ru/desktop/i18n/resources.resjson.lcl
Localize/loc/sv/desktop/i18n/resources.resjson.lcl
Localize/loc/tr/desktop/i18n/resources.resjson.lcl
Localize/loc/zh-Hans/desktop/i18n/resources.resjson.lcl
Localize/loc/zh-Hant/desktop/i18n/resources.resjson.lcl

LEGO: Pull request from users/loc/juno/hb_b5190a78-9093-45f2-826d-2cc1e04cb56a_20230602160658800 to main with localized lcls

LEGO: Pull request from users/loc/juno/hb_b5190a78-9093-45f2-826d-2cc1e04cb56a_20230602160658800 to main

---

packages/common/src/ui-common/logging/__tests__/logging-util.spec.ts

Closes a couple very minor testing gaps in the logger tests.

Add more mock logger tests

---

Localize/loc/cs/desktop/i18n/resources.resjson.lcl
Localize/loc/de/desktop/i18n/resources.resjson.lcl
Localize/loc/es/desktop/i18n/resources.resjson.lcl
Localize/loc/fr/desktop/i18n/resources.resjson.lcl
Localize/loc/hu/desktop/i18n/resources.resjson.lcl
Localize/loc/id/desktop/i18n/resources.resjson.lcl
Localize/loc/it/desktop/i18n/resources.resjson.lcl
Localize/loc/ja/desktop/i18n/resources.resjson.lcl
Localize/loc/ko/desktop/i18n/resources.resjson.lcl
Localize/loc/nl/desktop/i18n/resources.resjson.lcl
Localize/loc/pl/desktop/i18n/resources.resjson.lcl
Localize/loc/pt-BR/desktop/i18n/resources.resjson.lcl
Localize/loc/pt-PT/desktop/i18n/resources.resjson.lcl
Localize/loc/ru/desktop/i18n/resources.resjson.lcl
Localize/loc/sv/desktop/i18n/resources.resjson.lcl
Localize/loc/tr/desktop/i18n/resources.resjson.lcl
Localize/loc/zh-Hans/desktop/i18n/resources.resjson.lcl
Localize/loc/zh-Hant/desktop/i18n/resources.resjson.lcl

LEGO: Pull request from users/loc/juno/hb_b5190a78-9093-45f2-826d-2cc1e04cb56a_20230609170125312 to main with localized lcls

LEGO: Pull request from users/loc/juno/hb_b5190a78-9093-45f2-826d-2cc1e04cb56a_20230609170125312 to main

---

Localize/loc/cs/desktop/i18n/resources.resjson.lcl
Localize/loc/de/desktop/i18n/resources.resjson.lcl
Localize/loc/es/desktop/i18n/resources.resjson.lcl
Localize/loc/fr/desktop/i18n/resources.resjson.lcl
Localize/loc/hu/desktop/i18n/resources.resjson.lcl
Localize/loc/id/desktop/i18n/resources.resjson.lcl
Localize/loc/it/desktop/i18n/resources.resjson.lcl
Localize/loc/ja/desktop/i18n/resources.resjson.lcl
Localize/loc/ko/desktop/i18n/resources.resjson.lcl
Localize/loc/nl/desktop/i18n/resources.resjson.lcl
Localize/loc/pl/desktop/i18n/resources.resjson.lcl
Localize/loc/pt-BR/desktop/i18n/resources.resjson.lcl
Localize/loc/pt-PT/desktop/i18n/resources.resjson.lcl
Localize/loc/ru/desktop/i18n/resources.resjson.lcl
Localize/loc/sv/desktop/i18n/resources.resjson.lcl
Localize/loc/tr/desktop/i18n/resources.resjson.lcl
Localize/loc/zh-Hans/desktop/i18n/resources.resjson.lcl
Localize/loc/zh-Hant/desktop/i18n/resources.resjson.lcl

LEGO: Pull request from users/loc/juno/hb_b5190a78-9093-45f2-826d-2cc1e04cb56a_20230616160507576 to main with localized lcls

LEGO: Pull request from users/loc/juno/hb_b5190a78-9093-45f2-826d-2cc1e04cb56a_20230616160507576 to main

---

CHANGELOG.md
desktop/ThirdPartyNotices.txt
desktop/scripts/publish/publish.ts

Prepare for release 2.18.0

---

Localize/loc/cs/web/i18n/resources.resjson.lcl
Localize/loc/de/web/i18n/resources.resjson.lcl
Localize/loc/es/web/i18n/resources.resjson.lcl
Localize/loc/fr/web/i18n/resources.resjson.lcl
Localize/loc/hu/web/i18n/resources.resjson.lcl
Localize/loc/id/web/i18n/resources.resjson.lcl
Localize/loc/it/web/i18n/resources.resjson.lcl
Localize/loc/ja/web/i18n/resources.resjson.lcl
Localize/loc/ko/web/i18n/resources.resjson.lcl
Localize/loc/nl/web/i18n/resources.resjson.lcl
Localize/loc/pl/web/i18n/resources.resjson.lcl
Localize/loc/pt-BR/web/i18n/resources.resjson.lcl
Localize/loc/pt-PT/web/i18n/resources.resjson.lcl
Localize/loc/ru/web/i18n/resources.resjson.lcl
Localize/loc/sv/web/i18n/resources.resjson.lcl
Localize/loc/tr/web/i18n/resources.resjson.lcl
Localize/loc/zh-Hans/web/i18n/resources.resjson.lcl
Localize/loc/zh-Hant/web/i18n/resources.resjson.lcl

LEGO: Pull request from users/loc/juno/hb_b5190a78-9093-45f2-826d-2cc1e04cb56a_20230803131607860 to main with localized lcls

LEGO: Pull request from users/loc/juno/hb_b5190a78-9093-45f2-826d-2cc1e04cb56a_20230803131607860 to main

---

desktop/electron-builder.yml

Include the resources directory in the app

---

packages/react/i18n/resources.resjson
packages/react/src/account/arm.i18n.yml

These have been moved to bonito-core

Remove duplicate ARM strings

---

desktop/package-lock.json

Somehow missed this in the Electron upgrade PR.

Update desktop package-lock.json

---

desktop/src/app/components/common/react-container/react-container.component.ts
package-lock.json
packages/bonito-core/src/action/__tests__/action.spec.ts
packages/bonito-core/src/action/action.ts
packages/bonito-core/src/environment/abstract-environment.ts
packages/bonito-core/src/environment/environment.ts
packages/bonito-core/src/environment/mock-environment.ts
packages/bonito-core/src/form/__tests__/form.spec.ts
packages/bonito-core/src/form/__tests__/validation-snapshot.spec.ts
packages/bonito-core/src/form/form.ts
packages/bonito-core/src/form/internal/form-impl.ts
packages/bonito-core/src/form/subform.ts
packages/bonito-core/src/form/validation-snapshot.ts
packages/bonito-core/src/http/http-client.ts
packages/bonito-core/src/index.ts
packages/bonito-core/src/notification/__tests__/fake-notifier.spec.ts
packages/bonito-core/src/notification/fake-notifier.ts
packages/bonito-core/src/notification/index.ts
packages/bonito-core/src/notification/notification-util.ts
packages/bonito-core/src/util/__tests__/deferred.spec.ts
packages/bonito-core/src/util/deferred.ts
packages/bonito-ui/src/components/form/__tests__/action-form.spec.tsx
packages/bonito-ui/src/components/form/checkbox.tsx
packages/bonito-ui/src/components/form/list-form-layout.tsx
packages/bonito-ui/src/components/layout/root-pane.tsx
packages/bonito-ui/src/theme/azure-theme.ts
packages/bonito-ui/src/theme/theme-util.ts
packages/react/src/account/create-account-action.ts
web/src/components/application.tsx
web/src/components/layout/app-root.tsx

Various additions to forms, notifications and other APIs. See individual commits in this PR for details.

Assorted Bonito improvements

---

desktop/src/@batch-flask/electron/remote.service.ts

Fix error opening context menus

---

Localize/loc/cs/packages/bonito-ui/i18n/resources.resjson.lcl
Localize/loc/de/packages/bonito-ui/i18n/resources.resjson.lcl
Localize/loc/es/packages/bonito-ui/i18n/resources.resjson.lcl
Localize/loc/fr/packages/bonito-ui/i18n/resources.resjson.lcl
Localize/loc/hu/packages/bonito-ui/i18n/resources.resjson.lcl
Localize/loc/id/packages/bonito-ui/i18n/resources.resjson.lcl
Localize/loc/it/packages/bonito-ui/i18n/resources.resjson.lcl
Localize/loc/ja/packages/bonito-ui/i18n/resources.resjson.lcl
Localize/loc/ko/packages/bonito-ui/i18n/resources.resjson.lcl
Localize/loc/nl/packages/bonito-ui/i18n/resources.resjson.lcl
Localize/loc/pl/packages/bonito-ui/i18n/resources.resjson.lcl
Localize/loc/pt-BR/packages/bonito-ui/i18n/resources.resjson.lcl
Localize/loc/pt-PT/packages/bonito-ui/i18n/resources.resjson.lcl
Localize/loc/ru/packages/bonito-ui/i18n/resources.resjson.lcl
Localize/loc/sv/packages/bonito-ui/i18n/resources.resjson.lcl
Localize/loc/tr/packages/bonito-ui/i18n/resources.resjson.lcl
Localize/loc/zh-Hans/packages/bonito-ui/i18n/resources.resjson.lcl
Localize/loc/zh-Hant/packages/bonito-ui/i18n/resources.resjson.lcl

LEGO: Pull request from users/loc/juno/hb_b5190a78-9093-45f2-826d-2cc1e04cb56a_20231018000733472 to main with localized lcls

LEGO: Pull request from users/loc/juno/hb_b5190a78-9093-45f2-826d-2cc1e04cb56a_20231018000733472 to main

---

Localize/loc/ja/packages/bonito-ui/i18n/resources.resjson.lcl

LEGO: Pull request from users/loc/juno/hb_b5190a78-9093-45f2-826d-2cc1e04cb56a_20231018120841290 to main with localized lcls

LEGO: Pull request from users/loc/juno/hb_b5190a78-9093-45f2-826d-2cc1e04cb56a_20231018120841290 to main

---

Localize/loc/pl/packages/bonito-ui/i18n/resources.resjson.lcl

LEGO: Pull request from users/loc/juno/hb_b5190a78-9093-45f2-826d-2cc1e04cb56a_20231019120623801 to main with localized lcls

LEGO: Pull request from users/loc/juno/hb_b5190a78-9093-45f2-826d-2cc1e04cb56a_20231019120623801 to main

---

desktop/src/@batch-flask/ui/buttons/button.scss
desktop/src/app/components/layout/pinned-entity-dropdown/pinned-dropdown.html

Fixes [AB#1051](https://azurebatch.visualstudio.com/3426cbfe-4c9a-4da4-88df-70f025a77017/_workitems/edit/1051), [AB#1059](https://azurebatch.visualstudio.com/3426cbfe-4c9a-4da4-88df-70f025a77017/_workitems/edit/1059), and [AB#1060](https://azurebatch.visualstudio.com/3426cbfe-4c9a-4da4-88df-70f025a77017/_workitems/edit/1060)

Accessibility fixes for windows high contrast buttons

---

CHANGELOG.md
desktop/ThirdPartyNotices.txt

Prepare for release 2.19.0

---

packages/bonito-ui/src/components/form/__tests__/tab-selector.spec.tsx

Fix incorrect test name for TabSelector

---

Localize/loc/cs/packages/bonito-ui/i18n/resources.resjson.lcl
Localize/loc/de/packages/bonito-ui/i18n/resources.resjson.lcl
Localize/loc/es/packages/bonito-ui/i18n/resources.resjson.lcl
Localize/loc/fr/packages/bonito-ui/i18n/resources.resjson.lcl
Localize/loc/hu/packages/bonito-ui/i18n/resources.resjson.lcl
Localize/loc/id/packages/bonito-ui/i18n/resources.resjson.lcl
Localize/loc/it/packages/bonito-ui/i18n/resources.resjson.lcl
Localize/loc/ja/packages/bonito-ui/i18n/resources.resjson.lcl
Localize/loc/ko/packages/bonito-ui/i18n/resources.resjson.lcl
Localize/loc/nl/packages/bonito-ui/i18n/resources.resjson.lcl
Localize/loc/pl/packages/bonito-ui/i18n/resources.resjson.lcl
Localize/loc/pt-BR/packages/bonito-ui/i18n/resources.resjson.lcl
Localize/loc/pt-PT/packages/bonito-ui/i18n/resources.resjson.lcl
Localize/loc/ru/packages/bonito-ui/i18n/resources.resjson.lcl
Localize/loc/sv/packages/bonito-ui/i18n/resources.resjson.lcl
Localize/loc/tr/packages/bonito-ui/i18n/resources.resjson.lcl
Localize/loc/zh-Hans/packages/bonito-ui/i18n/resources.resjson.lcl
Localize/loc/zh-Hant/packages/bonito-ui/i18n/resources.resjson.lcl

LEGO: Pull request from users/loc/juno/hb_b5190a78-9093-45f2-826d-2cc1e04cb56a_20231108011127925 to main with localized lcls

LEGO: Pull request from users/loc/juno/hb_b5190a78-9093-45f2-826d-2cc1e04cb56a_20231108011127925 to main

---

desktop/package-lock.json
desktop/package.json

Fixes [AB#1109](https://azurebatch.visualstudio.com/3426cbfe-4c9a-4da4-88df-70f025a77017/_workitems/edit/1109): json5@^2.23.2
Fixes [AB#1108](https://azurebatch.visualstudio.com/3426cbfe-4c9a-4da4-88df-70f025a77017/_workitems/edit/1108): ajv@^6.12.6
Fixes [AB#1047](https://azurebatch.visualstudio.com/3426cbfe-4c9a-4da4-88df-70f025a77017/_workitems/edit/1047): xmljs@^0.50.0

Updates various modules

---

.vsts/distribution.yml

Increases timeout to 2h for all OSes

---

Localize/loc/de/desktop/i18n/resources.resjson.lcl

LEGO: Pull request from users/loc/juno/hb_b5190a78-9093-45f2-826d-2cc1e04cb56a_20231218010944643 to main with localized lcls

LEGO: Pull request from users/loc/juno/hb_b5190a78-9093-45f2-826d-2cc1e04cb56a_20231218010944643 to main

---

Localize/loc/nl/desktop/i18n/resources.resjson.lcl
Localize/loc/ru/desktop/i18n/resources.resjson.lcl
Localize/loc/tr/desktop/i18n/resources.resjson.lcl

LEGO: Pull request from users/loc/juno/hb_b5190a78-9093-45f2-826d-2cc1e04cb56a_20231217130844265 to main with localized lcls

LEGO: Pull request from users/loc/juno/hb_b5190a78-9093-45f2-826d-2cc1e04cb56a_20231217130844265 to main

---

Localize/loc/de/desktop/i18n/resources.resjson.lcl
Localize/loc/es/desktop/i18n/resources.resjson.lcl
Localize/loc/fr/desktop/i18n/resources.resjson.lcl
Localize/loc/ja/desktop/i18n/resources.resjson.lcl
Localize/loc/nl/desktop/i18n/resources.resjson.lcl
Localize/loc/pt-BR/desktop/i18n/resources.resjson.lcl
Localize/loc/zh-Hans/desktop/i18n/resources.resjson.lcl

LEGO: Pull request from users/loc/juno/hb_b5190a78-9093-45f2-826d-2cc1e04cb56a_20231222130727895 to main with localized lcls

LEGO: Pull request from users/loc/juno/hb_b5190a78-9093-45f2-826d-2cc1e04cb56a_20231222130727895 to main

---

Localize/loc/it/desktop/i18n/resources.resjson.lcl
Localize/loc/ko/desktop/i18n/resources.resjson.lcl
Localize/loc/pl/desktop/i18n/resources.resjson.lcl
Localize/loc/pt-PT/desktop/i18n/resources.resjson.lcl
Localize/loc/sv/desktop/i18n/resources.resjson.lcl
Localize/loc/zh-Hant/desktop/i18n/resources.resjson.lcl

LEGO: Pull request from users/loc/juno/hb_b5190a78-9093-45f2-826d-2cc1e04cb56a_20231222011019498 to main with localized lcls

LEGO: Pull request from users/loc/juno/hb_b5190a78-9093-45f2-826d-2cc1e04cb56a_20231222011019498 to main

---

Localize/loc/cs/desktop/i18n/resources.resjson.lcl
Localize/loc/hu/desktop/i18n/resources.resjson.lcl

LEGO: Pull request from users/loc/juno/hb_b5190a78-9093-45f2-826d-2cc1e04cb56a_20231216130814087 to main with localized lcls

LEGO: Pull request from users/loc/juno/hb_b5190a78-9093-45f2-826d-2cc1e04cb56a_20231216130814087 to main

---

desktop/i18n/resources.resjson
desktop/src/app/components/certificate/action/add/add-certificate-form.html
desktop/src/app/components/certificate/action/add/add-certificate-form.i18n.yml
desktop/src/app/styles/vendor/material-theme.scss

Fixes [AB#1055](https://azurebatch.visualstudio.com/3426cbfe-4c9a-4da4-88df-70f025a77017/_workitems/edit/1055): Selected tab in high-contrast mode
Fixes [AB#1130](https://azurebatch.visualstudio.com/3426cbfe-4c9a-4da4-88df-70f025a77017/_workitems/edit/1130): Title on learn more certificate deprecation link

Fixes AB#1130: Title on learn more certificate deprecation link

---

Localize/loc/fr/desktop/i18n/resources.resjson.lcl
Localize/loc/it/desktop/i18n/resources.resjson.lcl
Localize/loc/pt-PT/desktop/i18n/resources.resjson.lcl
Localize/loc/zh-Hant/desktop/i18n/resources.resjson.lcl

LEGO: Pull request from users/loc/juno/hb_b5190a78-9093-45f2-826d-2cc1e04cb56a_20240107010656157 to main with localized lcls

LEGO: Pull request from users/loc/juno/hb_b5190a78-9093-45f2-826d-2cc1e04cb56a_20240107010656157 to main

---

Localize/loc/cs/desktop/i18n/resources.resjson.lcl
Localize/loc/de/desktop/i18n/resources.resjson.lcl
Localize/loc/hu/desktop/i18n/resources.resjson.lcl
Localize/loc/id/desktop/i18n/resources.resjson.lcl
Localize/loc/ko/desktop/i18n/resources.resjson.lcl
Localize/loc/pl/desktop/i18n/resources.resjson.lcl
Localize/loc/ru/desktop/i18n/resources.resjson.lcl
Localize/loc/sv/desktop/i18n/resources.resjson.lcl

LEGO: Pull request from users/loc/juno/hb_b5190a78-9093-45f2-826d-2cc1e04cb56a_20240107130750416 to main with localized lcls

LEGO: Pull request from users/loc/juno/hb_b5190a78-9093-45f2-826d-2cc1e04cb56a_20240107130750416 to main

---

Localize/loc/es/desktop/i18n/resources.resjson.lcl
Localize/loc/nl/desktop/i18n/resources.resjson.lcl
Localize/loc/tr/desktop/i18n/resources.resjson.lcl
Localize/loc/zh-Hans/desktop/i18n/resources.resjson.lcl

LEGO: Pull request from users/loc/juno/hb_b5190a78-9093-45f2-826d-2cc1e04cb56a_20240108010808809 to main with localized lcls

LEGO: Pull request from users/loc/juno/hb_b5190a78-9093-45f2-826d-2cc1e04cb56a_20240108010808809 to main

---

Localize/loc/pt-BR/desktop/i18n/resources.resjson.lcl

LEGO: Pull request from users/loc/juno/hb_b5190a78-9093-45f2-826d-2cc1e04cb56a_20240109010827416 to main with localized lcls

LEGO: Pull request from users/loc/juno/hb_b5190a78-9093-45f2-826d-2cc1e04cb56a_20240109010827416 to main

---

CHANGELOG.md
desktop/ThirdPartyNotices.txt
desktop/scripts/lca/generate-third-party.ts

Prepare for release 2.20.0

---

Localize/loc/ja/desktop/i18n/resources.resjson.lcl

LEGO: Pull request from users/loc/juno/hb_b5190a78-9093-45f2-826d-2cc1e04cb56a_20240110010736227 to main with localized lcls

LEGO: Pull request from users/loc/juno/hb_b5190a78-9093-45f2-826d-2cc1e04cb56a_20240110010736227 to main

---

desktop/src/app/app.component.ts

Prevent duplicate env initialization

---

.vsts/darwin/sign.yml
.vsts/distribution.yml
.vsts/pipelines.yml

The MacOS 11 image is scheduled for removal

Updated MacOS pipeline to macOS-13 image

---

desktop/karma.conf.js

This allows tests to run as root in the CI container

Add --no-sandbox flag to Electron when running tests

---

util/bux/util.ts

This PR fixes 2 regressions in the bux script that Dave and I identified:
- Previously, when a bux status command was run, it would only print out the git status for BatchExplorer. Now, it **also** prints out the git status for whatever repository it’s being run in (e.g. the portal or CycleCloud) 
- Also, I forgot to test the script in sub-directories underneath the root directory, so bux operations would previously fail if run in any directory other than the root directory. Now, all bux operations (configure, link, unlink, status) can be performed in any sub-directory under the root directory.
What the output looks like when running the commands in the portal (note the changing directories):
``` 
PS C:\Users\sanjanakapur\Batch-UX-Portal> node_modules/.bin/bux configure
? Path to Batch …
```

Fix regressions in bux script logic

---

desktop/src/client/core/aad/auth-provider.spec.ts
desktop/src/client/core/aad/auth-provider.ts

Users authenticating through the system browser are now presented with the account selection experience.

External browser auth prompts for account selection

---

Localize/loc/cs/desktop/i18n/resources.resjson.lcl
Localize/loc/de/desktop/i18n/resources.resjson.lcl
Localize/loc/es/desktop/i18n/resources.resjson.lcl
Localize/loc/fr/desktop/i18n/resources.resjson.lcl
Localize/loc/hu/desktop/i18n/resources.resjson.lcl
Localize/loc/id/desktop/i18n/resources.resjson.lcl
Localize/loc/it/desktop/i18n/resources.resjson.lcl
Localize/loc/ja/desktop/i18n/resources.resjson.lcl
Localize/loc/ko/desktop/i18n/resources.resjson.lcl
Localize/loc/nl/desktop/i18n/resources.resjson.lcl
Localize/loc/pl/desktop/i18n/resources.resjson.lcl
Localize/loc/pt-BR/desktop/i18n/resources.resjson.lcl
Localize/loc/pt-PT/desktop/i18n/resources.resjson.lcl
Localize/loc/ru/desktop/i18n/resources.resjson.lcl
Localize/loc/sv/desktop/i18n/resources.resjson.lcl
Localize/loc/tr/desktop/i18n/resources.resjson.lcl
Localize/loc/zh-Hans/desktop/i18n/resources.resjson.lcl
Localize/loc/zh-Hant/desktop/i18n/resources.resjson.lcl

LEGO: Pull request from users/loc/juno/hb_b5190a78-9093-45f2-826d-2cc1e04cb56a_20240901000833979 to main with localized lcls

LEGO: Pull request from users/loc/juno/hb_b5190a78-9093-45f2-826d-2cc1e04cb56a_20240901000833979 to main

---

Localize/loc/cs/desktop/i18n/resources.resjson.lcl
Localize/loc/fr/desktop/i18n/resources.resjson.lcl
Localize/loc/ko/desktop/i18n/resources.resjson.lcl
Localize/loc/sv/desktop/i18n/resources.resjson.lcl

LEGO: Pull request from users/loc/juno/hb_b5190a78-9093-45f2-826d-2cc1e04cb56a_20240902000824948 to main with localized lcls

LEGO: Pull request from users/loc/juno/hb_b5190a78-9093-45f2-826d-2cc1e04cb56a_20240902000824948 to main

---

desktop/src/client/proxy/manual-proxy-configuration-window/manual-proxy-configuration-window.css
desktop/src/client/proxy/manual-proxy-configuration-window/manual-proxy-configuration-window.html
desktop/src/client/proxy/manual-proxy-configuration-window/manual-proxy-configuration-window.spec.ts
desktop/src/client/proxy/manual-proxy-configuration-window/manual-proxy-configuration-window.ts

Used deprecated Electron `remote` object

Fixes broken proxy config window

---

.vsts/darwin/distribution.yml
.vsts/darwin/entitlements.plist
.vsts/darwin/sign.yml
.vsts/distribution.yml
.vsts/pipelines.yml

* Exits when certificate is invalid
* Uses latest MacOS VM image
* Adds entitlements

Notarization updates

---

.vsts/darwin/entitlements.plist
desktop/package-lock.json
desktop/package.json
desktop/src/@batch-flask/electron/auto-update/auto-update-main.service.ts
package-lock.json
util/bux/package-lock.json
util/common-config/package-lock.json
web/package-lock.json
web/package.json
web/src/components/application.tsx

Addresses some critical vulnerabilities

Component governance updates

---

desktop/package.json

Bumps Batch Explorer version to 2.22.0

Post-release merge 'stable' into main

---

index.js

Fixed a race condition where the version used would depend on which .yml file loaded last. Also added some missing semi-colons.

Use Windows version for home page banner

---

Localize/loc/de/desktop/i18n/resources.resjson.lcl
Localize/loc/es/desktop/i18n/resources.resjson.lcl
Localize/loc/hu/desktop/i18n/resources.resjson.lcl
Localize/loc/id/desktop/i18n/resources.resjson.lcl
Localize/loc/it/desktop/i18n/resources.resjson.lcl
Localize/loc/ja/desktop/i18n/resources.resjson.lcl
Localize/loc/nl/desktop/i18n/resources.resjson.lcl
Localize/loc/pt-PT/desktop/i18n/resources.resjson.lcl
Localize/loc/ru/desktop/i18n/resources.resjson.lcl
Localize/loc/tr/desktop/i18n/resources.resjson.lcl
Localize/loc/zh-Hans/desktop/i18n/resources.resjson.lcl
Localize/loc/zh-Hant/desktop/i18n/resources.resjson.lcl

LEGO: Pull request from users/loc/juno/hb_b5190a78-9093-45f2-826d-2cc1e04cb56a_20240901120711551 to main with localized lcls

LEGO: Pull request from users/loc/juno/hb_b5190a78-9093-45f2-826d-2cc1e04cb56a_20240901120711551 to main

---

Localize/loc/cs/desktop/i18n/resources.resjson.lcl
Localize/loc/de/desktop/i18n/resources.resjson.lcl
Localize/loc/es/desktop/i18n/resources.resjson.lcl
Localize/loc/fr/desktop/i18n/resources.resjson.lcl
Localize/loc/hu/desktop/i18n/resources.resjson.lcl
Localize/loc/id/desktop/i18n/resources.resjson.lcl
Localize/loc/it/desktop/i18n/resources.resjson.lcl
Localize/loc/ja/desktop/i18n/resources.resjson.lcl
Localize/loc/ko/desktop/i18n/resources.resjson.lcl
Localize/loc/nl/desktop/i18n/resources.resjson.lcl
Localize/loc/pl/desktop/i18n/resources.resjson.lcl
Localize/loc/pt-BR/desktop/i18n/resources.resjson.lcl
Localize/loc/pt-PT/desktop/i18n/resources.resjson.lcl
Localize/loc/ru/desktop/i18n/resources.resjson.lcl
Localize/loc/sv/desktop/i18n/resources.resjson.lcl
Localize/loc/tr/desktop/i18n/resources.resjson.lcl
Localize/loc/zh-Hans/desktop/i18n/resources.resjson.lcl
Localize/loc/zh-Hant/desktop/i18n/resources.resjson.lcl

Rolled up from separate PRs:
#2962, #2963, #2964, #2965, and #2966

Localization updates

---

Localize/loc/fr/packages/bonito-ui/i18n/resources.resjson.lcl

LEGO: Pull request from users/loc/juno/hb_b5190a78-9093-45f2-826d-2cc1e04cb56a_20250205212949672 to main with localized lcls

LEGO: Pull request from users/loc/juno/hb_b5190a78-9093-45f2-826d-2cc1e04cb56a_20250205212949672 to main
