Azure/BatchExplorer

app/components/pool/graphs/pool-graphs.component.ts, app/components/pool/graphs/pool-graphs.html, app/services/core/data-cache.ts, app/services/core/index.ts, app/services/core/poll-service.ts, app/services/core/rx-entity-proxy.ts, app/services/core/rx-list-proxy.ts, app/services/core/rx-proxy-base.ts, app/services/core/targeted-data-cache.ts, app/utils/object.ts, definitions/index.d.ts, test/app/services/core/data-cache.spec.ts, test/app/services/core/poll-service.spec.ts, test/app/utils/object.spec.ts
If we have multiple components that would poll same set of resources, then it would be ineficient to have to double every call. This allow a sync between component as it keeps only the smallest timer for each resource.
=> Poll service to sync to allow multiple component to poll the same resource effictivelly

CHANGELOG.md, Readme.md, package.json
=> Changelog and stable branch docs

app/components/file/browse/node-file-browse.html, app/components/file/browse/node-file-list.component.ts, app/components/node/browse/node-list.component.ts, app/services/core/rx-batch-list-proxy.ts, app/services/core/rx-list-proxy.ts, test/app/services/core/rx-batch-list-proxy.spec.ts
=> Fix node files filter and load more always showing after first load even if no more

app/app.ts, app/services/adal/adal.service.ts, app/services/adal/user-authorization.ts, client/main.ts, client/splash-screen/splash-screen.html, client/splash-screen/splash-screen.ts
=> Splash screen show status progress

Readme.md, app/services/core/query-cache.ts, app/services/core/rx-list-proxy.ts
=> Fix query cache not including newly created entities

app/components/job/action/add/pool-picker.component.ts, app/components/job/details/job-progress-status/job-progress-status.component.ts, app/components/pool/browse/pool-list.component.ts, app/components/pool/graphs/pool-graphs.component.ts, app/components/task/browse/task-list.component.ts, app/services/core/index.ts, app/services/core/list-options.ts, app/services/core/rx-arm-list-proxy.ts, app/services/core/rx-batch-list-proxy.ts, app/services/core/rx-list-proxy.ts, app/services/core/rx-proxy-base.ts, app/services/node-service.ts, app/services/service-base.ts, app/services/task-service.ts, test/app/components/application/browse/application-list.component.spec.ts, test/app/components/file/browse/node-file-list.component.spec.ts, test/app/services/core/list-options.spec.ts, test/app/services/core/rx-batch-list-proxy.spec.ts
This is done by changing the way the query cache works. It will now just be used to show the initial items but items will still be loaded in the background(This should also make sure the data is not out of date)
fix #297
=> Fix bug with query cache loading items too litle at the time

app/components/base/form/create-form/create-form.html, app/components/base/form/form-base.ts, app/styles/base/forms.scss, app/styles/base/server-error.scss, test/app/components/base/form/create-form/create-form.spec.ts
=> Show error at the bottom sticked to the footer

app/components/pool/base/index.ts, app/components/pool/base/pool-nodes-preview.component.ts, app/components/pool/base/pool-nodes-preview.html, app/components/pool/base/pool-nodes-preview.scss, app/components/pool/details/pool-details.html, app/styles/pool/base.scss, definitions/index.d.ts, test/app/components/pool/base/pool-nodes-preview.component.spec.ts
=> Fix: Pool node file preview

app/components/base/form/form-base.ts, app/components/base/form/simple-form/simple-form.component.ts, app/components/base/form/simple-form/simple-form.html, app/components/pool/start-task/start-task-edit-form.component.ts, app/components/pool/start-task/start-task-edit-form.html, app/core/record/record.ts, app/models/pool.ts, test/app/core/record.spec.ts
=> Fix start task edit

app/components/account/browse/account-list.component.ts, app/components/account/browse/account-list.html, app/services/account.service.ts, test/app/components/account/browse/account-list.component.spec.ts
=> Fix: Show loading animation for account list.

app/components/application/details/application-details.html, app/components/application/home/application-home.html, app/components/base/table/table.scss, app/components/job/details/error-display/job-error-display.html, app/components/job/details/job-configuration.component.ts, app/components/job/details/job-details.html, app/core/record/decorators.ts, app/core/record/helpers.ts, app/models/constraints.ts, app/models/job-constraints.ts, app/models/job-execution-information.ts, app/models/job.ts, app/models/name-value-pair.ts, app/models/scheduling-error.ts, test/app/components/job/details/error-display/job-error-display.component.spec.ts, test/app/core/record.spec.ts, tslint.json
=> Fix: Disabled editing tags for a completed job & small refactor

app/components/account/base/storage-account-picker/storage-account-picker.html, app/core/record/arm-record.ts, app/models/storage-account.ts, app/services/storage-account.service.ts
=> Fix: List classic storage accounts too

app/components/application/browse/application-list.component.ts, app/components/job/action/delete/delete-job-action.ts, app/components/job/browse/job-list.component.ts, app/components/job/details/job-details.component.ts, app/components/job/details/job-progress-status/job-progress-status.component.ts, app/components/node/details/node-details.component.ts, app/components/pool/action/delete/delete-pool-task.ts, app/components/pool/browse/pool-list.component.ts, app/components/pool/details/pool-details.component.ts, app/components/task/action/delete/delete-task-action.ts, app/components/task/browse/task-list.component.ts, app/components/task/details/task-details.component.ts, app/services/core/rx-entity-proxy.ts, app/services/core/rx-list-proxy.ts, app/services/core/rx-proxy-base.ts, app/services/job-service.ts, app/services/node-service.ts, app/services/pool-service.ts, app/services/task-service.ts, app/utils/constants.ts, test/app/services/core/rx-batch-list-proxy.spec.ts
=> Feature: Entities are refreshing every 10 seconds automatically

app/app.module.ts, app/components/job/details/job-progress-status/job-progress-status.component.ts, app/components/pool/graphs/history-data/running-tasks-history-data.ts, app/components/pool/graphs/nodes-heatmap.component.ts, app/components/pool/graphs/nodes-heatmap.html, app/components/pool/graphs/pool-graphs.component.ts, app/components/pool/graphs/pool-graphs.html, app/components/task/details/task-configuration.component.ts, app/components/task/details/task-resource-files.component.ts, app/models/compute-node-information.ts, app/models/node.ts, app/models/task.ts, app/services/core/poll-service.ts, app/services/core/rx-entity-proxy.ts, app/services/core/rx-list-proxy.ts, app/services/job-service.ts, app/services/task-service.ts, app/utils/constants.ts, test/app/components/job/details/job-progress-status/job-progress-status.component.spec.ts, test/app/components/pool/graphs/nodes-heatmap.component.spec.ts, test/app/components/task/details/task-dependencies.component.spec.ts, test/app/components/task/details/task-error-display.component.spec.ts, test/app/components/task/details/task-lifetime/task-timeline.component.spec.ts, test/app/models/node.spec.ts, test/app/models/task.spec.ts
=> Feature: Load all tasks running on a pool

app/components/file/details/file-details.html, app/components/node/browse/display/node-list-display.html, app/styles/file/log.scss
=> Fix: Files summary card style not updated for new actions buttons

app/app.component.ts, app/components/pool/action/add/pool-create-basic-dialog.component.ts, app/components/pool/action/add/pool-create-basic-dialog.html, app/components/pool/action/add/vm-size-picker.component.ts, app/components/pool/action/add/vm-size-picker.html
=> Enable pricing and fix it being hard coded for linux

CHANGELOG.md, package.json
=> Update version and changelog for version 0.6.0

src/client/client-constants.ts, src/client/logger/logger-proxy.ts, src/client/python-process/python-rpc-server-process.ts
=> Internal: python rpc server log stdout and stderr to file

app/components/base/background-task/background-task-tracker.scss, app/components/data/action/add/file-group-create-form.component.ts
Make background task label a bit wider to display more of the name. Sub-string the file group name to 10 characters and add an ellipsis if required.
Fix #704
=> make background task label more friendly

app/services/file/file-loader.ts
Clean out any stray : characters from a full path file group.  Hopefully this is ok, but its only writing to the temp file location so changing "D:" to "D" should be fine as the destination source is passed into the file viewer.
Fix #561
=> Not able to view image with full path

app/components/file/browse/file-explorer/file-table-view/file-table-view.html, app/components/task/details/output/task-outputs.component.ts, app/services/file/file-navigator/file-navigator.ts, test/app/components/task/details/output/task-output.component.spec.ts, test/app/services/file/file-navigator/file-tree.model.spec.ts
change a couple of words in notifications
fix the blob file explorer by removing training slash that was messing up the storage prefix.
=> grammar issues and fix blob file explorer

src/client/main.ts
=> Fix osx copy and paste shortcuts not working in prod

app/components/application/details/application-details.component.ts
Fix: #777 
Background overlay was not being removed after a successful delete. Seems delete application used an old way of opening dialog boxes.
=> Fix delete application dialog

app/services/adal/adal.service.ts, app/services/adal/token-cache.ts
fix #783 
The cached tokens were also not being stored correcly which should improve loading time when refreshing the app or restarting and it doesn't need to relogin
=> Fix: handling refresh token error & cached token not loaded

app/components/application/action/delete/delete-application-action.ts, app/components/application/action/delete/delete-application-dialog.html, app/components/application/browse/application-list.component.ts, app/components/application/browse/application-list.html, app/components/application/details/application-details.html, app/components/base/buttons/buttons.component.ts, app/components/data/details/data-details.html, app/components/job/details/job-details.component.ts, app/components/job/details/job-details.html, app/components/node/details/node-details.html, app/components/pool/details/pool-details.html, app/components/task/details/task-details.html, test/app/components/application/browse/application-list.component.spec.ts
=> Batch Application context menu and delete refactor.

.travis.yml, app/components/shared/main-navigation.component.ts, app/services/electron/remote.service.ts, electron-builder.yml, package.json
Auto update should be called in `setImmediate`
=> Fix: auto update and update node

app/components/account/details/programatic-usage/programing-sample/samples/aad/node.js.template, app/services/core/data-cache.ts, app/services/core/data/list-view.ts, app/services/task-service.ts, python/requirements.txt
fix #1065 
Currently if data was in the cache it would load from there but not update with server data unless explicitly refershed which leads to weird data if deleting a job and recreating and navigating to it seeing deleted job task.
Still try to load from cache to have a fast loading if quickly switching between elements.
Could maybe add a timestamp to the cache and not even try to load from it if the data is too old
=> List view loads from cache but always query server right away to check for changes

app/components/account/details/account-details.html, src/@batch-flask/ui/table/table.scss
Added CSS for bl-cell that allows for fixed size columns rather than them all defaulting to the same width. Changed account overview to use new CSS.
Fix: #1136
=> Allow fixed size table columns for flex-boxes

app/components/data/action/add/file-group-create-form.component.ts, app/components/data/action/add/file-group-create-form.html, app/components/data/action/add/file-group-create-form.scss, app/components/data/shared/file-group-picker/file-group-picker.component.ts, app/components/market/submit/parameter-input/parameter-input.component.spec.ts, app/components/market/submit/parameter-input/parameter-input.component.ts, app/components/market/submit/submit-ncj-template.component.spec.ts, app/components/market/submit/submit-ncj-template.component.ts, app/components/market/submit/submit-ncj-template.html, app/services/storage.service.ts, src/@batch-flask/ui/notifications/notification.ts, src/client/core/batchlabs-application.ts, src/common/constants/constants.ts
Fix: #1180
When submitting a job from a plugin, if you supply a container name and a set of paths it will automatically populate the file group create/manage form.
=> Setup file-group sync via plugin before submit

app/services/local-file-storage.service.ts, src/@batch-flask/ui/entity-commands/entity-command.ts, src/client/core/aad/authentication/authentication.service.ts
Spelling of 'successful' was incorrect. Mainly an issue in the user-facing notification, but updated all references in the project.
=> Correct spelling of 'successful'.

app/components/data/action/add/file-group-create-form.component.ts, app/services/ncj-file-group.service.ts, python/controllers/create_file_group_controller.py, python/jsonrpc/error.py, python/requirements.txt, python/server/app.py, src/@batch-flask/core/server-error/server-error.ts, src/@batch-flask/ui/background-task/background-task-tracker-item.html, src/@batch-flask/ui/background-task/background-task-tracker-item/background-task-tracker-item.component.ts, src/@batch-flask/ui/background-task/background-task-tracker-item/background-task-tracker-item.html, src/@batch-flask/ui/background-task/background-task-tracker-item/index.ts, src/@batch-flask/ui/background-task/background-task-tracker.component.ts, src/@batch-flask/ui/background-task/background-task.module.ts, src/client/startup.ts
fix #1355 
Also refactor background task tracker to use `OnPush` for perf
=> Fix: Show better errors form python server when folder is empty

app/app.module.ts, app/services/azure-batch/core/batch-http.service.ts, app/services/azure-batch/core/index.ts, app/services/batch-api/poolProxy.ts, app/services/pool.service.ts, src/@batch-flask/core/http-base.ts, src/@batch-flask/core/server-error/server-error.ts, src/common/constants/constants.ts
fix #1413 
This set the foundation to call the rest api directly without the sdk, which means we could potentially get rid of it and save in bundle size
=> Feature: Call rest api directly for resize as there is an issue with duration on mac

app/components/pool/graphs/performance-graph/enable-app-insights-doc/enable-app-insights-doc.html
=> Fix: App insights docs having wrong environment variables names

app/components/job/details/job-progress-status/job-progress-status.component.spec.ts, app/components/job/details/job-progress-status/job-progress-status.component.ts, app/components/job/details/job-progress-status/job-progress-status.html, app/components/job/details/job-progress-status/job-progress-status.scss, app/components/task/details/task-timeline/task-timeline.component.ts, app/models/job-task-counts.ts, src/client/core/bl-ipc-main.ts
=> Feature: Job task counts shows warning if not validated

app/app.component.ts, app/components/market/home/market.component.ts, app/components/settings/default-settings.json, app/models/settings.ts, app/services/github-data.service.ts, app/services/github-data/github-data.service.spec.ts, app/services/github-data/github-data.service.ts, app/services/github-data/index.ts, app/services/index.ts, app/services/ncj-template.service.ts, app/services/predefined-formula.service.ts, app/services/vm-size.service.ts
=> Feature: Pick which branch to load the github data from 

app/services/ncj-file-group.service.ts
Creating a file group now only calls get to validate whether the group exists already, instead of create (probably a bad copy/paste or something)
=> Fix: File Group Creation

app/models/dtos/index.ts, app/models/dtos/task-create/index.ts, app/models/dtos/task-create/task-create.dto.spec.ts, app/models/dtos/task-create/task-create.dto.ts, app/models/dtos/user-identity.dto.ts, app/models/user-account.ts
=> Fix task clone user identity

app/app.ts, app/components/account/browse/account-browse.module.ts, app/components/account/browse/account-dropdown.scss, app/components/account/browse/account-list/account-list.component.spec.ts, app/components/account/browse/account-list/account-list.html, app/components/account/browse/account-list/account-list.scss, app/components/account/monitoring/monitor-chart/monitor-chart.component.ts, app/components/account/monitoring/monitor-chart/monitor-chart.scss, app/components/common/common.module.ts, app/components/common/index.ts, app/components/common/location/index.ts, app/components/common/location/location.component.spec.ts, app/components/common/location/location.component.ts, app/components/common/location/location.html, app/components/common/location/location.module.ts, app/components/common/location/location.scss, app/services/monitoring/metrics/insights-metrics.service.spec.ts, app/services/monitoring/metrics/insights-metrics.service.ts, package-lock.json, package.json
=> Accessibility: Make account list favorites accessible + show flag for location

app/components/data/home/data-home.component.ts, app/components/job-schedule/action/add/job-schedule-job-specification.html, src/@batch-flask/ui/dialogs/prompt/prompt-dialog.html, src/common/constants/constants.ts
=> Feature: Add container length validation

CHANGELOG.md, app/models/dtos/pool-create/pool-create.dto.spec.ts, app/models/dtos/virtual-machine-configuration.dto.ts, app/models/forms/create-pool-model.ts
=> Fix: Create pool with custom image broken

app/components/certificate/browse/filter/certificate-advanced-filter.component.ts, app/components/certificate/home/certificate-home.html, app/components/job-schedule/browse/filter/job-schedule-advanced-filter.component.ts, app/components/job-schedule/home/job-schedule-home.html, app/components/job/browse/filter/job-advanced-filter.component.ts, app/components/job/home/job-home.html, app/components/node/browse/filter/node-advanced-filter.component.ts, app/components/node/home/node-home.html, app/components/pool/browse/filter/pool-advanced-filter.component.ts, app/components/pool/home/pool-home.html, app/components/task/browse/filter/task-advanced-filter.component.ts, app/components/task/home/task-home.html
fix #1687
Seems to be a conflict with having an output called `change` angular emits change event in some scenarios
=> Fix: Error thrown in advanced filter windows

scripts/azpipelines/upload-to-storage.js
fix #1689 
This will try the following: 
- Upload the file to blob
- If it fails because blob already exists compare the md5 of the blob with the local file
- If this is the same just pass as the file is already up to date on the blob
- If the file is different throw an error and fail the release(File shouldn't be there or release has wrong version)
=> Internal: Handle release retries by not re-uploading artifact

src/@batch-flask/ui/browse-layout/browse-layout.component.ts, src/@batch-flask/ui/browse-layout/browse-layout.html, src/@batch-flask/ui/browse-layout/browse-layout.module.ts, src/@batch-flask/ui/browse-layout/browse-layout.scss, src/@batch-flask/ui/file/file-loader/file-loader.ts, src/@batch-flask/ui/split-pane/split-separator/split-separator.component.ts, src/@batch-flask/ui/split-pane/split-separator/split-separator.scss, src/@batch-flask/ui/summary-card/summary-card.scss, src/app/components/account/details/account-quotas-card/account-quotas-card.html, src/app/components/account/details/account-quotas-card/account-quotas-card.scss
=> Feature: Resizable left pane

src/app/components/data/shared/file-group-picker/file-group-picker.component.ts, src/app/components/data/shared/file-group-picker/file-group-picker.html, src/app/components/data/shared/file-group-picker/file-group-picker.i18n.yml, src/app/components/market/submit/parameter-input/parameter-input.component.spec.ts, src/app/components/market/submit/submit-ncj-template.component.spec.ts, src/app/components/market/submit/submit-ncj-template.component.ts, src/app/components/settings/default-settings.json, src/app/models/settings.ts, src/common/constants/constants.ts
User can define a default output container to use when submitting gallery template jobs. Handles one being passed in from a plugin using the ms-batchlabs:// route parameters also.
Fix: #1790
=> Auto add default file group output container

electron-builder.yml
=> Fix: Show the right icon in insider builds

src/app/app.component.ts, src/app/components/pool/action/add/vm-size-picker/vm-size-picker.component.spec.ts, src/app/components/pool/action/add/vm-size-picker/vm-size-picker.component.ts, src/app/components/pool/action/add/vm-size-picker/vm-size-picker.html, src/app/components/pool/action/add/vm-size-picker/vm-size-picker.scss, src/app/services/compute/index.ts, src/app/services/compute/vm-size.service.spec.ts, src/app/services/compute/vm-size.service.ts, src/app/services/github-data/github-data.service.spec.ts, src/app/services/github-data/github-data.service.ts, src/app/services/index.ts, src/app/services/pricing.service.ts, src/app/services/quota.service.ts, src/app/services/vm-size.service.ts
=> Feature: VM Sizes picker show basic input when unable to get vm sizes(Local account)

CHANGELOG.md, package.json, src/app/components/gallery/submit/submit-ncj-template.component.ts, src/app/components/job/graphs/tasks-running-time-graph/task-running-time-graph.component.spec.ts, src/app/components/job/graphs/tasks-running-time-graph/tasks-running-time-graph.component.ts, src/app/components/workspace/json-templates/end-user-workspace.json
=> Fix: Task stats filter by start time

src/app/components/account/browse/account-list/account-list.component.ts, src/app/services/batch-account/arm-batch-account.service.ts, src/app/services/batch-account/batch-account.service.ts, src/app/services/compute.service.ts, src/app/services/index.ts, src/app/services/storage-account.service.ts, src/app/services/subscription.service.ts, src/app/services/subscription/index.ts, src/app/services/subscription/subscription.service.spec.ts, src/app/services/subscription/subscription.service.ts
fix #1872 
When listing subscription if the call add a nextLink to follow it was not returning which caused a undefined error
=> Fix: subscription with nextLink undefined error and fix duplicate calls

src/app/components/data/action/add/file-group-create-form.component.ts, src/app/components/data/shared/file-group-picker/file-group-picker.component.ts, src/app/components/data/shared/file-group-picker/file-group-picker.html, src/app/components/data/shared/file-group-picker/file-group-picker.i18n.yml
=> Feature: Show file group upload progress

src/app/services/adal/adal.service.spec.ts, src/app/services/adal/adal.service.ts, src/client/core/aad/adal/aad.service.spec.ts, src/common/deferred/deferred.spec.ts, src/test/utils/async-test.ts, src/test/utils/index.ts
fix #1505
This should allow to recover after the connection died while retrieving tokens.
This was discovered after the original issue was the auth window was failing to load the AADlogin page and then never resolving which was fixed. Now though that it is throwing an error it was being cached by mistake
=> Fix: Authentication error is being cached an doesn't allow reload 

src/@batch-flask/ui/file/file-loader/file-loader.spec.ts, src/@batch-flask/ui/file/file-loader/file-loader.ts, src/@batch-flask/ui/file/file-viewer/file-too-large/file-too-large.component.ts, src/@batch-flask/ui/file/file-viewer/file-viewer-container/file-viewer-header/file-viewer-header.component.spec.ts, src/@batch-flask/ui/file/file-viewer/file-viewer-container/file-viewer-header/file-viewer-header.component.ts, src/@batch-flask/ui/file/file-viewer/image-file-viewer/image-file-viewer.component.spec.ts, src/@batch-flask/ui/file/file-viewer/image-file-viewer/image-file-viewer.component.ts, src/app/components/gallery/local-template-explorer/local-template-explorer.component.ts, src/app/services/ncj/local-template.service.ts
=> Feature: Show abssolute path and open actual file in local templates

src/@batch-flask/ui/buttons/button.component.ts
Seems like showing the tooltip immediatly conflict with the label and Voice Over describe weird things
=> Fix: Voice over issue in credentials and code samples

src/@batch-flask/ui/time-range-picker/time-range-picker.component.ts, src/app/components/account/details/account-cost-card/account-cost-card.component.spec.ts, src/app/components/account/details/account-cost-card/account-cost-card.component.ts, src/app/components/account/details/account-cost-card/account-cost-card.html, src/app/components/account/details/account-cost-card/account-cost-card.scss, src/app/services/azure-cost-management/azure-cost-management.service.spec.ts, src/app/services/azure-cost-management/azure-cost-management.service.ts
=> Feature: Ability to pick time range for account cost

src/app/services/subscription/subscription.service.ts
=> Feature: Sort subscriptions in subscription picker

src/app/components/job-schedule/details/job-schedule-job-specification.component.spec.ts, src/app/components/job-schedule/details/job-schedule-job-specification.html
=> Fix: Job Schedule job release task null error

CHANGELOG.md, package.json, src/app/components/pool/graphs/pool-graphs.html
One week and a day both have the value of a day
fix #1999
=> Fix: Pool graph doesn't let you pick one week

karma.conf.js, src/@batch-flask/core/commands/command-registry/command-registry.spec.ts, src/@batch-flask/core/commands/command-registry/command-registry.ts, src/@batch-flask/core/commands/keybindings/keybindings.service.spec.ts, src/@batch-flask/core/commands/keybindings/keybindings.service.ts, src/@batch-flask/ui/index.ts, src/@batch-flask/ui/keybindings/index.ts, src/@batch-flask/ui/keybindings/keybindings.component.spec.ts, src/@batch-flask/ui/keybindings/keybindings.component.ts, src/@batch-flask/ui/keybindings/keybindings.html, src/@batch-flask/ui/keybindings/keybindings.module.ts, src/@batch-flask/ui/keybindings/keybindings.scss, src/app/app.module.ts, src/app/app.routes.ts, src/app/commands/account.appcmd.ts, src/app/commands/data.appcmd.ts, src/app/commands/job.appcmd.ts, src/app/commands/list.appcmd.ts, src/app/commands/pool.appcmd.ts, src/app/components/layout/main-navigation/profile-button/profile-button.component.spec.ts, src/app/components/layout/main-navigation/profile-button/profile-button.component.ts, src/app/components/layout/main-navigation/profile-button/profile-button.i18n.yml
#2006
This is a ready only page for now. Key bindings cannot be edited
=> Feature: Add key bindings configuration page

src/@batch-flask/core/commands/keybindings/keybindings.service.spec.ts, src/@batch-flask/core/commands/keybindings/keybindings.service.ts, src/@batch-flask/core/commands/keybindings/user-keybindings.service.ts, src/@batch-flask/core/keys.ts, src/@batch-flask/core/list/selectable-list.ts, src/@batch-flask/ui/keybindings/keybinding-picker/index.ts, src/@batch-flask/ui/keybindings/keybinding-picker/keybinding-picker-dialog.component.spec.ts, src/@batch-flask/ui/keybindings/keybinding-picker/keybinding-picker-dialog.component.ts, src/@batch-flask/ui/keybindings/keybinding-picker/keybinding-picker-dialog.html, src/@batch-flask/ui/keybindings/keybinding-picker/keybinding-picker-dialog.scss, src/@batch-flask/ui/keybindings/keybindings-listener.directive.ts, src/@batch-flask/ui/keybindings/keybindings.component.spec.ts, src/@batch-flask/ui/keybindings/keybindings.component.ts, src/@batch-flask/ui/keybindings/keybindings.html, src/@batch-flask/ui/keybindings/keybindings.module.ts, src/@batch-flask/ui/keybindings/keybindings.scss, src/test/utils/helpers/template-interaction.ts
=> Feature: Add support for user key binding customization

src/app/components/task/base/user-identity/user-identity-picker.component.spec.ts, src/app/components/task/base/user-identity/user-identity-picker.component.ts
Switch defaults around, to align with best practices (even though default through REST is different)
=> Update auto-user defaults to target pool scope

src/app/components/pool/details/error-display/pool-error-display.html
========>>
Don't love the duplication but its either this or hover text, but hover text may have some accessibility concerns? I guess the message could also just be moved to entirely be in the description so only code + fix in banner
=> Fix resize error text getting cutoff in banner

src/app/components/node/browse/filter/node-advanced-filter.component.ts
Fixes #2069 . Looks to just have been a missed state in the state picker.
=> Add Offline OData filter to advanced filter on Pool list nodes page

src/app/components/pool/start-task/start-task-picker.component.spec.ts, src/app/components/pool/start-task/start-task-picker.component.ts
Sets waitForSuccess checkbox as checked as default. Tests for waitForSuccess.
=> Fix starttask waitforsuccess

src/@batch-flask/ui/banner/banner.component.spec.ts, src/@batch-flask/ui/banner/banner.component.ts, src/@batch-flask/ui/banner/banner.html, src/app/components/pool/details/error-display/pool-error-display.html
Changed the error message details to display by default.
=> Pool Resize Error Default

src/app/components/pool/graphs/heatmap/nodes-heatmap.component.spec.ts, src/app/components/pool/graphs/heatmap/nodes-heatmap.component.ts, src/app/components/pool/graphs/pool-graphs.component.ts, src/app/components/pool/graphs/pool-graphs.html
Added an error banner for unusable nodes:
* Changed tooltip for error nodes to display error instead of number of tasks running
* Added error banner for unusable nodes
* Changed error message for both unusable nodes and start task failed errors to be more explicit
=> Unusable Node Error Banner on Pool Page

src/app/components/pool/action/add/app-license-picker/app-license-picker.component.spec.ts, src/app/components/pool/action/add/app-license-picker/app-license-picker.component.ts, src/app/components/pool/action/add/license-eula-dialog/license-eula-dialog.component.ts, src/app/models/batch-software-license.ts, src/app/models/batch-software-skus.ts, src/app/models/index.ts, src/app/models/software-billing-unit.ts, src/app/services/pricing.service.ts, src/app/services/pricing/pricing.model.ts, src/app/utils/pool-utils.spec.ts
Updated Autodesk Arnold meter pricing and units, and added Chaos Group V-Ray RT to list of available software. 
* EULA for V-Ray RT is the same as EULA for V-Ray
Current list of software available:
Chaos Group V-Ray RT EULA link:
=> Autodesk Arnold Meter Change 

package-lock.json
This was lost in the dependency update PR
=> Reapply dependabot websocket-extension security fix

scripts/package/package-utils.ts, scripts/package/package.ts
Handles 2 breaking changes from the recent electron-builder update:
- The API for creating a standalone executable in electron-builder changed.
- The Linux AppImage binary filename changed.
=> Fixed Windows/Linux packaging issues

src/client/splash-screen/splash-screen.ts, test/spectron/test-app-start.spec.ts
When running in dev mode, Batch Explorer kept getting stuck on the splash screen for Mac. This minor change fixes this issue.
=> Fixed Splash Screen Stuck Issue - Mac

src/client/core/batch-explorer-application.ts
Fixes #2212 and Fixes #2165 
The User-Agent string being sent was exposing a bug in AAD auth when setting up 2-factor verification. Including the default Electron User-Agent string fixed this issue.
=> Include the default Electron User-Agent string

scripts/install/install-windows.bat, scripts/install/install-windows.ps1
Allows developers (e.g., moi 😃) to build BatchExplorer on Windows.
=> Windows install scripts support paths with spaces

.vsts/dependencies.yml, scripts/azpipelines/build-type.ps1, scripts/azpipelines/update-build-name.ps1
When manually building a PR branch, underscores would cause the RPM
build to fail
=> Replace hyphens in the build number with underscores

data/themes/classic.json, src/@batch-flask/ui/form/form-field/form-field.scss, src/app/styles/base/forms.scss
Fix color contrast ratio issue for 'Low Priority' on graphs for Batch accounts [AD#434](https://azurebatch.visualstudio.com/BatchExplorer/_workitems/edit/434):
Fix color contrast ratio issue for account naming suffix when creating a new Batch account [AD#437 ](https://azurebatch.visualstudio.com/BatchExplorer/_workitems/edit/437):
=> Accessibility M1: Fix luminosity contrast issues

src/client/core/batch-explorer-application.ts
As a security measure, Electron 9.0.0 stopped enabling the `file://` protocol when `webSecurity` is set to `false`.  See https://github.com/electron/electron/issues/23757
Closes #2274: Restores image previews in Task Output.
=> Adds explicit file:// protocol support

src/client/startup.ts
This changed in Electron 9. See this issue: https://github.com/electron/electron/issues/23664
=> Explicitly disable CORS when running the local dev server

scripts/azpipelines/upload-to-storage.ts
Used in the release pipeline.
Had not realized that the JS version of the file is being used in the release pipeline, and conversion to TS missed several imports and type definitions.
=> Fixes TypeScript in upload-to-storage

src/client/main-window/main-window.ts
Add undocked mode for devtools when running Batch Explorer in development mode. When selecting 'pause on exceptions' in devtools, Batch Explorer would freeze at splash screen but devtools wasn't visible.
=> Fix freezing issue for 'pause on exceptions' in splash screen

src/@batch-flask/core/data-store/user-specific-data-store/user-specific-data-store.spec.ts, src/@batch-flask/core/data-store/user-specific-data-store/user-specific-data-store.ts, src/app/components/layout/main-navigation/profile-button/profile-button.component.spec.ts, src/app/components/layout/main-navigation/profile-button/profile-button.component.ts, src/client/core/aad/auth/aad-user.ts, src/client/core/aad/auth/aad.service.spec.ts, src/client/core/aad/auth/aad.service.ts, src/client/core/aad/auth/user-decoder.ts
MSAL access tokens have a different interface, using `preferred_username` instead of `unique_name`. The AADUser object now has a new `username` attribute that abstracts away how the access token stores the username.
Also removed the following non-existent (and unused) attributes: `upn`, `given_name`, `last_name`.
Fixes #2334
=> Fixes username in profile button

src/@batch-flask/ui/table/table.scss
The sort icon color contrast (5.7:1) is the same as the label as shown in the screenshot below. When clicked, it turns blue.
=> Fix sort icon luminosity contrast ratio too low

src/app/components/pool/details/error-display/pool-error-display.component.spec.ts, src/app/components/pool/details/error-display/pool-error-display.html
The ResizeError details object has a format of `{ name: string, value: string }`, not `{ key: string, value: string }`, which the PoolErrorDisplayComponent was using.
=> Fix: Resize error name wasn't being displayed properly

.vscode/launch.json, package-lock.json, src/client/core/aad/aad-constants.ts, src/client/core/aad/auth-provider.spec.ts, src/client/core/aad/auth-provider.ts, src/client/core/aad/auth/aad.service.spec.ts, src/client/core/aad/authentication/authentication.service.spec.ts, src/client/core/aad/msal-cache-plugin.spec.ts, src/client/core/aad/msal-cache-plugin.ts, src/test/utils/mocks/auth/auth-provider.mock.ts
Caches user auth in secure data store
Introduces a persistent cache using the secure data store to store accounts and tokens, which avoids making users log in every time they start the app.
Fixes [AB#10633343](https://msazure.visualstudio.com/AzureBatch/_workitems/edit/10633343/)
=> Caches user auth in secure data store

src/app/components/layout/pinned-entity-dropdown/pinned-dropdown.component.spec.ts, src/app/components/layout/pinned-entity-dropdown/pinned-dropdown.html, src/app/components/layout/pinned-entity-dropdown/pinned-dropdown.scss
Fix bug [AB#574](https://azurebatch.visualstudio.com/3426cbfe-4c9a-4da4-88df-70f025a77017/_workitems/edit/574)
Previously, individual items could not be accessed through keyboard tabbing, only the Delete button for those items could. 
Individual items in the favorite item drop down can be accessed through keyboard tabbing now.
=> Fix favorite item pinned visual focus indicator through keyboard

.vsts/common/generate-sbom.yml, .vsts/darwin/ci.yml, .vsts/distribution.yml, .vsts/linux/ci.yml, .vsts/pipelines.yml, .vsts/update-en-loc.yml, .vsts/win/ci.yml, package-lock.json, package.json, test/spectron/test-app-start.spec.ts
This PR makes BatchExplorer compliant with the [Cybersecurity Executive Order](https://www.microsoft.com/en-us/federal/CyberEO.aspx) (CyberEO):
* Migrates the retail Azure Pipelines agents to secure and compliant 1ES Hosted Pools
* Adds a build task that generates SBOM (Software Bill of Materials) manifests for each package
=> CyberEO Compliance

src/@batch-flask/ui/browse-layout/toggle-filter-button/toggle-filter-button.component.spec.ts, src/app/components/gallery/application-list/gallery-application-list.component.spec.ts, src/app/services/compute/vm-size.service.spec.ts, src/app/services/compute/vm-size.service.ts, src/app/services/compute/vmsize_sample_responses.ts
Bringing back VM SKU API support.
* Switch to using Service VM SKUs API from pulling json information from GitHub
* Fix 'filter' typo
* Update repo to contain vm size category list and fix unit tests
=> [Re-land] Update to call List Supported Virtual Machine and Cloud Service SKUs

.vsts/darwin/sign.yml
Explicitly download .NET Core 2.1 for use by codesigning task on Mac agents. This is a mitigation step to make codesigning work until the task is upgraded.
=> Fix code-signing on Mac

src/@batch-flask/ui/datetime-picker/datetime-picker.component.spec.ts, src/@batch-flask/ui/datetime-picker/datetime-picker.component.ts, src/@batch-flask/ui/loading/loading.scss, src/@batch-flask/ui/select/select-dropdown/select-dropdown.component.ts, src/@batch-flask/ui/select/select.component.ts, src/app/components/account/details/programatic-usage/programing-sample/programing-sample.scss, src/app/components/gallery/application-action/choose-action.html, src/app/components/pool/action/add/os-picker/data-disk-picker/data-disk-picker.component.spec.ts, src/app/utils/pool-utils.ts
- Fix luminosity contrast ratio for "The node the task ran on doesn't exist anymore or is in an invalid state" warning for tasks by increasing background color:
=> March a11y Bug Fixes

package-lock.json, package.json
Addresses issue with caching multiple tokens for same user (AzureAD/microsoft-authentication-library-for-js#4486).
=> Bumps @azure/msal-node from 1.9.0 to 1.10.0

src/@batch-flask/ui/file/file-explorer/file-tree-view/file-tree-view.html, src/@batch-flask/ui/form/editable-table/editable-table.html
April accessibility bug fixes include improvements on a label name for the file tree view and making sure editable tables have different Name and LocalizedControlTypes.
=> April a11y Bug Fixes

CHANGELOG.md, ThirdPartyNotices.txt
=> Prepare for release 2.14.0

src/client/core/aad/aad-config.ts, src/client/core/aad/auth/aad.service.ts, src/client/core/aad/authentication/authentication.service.spec.ts, src/test/utils/mocks/auth/auth-provider.mock.ts
Fixes #2542
It looks like the AZ CLI changed their app configuration to disallow the redirect url "urn:ietf:wg:oauth:2.0:oob". Switched to using the recommended value of "https://login.microsoftonline.com/common/oauth2/nativeclient", however the proper fix is to stop using the AZ CLI's app ID and create our own for Batch Explorer.
=> Fix login failures due to AADSTS50011 error

.vsts/darwin/darwin-dependencies.yml, .vsts/distribution.yml, .vsts/pipelines.yml, .vsts/python-setup.yml, scripts/azpipelines/setup-python.sh
* Uses MacOS Big Sur (version 11) since the previous build image became unsupported
* Bumps Python 3.8 → 3.9
* Bumps pyenv 1.2.20 → 2.3.2
=> Updates MacOS build image

.vsts/python-setup.yml
Using 3.9.x generated a spurious warning about not specifying an exact Python version
=> Fix UsePythonVersion warning

src/@batch-flask/ui/buttons/clickable/clickable.component.ts, src/@batch-flask/ui/entity-commands-list/button/entity-command-button.component.spec.ts
Permissions checking is specifically looking for the "*" permission and doesn't handle custom roles which include specific actions like "Microsoft.Batch/batchAccounts/pools/write". Will re-enable this when the client-side permissions checking is made more robust.
Fixes #2077
=> Temporarily disable permissions checking on buttons

src/@batch-flask/ui/callout/callout.directive.ts, src/@batch-flask/ui/callout/callout.html, src/app/components/account/details/account-details.html, src/app/components/account/details/account-monitoring-section/account-monitoring-section.html, src/app/components/account/monitoring/monitor-chart/monitor-chart.html, src/app/components/pool/action/add/pool-create-basic-dialog.html, src/app/components/pool/action/add/pool-create-basic-dialog.scss, src/client/proxy/manual-proxy-configuration-window/manual-proxy-configuration-window.html
Merge multiple September accessibility bug fixes into master branch
Work Items:
[686](https://azurebatch.visualstudio.com/BatchExplorer/_workitems/edit/686/)
[790](https://azurebatch.visualstudio.com/BatchExplorer/_workitems/edit/790/)
[883](https://azurebatch.visualstudio.com/BatchExplorer/_workitems/edit/883/)
[999](https://azurebatch.visualstudio.com/BatchExplorer/_workitems/edit/999/)
[917](https://azurebatch.visualstudio.com/BatchExplorer/_workitems/edit/917/)
=> Add September Accessibility Bug Fixes

src/@batch-flask/ui/buttons/clickable/clickable.component.ts
Fix: [AB#1011](https://azurebatch.visualstudio.com/3426cbfe-4c9a-4da4-88df-70f025a77017/_workitems/edit/1011),
To repro can see [AB#609](https://azurebatch.visualstudio.com/3426cbfe-4c9a-4da4-88df-70f025a77017/_workitems/edit/609)
=> fix: Create button for storage container under data menu is broken

src/@batch-flask/ui/select/select-dropdown/select-dropdown.component.ts, src/@batch-flask/ui/select/select-dropdown/select-dropdown.html, src/@batch-flask/ui/select/select-dropdown/select-dropdown.i18n.yml, src/@batch-flask/ui/select/select.component.spec.ts, src/@batch-flask/ui/select/select.component.ts
fix: [AB#758](https://azurebatch.visualstudio.com/3426cbfe-4c9a-4da4-88df-70f025a77017/_workitems/edit/758)
=> fix: announce ‘no match’ information on subscription filter

package-lock.json, package.json
Lerna 4 leaked processes when using Ctrl-C to kill webpack-dev-server. Upgraded to Lerna 6 to resolve the issue.
=> Lerna upgrade (fix for orphaned dev-server processes on Windows)

.vsts/common/build-vars.ps1, .vsts/dependencies.yml, .vsts/linux/distribution.yml, .vsts/linux/linux-dependencies.yml, .vsts/linux/publish-npm-package.yml, .vsts/node-setup.yml, desktop/scripts/azpipelines/utils.ts, desktop/scripts/package/package-utils.ts, lerna.json, packages/common/package.json, packages/playground/package.json, packages/react/package.json, packages/service/package.json
Publishes 4 packages to a private artifact feed whenever the distribution pipeline runs (a release or a PR merge):
* @batch/ui-common
* @batch/ui-react
* @batch/ui-service
* @batch/ui-playground
Depending on the release type, the published packages are assigned distribution tag (`npm-dist-tag`), which can then be used to fetch packages of a certain type:
| Branch | Build Type | Dist Tag |
|--------|------------|---------|
| master | insider        | latest     |
| stable  | stable          | stable    |
| vnext    | vnext          | next       |
Even though each package shares the same version (`1.0.0`), the pipeline gets the version from each package's `package.json` and appends a build ID, which is the distribution tag and the build number. So each published package will have a version …
=> vNext: Publish NPM packages to private artifact feed

.vsts/win/sign.yml
.NET 2.x doesn't seem to be on our CI image anymore
=> Fixed Windows code signing

python/server/websocket_server.py, src/@batch-flask/core/keys.ts, src/@batch-flask/ui/form/form-field/form-field.html, src/@batch-flask/ui/notifications/notification-service.ts, src/@batch-flask/ui/notifications/toast/toast.component.ts, src/@batch-flask/ui/notifications/toast/toast.html, src/@batch-flask/ui/property-list/property-group/property-group.html, src/@batch-flask/ui/select/select.component.spec.ts, src/@batch-flask/ui/select/select.component.ts, src/app/components/account/details/programatic-usage/aad-credentials-picker/aad-credentials-picker.html, src/app/components/account/details/programatic-usage/aad-credentials-picker/generate-aad-app-secret/generate-aad-app-secret.html, src/app/components/account/details/programatic-usage/programatic-usage.html, src/app/components/account/details/programatic-usage/programing-sample/programing-sample.html, src/app/components/data/action/delete/delete-container-dialog.html, src/app/components/job/details/job-progress-status/job-progress-status.html, src/app/components/pool/details/pool-cost-card/pool-cost-card.html, src/app/components/pool/graphs/performance-graph/enable-app-insights-doc/enable-app-insights-doc.html, src/app/components/pool/graphs/performance-graph/enable-app-insights-doc/enable-app-insights-doc.i18n.yml, src/app/components/pool/graphs/pool-graphs.component.ts, src/app/components/pool/graphs/pool-graphs.html, src/app/components/pool/graphs/pool-graphs.i18n.yml, src/app/components/task/base/task-state/task-state.html
Various accessibility bugs, most related to VoiceOver, as well as improvements to localization.
=> Accessibility bug fixes

packages/common/src/ui-common/action/__tests__/action.spec.ts, packages/common/src/ui-common/form/__tests__/form.spec.ts, packages/common/src/ui-common/form/form.ts, packages/playground/src/ui-playground/demo/form/action-form-demo.tsx, packages/react/src/ui-react/account/__tests__/create-account-action.spec.tsx
Values should now be set through setValues() and updateValue() which will properly trigger change events
=> Make form values read-only

src/app/services/aad/auth.service.spec.ts, src/app/services/aad/auth.service.ts
Users may opt in to authenticate specific tenants by activating them in the authentication settings page.
=> Non-home tenants are inactive by default

CHANGELOG.md, package.json, src/app/components/account/base/auto-storage-account-picker/auto-storage-account-picker.component.ts
Removes test data that made storage accounts appear as "classic".
=> Hotfix release 2.16.1

packages/playground/src/ui-playground/demo/form/action-form-demo.tsx, packages/react/src/ui-react/components/editor/impl/MonacoEditorImpl.tsx
There are inconsistent editor contents when switching actions.
Cause by the debounceOnChange function holds the reference of onChange props from previous renders.
=> fix monaco editor impl bug

Localize/LocProject.json
- I forgot to set the CopyOption in LocProject.json, which meant that the language resjson files were not being generated. 
- This PR fixes that issue so that the i18n folder in each package will have language files formatted as resources.{lang}.resjson: resources.fr.resjson, resources.es.resjson, resources.ko.resjson, etc.
From the [OneLocBuild](https://ceapex.visualstudio.com/CEINTL/_wiki/wikis/CEINTL.wiki/107/Localization-with-OneLocBuild-Task?anchor=copyoption%2C-outputpath-(optional)]) docs:
CopyOption, OutputPath (Optional) 
- These two options facilitate the post-processing of resulting localized files when they are used together. When CopyOption is set to `LangIDOnName`, localized files are copied to OutputPath with a language ID in the filename such as {OutputPath}\A.ko.resx for …
=> Fix LocProject file so resjson files are generated

python/requirements.txt
Updated Batch CLI extensions (v9.0.0) require `azure-multiapi-storage` as explicit requirement.
=> Fixes #2662: Restores Python backend

packages/common/src/ui-common/action/__tests__/action.spec.ts, packages/common/src/ui-common/action/action.ts, packages/common/src/ui-common/form/__tests__/form.spec.ts, packages/common/src/ui-common/form/form.ts, packages/common/src/ui-common/form/internal/form-impl.ts, packages/common/src/ui-common/form/subform.ts, packages/common/src/ui-common/index.ts, packages/common/src/ui-common/localization/standard-localizer.ts, packages/react/src/ui-react/account/create-account-action.ts, packages/react/src/ui-react/components/form/__tests__/action-form.spec.tsx, packages/react/src/ui-react/components/form/action-form.tsx, packages/react/src/ui-react/components/form/list-form-layout.tsx
Action forms also have a default 'Discard changes' button now
=> Added support for resetting forms

packages/common/src/ui-common/http/__tests__/fetch-http-client.spec.ts, packages/common/src/ui-common/http/constants.ts, packages/common/src/ui-common/http/fetch-http-client.ts, packages/common/src/ui-common/http/http-client.ts
This can be used to add a friendly name to HTTP requests such as "CreateAccount" or "ScalePool" for debugging/logging purposes.
=> Add x-ms-command-name header support

packages/common/src/ui-common/action/__tests__/action.spec.ts, packages/common/src/ui-common/action/action.ts, packages/common/src/ui-common/form/parameter.ts, packages/playground/src/ui-playground/demo/form/action-form-demo.tsx, packages/react/src/ui-react/account/create-account-action.ts, packages/react/src/ui-react/components/form/__tests__/action-form.spec.tsx, packages/react/src/ui-react/components/form/action-form.tsx
- Friendly names to actions
- Action error logging
- ActionForm onError callback
=> Improve action logging & error handling

definitions/index.d.ts, src/@batch-flask/ui/form/form-field/form-field.scss, src/app/components/account/details/programmatic-usage/programming-sample/programming-sample.scss, src/app/components/layout/main-navigation/profile-button/profile-button.component.spec.ts, src/app/components/layout/main-navigation/profile-button/profile-button.component.ts, src/app/components/pool/action/scale/autoscale-formula-picker/autoscale-formula-picker.scss, src/app/components/tenant-picker/tenant-card.scss, src/app/styles/base/forms.scss
Add Developer menu item in Profile which would only appear while in dev mode. Fix some hardcoded color values to use our themes.
=> Theme colors will only show in dev mode

src/@batch-flask/ui/form/complex-form/complex-form.component.ts, src/@batch-flask/ui/form/complex-form/complex-form.html, src/app/components/account/base/auto-storage-account-picker/auto-storage-account-picker.component.ts, src/app/components/account/base/auto-storage-account-picker/auto-storage-account-picker.html, src/app/components/gallery/submit/submit-ncj-template.html, src/app/components/job/action/add/job-preparation-task-picker.html, src/app/components/job/action/add/job-release-task-picker.html
- [Bug 853]: [Keyboard Navigation-Batch Explorer-SetUp]: Keyboard focus does not land on the first interactive control as soon as we invoke the 'Setup' control in Storage accounts pane.
- [Bug 463]: [Keyboard Navigation -Batch Explorer - Job preparation task] After activating ‘Job preparation task’ keyboard focus does not lands on first interactive control.
- [Bug 593] [Keyboard Navigation-Batch Explorer-Gallery-V-Ray] Visual focus indicator does not moves to the "run job with auto pool" button.
- Updated the `bl-complex-form` implementation so that it automatically focuses the first element in any `nested-form`s when they open. As a result, this fixes all instances of `bl-complex-form` that had similar auto focus issues, not just the "Job preparation task" form in the bug above. For …
=> Keyboard accessibility bugs (463, 853, 593)

data/themes/classic.json, data/themes/dark.json, src/@batch-flask/ui/form/form-field/form-field.scss, src/app/components/account/monitoring/monitor-chart/monitor-chart.component.ts, src/app/styles/vendor/material-theme.scss
- [Bug 568] [Visual Requirement-Batch Explorer-Add a batch account] Luminosity contrast ratio of the text "eastus.batch.azure.com" is less than 4.5:1 i.e 2.5:1.
- [Bug 569] [Visual Requirement-Batch Explorer-Node states] Luminosity contrast ratio of the text "Idle" is less than 4.5:1 i.e 2.5:1.
- [Bug 589] [Visual Requirement-Batch Explorer-Add a pool to the account] On the Add a pool to the account blade, luminosity contrast ratio of the text " Container" is less than 4.5:1 i.e 3.7:1.
- Updated colors of monitor chart and other parts of the UI on the dashboard for both classic and dark themes to have luminosity contrast ratio >=4.5:1 — bug above was specific to classic theme
- Update `primary` text color to a slightly darker color to pass the contrast test. This should affect all places …
=> Luminosity contrast accessibility bugs (568, 569, 589) #2693

src/@batch-flask/ui/form/editable-table/editable-table.html
Fix for [AB#788](https://azurebatch.visualstudio.com/3426cbfe-4c9a-4da4-88df-70f025a77017/_workitems/edit/788) [Visual Requirement-Batch Explorer-Edit Metadata] Incorrect tooltip is define for delete metadata row icon under Edit metadata blade.
=> Accessibility fix for bug 788 ("delete metadata row" tooltip)

src/@batch-flask/ui/buttons/button.scss, src/@batch-flask/ui/select/select.component.ts, src/@batch-flask/ui/table/table.scss, src/app/components/data/home/data-home.html, src/app/components/pool/action/add/os-picker/os-offer-tile/os-offer-tile.scss, src/app/styles/vendor/material-theme.scss
- [865] [Keyboard Navigation-Azure Batch Explorer-Add a Pool]: Visual focus indicator is not visible for the multiple controls, while navigating using Tab key.
- [950] [Screen Readers-Azure Batch Explorer-Job>>Disable]: Visual focus indicator is not visible for the 'radio' buttons, while navigating using TAB key under the disable dialog.
- [990] [Screen Reader-Batch Explorer-Add button]: Focus moves to background while "Create a new empty container" pop-up is open.
- [702] [Keyboard Navigation - Batch Explore - Pools]: Focus order is not logical after refresh control under "Node" on "Pools" page. 
- [671] [Keyboard Navigation - Batch Explore - Add a batch account]: While closing the subscription dropdown whole dialog is getting close with esc key.
- `keydown` events handled by the …
=> Accessibility bug fixes (865, 950, 990, 702, 671)

src/app/components/pool/action/add/vm-size-picker/vm-size-picker.component.ts, src/app/components/pool/action/add/vm-size-picker/vm-size-picker.html, src/app/models/vm-size.ts
Example of what the table looked like before, with all values set to 0:
Example of the table now with correct values:
- also removed the OS Disk table column for cloud service skus
=> Fix cloud service sku values for vm picker table

src/@batch-flask/ui/buttons/button.component.spec.ts, src/@batch-flask/ui/buttons/button.component.ts, src/@batch-flask/ui/buttons/button.html, src/@batch-flask/ui/buttons/button.scss, src/@batch-flask/ui/buttons/clickable/clickable.component.ts, src/@batch-flask/ui/form/editable-table/editable-table.component.ts, src/@batch-flask/ui/form/editable-table/editable-table.html, src/@batch-flask/ui/metrics-monitor/metrics-monitor.scss, src/@batch-flask/ui/quotas/quota-display/quota-display.scss, src/@batch-flask/ui/tags/tag-list/tag-list.scss, src/@batch-flask/ui/toolbar/toolbar.scss, src/app/components/gallery/application-list/gallery-application-list.html, src/app/components/gallery/application-list/gallery-application-list.scss, src/app/components/layout/pinned-entity-dropdown/pinned-dropdown.html, src/app/components/pool/action/add/app-license-picker/app-license-picker.scss, src/app/styles/variables.scss
- [Bug 461] [Keyboard Navigation -Batch Explorer - 3DS Max] Tooltip content is not displayed on "3DS Max" button while navigating with keyboard.
- [Bug 604] [Programmatic Access-Batch Explorer- Gallery-Local template library] On the Set local folders containing your templates window, an incorrect structure is defined for the friendly name control.
- [Bug 605] [Screen Reader-Batch Explorer- Gallery-Local template library] On the Set local folders containing your templates window, the label (friendly name) is not associated with the control.
- [Bug 778] [Visual Requirement- Batch Explorer- Terminate button]: Tooltip is not visible on keyboard focus for terminate button.
- [Bug 573] [Programmatic Access-Batch Explorer-No favorite item pinned] Name is not defined for the control available …
=> Accessibility Bug Fixes (461, 573, 604, 605, 778)

desktop/tsconfig.scripts.json
`update-latest.ts` used an external dependency (`make-dir`) which didn't produce a valid namespace export in TypeScript. Enabling `esModuleInterop` creates a shim to ensure namespace exports so that the script runs correctly during deployment.
=> Fixes release deployment

.vsts/common/publish-packages.sh, .vsts/linux/publish-npm-package.yml
This was broken because the Git repo on the DevOps pipelines runs on a detached HEAD. Use the DevOps environment variable to read the target branch instead of using `git symbolic-ref`.
=> Fix package publishing script

desktop/i18n/resources.resjson, desktop/src/@batch-flask/ui/info-box/info-box.component.ts, desktop/src/@batch-flask/ui/info-box/info-box.html, desktop/src/@batch-flask/ui/info-box/info-box.i18n.yml, desktop/src/@batch-flask/ui/info-box/info-box.module.ts, desktop/src/@batch-flask/ui/list-and-show-layout/entity-details-list.html, desktop/src/@batch-flask/ui/server-error/server-error.html, desktop/src/@batch-flask/ui/tags/tags.html, desktop/src/app/components/account/browse/account-list/account-list.scss, desktop/src/app/components/job/base/job-state/job-state.scss, desktop/src/app/components/pool/base/pool-nodes-preview.scss, desktop/src/app/components/pool/graphs/heatmap/nodes-heatmap.component.spec.ts, desktop/src/app/components/pool/graphs/heatmap/nodes-heatmap.component.ts, desktop/src/app/components/pool/graphs/pool-state-graph/pool-state-graph.component.ts
This PR Fixes:
- [Bug 332] [Visual Requirement-Batch explorer-Pools] Luminosity contrast ratio of the focusable element is less than 3:1 i.e 1.2:1.
- [Bug 576] [Programmatic Access-Batch Explorer-Edit] On the Update the storage account blade, name and aria-expanded property are not defined for the expand and collapse button.
- [Bug 592] [Programmatic Access-Batch Explorer-Pools-Edit tags] On the pools blade, the name is not defined for the edit tags button.
- [Bug 601] [Programmatic Access-Batch Explorer-Pool-Nodes] The name is not defined for the toggle advanced filter button.
- [Bug 598] [Screen Reader-Batch Explorer-Jobs-Disable] ALT is not defined for the image available on the "Are you sure you want to disable job" dialog box.
I also [updated the …
=> Accessibility Fixes (332, 576, 592, 601, 598)

.vsts/darwin/distribution.yml, .vsts/darwin/entitlements.plist, .vsts/darwin/notarize.yml, .vsts/distribution.yml, desktop/electron-builder.yml
Notarizes the MacOS build of the desktop app for distribution on MacOS 10.15 and later.
Fixes #2182
=> MacOS Notarization

.vsts/distribution.yml
Notarization and code signing are making the MacOS distribution come extremely close (or over) the 60 minute default timeout.
=> Bump MacOS dist pipeline timeout to 2 hour

desktop/src/@batch-flask/core/i18n/locale.service.ts
- Fix the locale code for Portuguese in the desktop app so that the Portuguese translations render correctly 
- Add Indonesian to list of supported languages in the desktop app
- Checked multiple translation services and Edge/Google Chrome language settings, and it seems that the standard way to write the word ‘Indonesian’ in the Indonesian language for digital localization purposes is simply ‘Indonesia’ 
- Disable security warning for non-English characters for locale file
=> Add Indonesian translations and fix Portuguese locale code in desktop app

.vsts/common/setup-python.sh, .vsts/darwin/darwin-dependencies.yml, .vsts/linux/linux-dependencies.yml, .vsts/python-setup.yml, .vsts/win/win-dependencies.yml
Use pre-installed dependencies on MS images where possible instead of installing them at build-time. Also switch the `bux` install to use the `dev-setup` NPM script.
=> Build pipeline perf improvements

packages/bonito-core/src/http/__tests__/mock-http-client.spec.ts, packages/bonito-core/src/http/mock-http-client.ts
Added support for mocking UrlSearchParams bodies and fixed a minor issue where request URLs were ignored when setting expected requests.
=> Minor MockHttpClient improvements

util/common-config/jest-common.js
Using globals to configure ts-jest is deprecated.
=> Update ts-jest configuration to fix deprecation warning

desktop/src/app/components/pool/details/configuration/pool-configuration.component.ts, desktop/src/app/components/pool/details/configuration/pool-configuration.html, desktop/src/app/decorators/pool-decorator.ts
This was only enabled in dev mode before. Now that we've updated to the latest API version, we can enable it in production.
=> Enable node communication mode editing

desktop/src/@batch-flask/ui/notifications/toast/toast.scss, desktop/src/@batch-flask/ui/quick-list/quick-list-row-render/quick-list-row-render.scss, desktop/src/@batch-flask/ui/summary-card/summary-card.scss, desktop/src/app/styles/vendor/material-theme.scss
Notification close button focus outline color contrast:
-----------------
Calendar weekday text color contrast:
-----------------
Star icon focus outline color contrast:
-----------------
Subscription & resource group link colors (used to be regular text color):
-----------------
Also includes a very minor alignment fix on lists to vertically center the text.
Before:
After:
=> Accessibility fixes for color contrast, link colors

desktop/python/server/aad_auth.py, desktop/src/@batch-flask/core/data/targeted-data-cache/targeted-data-cache.ts, desktop/src/@batch-flask/core/record/decorators.ts, desktop/src/@batch-flask/core/record/record.spec.ts, desktop/src/app/components/data/shared/file-group-picker/file-group-picker.component.spec.ts, desktop/src/app/components/data/shared/file-group-picker/file-group-picker.component.ts, desktop/src/app/components/data/shared/file-group-picker/file-group-picker.html, desktop/src/app/components/gallery/submit/market-application.model.ts, desktop/src/app/components/gallery/submit/parameter-input/parameter-input.component.ts, desktop/src/app/components/gallery/submit/submit-ncj-template.component.ts, desktop/src/app/components/pool/action/add/container-configuration-picker/container-configuration-picker.component.spec.ts, desktop/src/app/models/azure-batch/pool/pool.spec.ts, desktop/src/app/models/blob-container.ts, desktop/src/app/services/core/data/storage-list-getter.ts, desktop/src/app/services/storage/blob-storage-client-proxy.ts, desktop/src/app/services/storage/models/storage-blob.ts, desktop/src/app/services/storage/storage-blob.service.ts, desktop/src/app/services/storage/storage-client.service.ts, desktop/src/app/services/storage/storage-container.service.ts
* Various issues with controls that were not rendered correctly in Gallery views
* Updates Python backend to MSAL
Fixes #2785
=> Fixes to gallery and to storage functionality

packages/bonito-core/src/form/parameter.ts, packages/bonito-ui/src/components/form/__tests__/tab-selector.spec.tsx, packages/bonito-ui/src/components/form/index.ts, packages/bonito-ui/src/components/form/tab-selector.tsx, packages/bonito-ui/src/components/form/text-field.tsx, packages/bonito-ui/src/form/__tests__/react-form.spec.tsx, packages/bonito-ui/src/form/react-form.ts, packages/playground/src/demo-routes.tsx, packages/playground/src/demo/form/action-form-demo.tsx, packages/playground/src/demo/form/tab-selector-demo.tsx, packages/playground/src/layout/demo-nav-menu.tsx
=> Add TabSelector form control

packages/playground/jest.config.js, util/common-config/jest-common.js, web/jest.config.js, web/src/__tests__/setup-tests.ts, web/src/components/__tests__/application.spec.tsx
These are non-production and their code coverage scores shouldn't be aggregated with production packages.
=> Disable code coverage for most of playground/web

desktop/i18n/resources.resjson, desktop/src/app/components/task/action/add/add-task-form.component.ts, desktop/src/app/components/task/action/add/add-task-form.html, desktop/src/app/components/task/action/add/add-task.i18n.yml, desktop/src/app/models/forms/create-task-model.ts, desktop/src/app/styles/base/forms.scss
=> Add requiredSlots disable logic for multi-instance tasks

package-lock.json, package.json, packages/service/package-lock.json, packages/service/package.json
This works around an issue using the service package inside the Azure portal when `bux link` is active. See AB#27200905 for details.
=> Move TypeSpec/Autorest dependencies to root of the repo

desktop/src/client/core/secure-data-store/crypto-service.spec.ts
The current value looks too much like a real secret. Switched to a more obviously fake string.
=> Make CryptoService tests use a more obviously fake key for tests

packages/bonito-core/src/environment/abstract-environment.ts, packages/bonito-core/src/environment/environment.ts, packages/bonito-core/src/http/__tests__/fetch-http-client.spec.ts, packages/bonito-core/src/http/__tests__/mock-http-client.spec.ts, packages/bonito-core/src/http/fetch-http-client.ts, packages/bonito-core/src/http/mock-http-client.ts, packages/bonito-core/src/index.ts, packages/bonito-core/src/util/__tests__/url.spec.ts, packages/bonito-core/src/util/index.ts, packages/bonito-core/src/util/url.ts
When using bonito in an environment with a base path (ie: pages that define a `<base>` tag), automatically normalize calls through HttpClient to include the base path if it is defined.
=> Add optional base URL path to environment

util/bux/cli.ts, util/bux/util.ts
Add support for multiple repositories to be used with bux operations.
These changes allow for bux to be used as a tool to symlink JavaScript modules from BatchExplorer shared libraries packages with multiple repositories (namely, the Batch Portal and CycleCloud repos).
See this work item for more context: https://msazure.visualstudio.com/AzureBatch/_workitems/edit/27253286/
What the output looks like when running the commands in the portal:
```
PS C:\Users\sanjanakapur\Batch-UX-Portal> node_modules/.bin/bux configure
? Path to Batch Explorer (use /mnt/c/... for WSL, e.g., CycleCloud): C:\Users\sanjanakapur\BatchExplorer
Configuration saved to C:\Users\sanjanakapur\.config\batch\bux.json
PS C:\Users\sanjanakapur\Batch-UX-Portal> node_modules/.bin/bux status   
Batch Explorer (main)
- Path: …
```
=> Add support for multiple repos to bux tooling

desktop/config/webpack.config.base.js
Copy `src/client/recover-window/recover-window.html` into the build output directory to fix recover window fails to load in production build.
=> fix recover window failed to load in prod build

packages/bonito-core/src/form/internal/form-impl.ts
This prevents warnings, as forms are intended to have a lot of listeners (3 per parameter)
=> Bump max listeners for form event emitters

index.js
This will allow us to turn off public storage account access
=> Switch insider downloads to use CDN
